import type { Deep } from "./deep";

export const DEEP_A: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 1 */
  "best-seo-expert-in-islamabad": {
    updatedAt: "2026-10-09T03:00:00+05:00",
    blocks: [
      { type: "h2", text: "How the best SEO experts in Islamabad think about your market" },
      { type: "p", text: "Ask a weak SEO provider about your business and you will hear about keywords and backlinks within the first minute. Ask a strong one and the first questions are about your customers: who buys, where they live or work, what they compare you against, how long they take to decide and what one new client is worth. That difference matters more in Islamabad than almost anywhere else in Pakistan, because the city rewards precision over volume." },
      { type: "p", text: "Consider how differently three Islamabad businesses need to be handled. A corporate law firm in Blue Area sells to a few dozen decision makers a year, each worth a great deal, who read carefully and shortlist before calling. A pharmacy in G-9 serves hundreds of nearby residents who decide in minutes on their phones. A property developer in DHA sells largely to overseas Pakistanis who cannot visit the site and need every doubt answered online. The best SEO expert recognises that these are three different problems, and the plan, the content and even the reporting look different for each." },
      { type: "table", caption: "How a strong expert adapts the plan to the business", head: ["Business type", "Main search behaviour", "Where the expert focuses"], rows: [
        ["Professional services (Blue Area)", "Research-heavy, desktop, English", "Credibility pages, detailed service pages, thought leadership"],
        ["Neighbourhood services (G-9, F-10)", "Urgent, mobile, near me", "Google Business Profile, reviews, sector pages"],
        ["Property and investment (DHA, Bahria)", "Overseas buyers, high value", "Project pages, documentation guides, trust signals"],
        ["Education (multi-campus)", "Seasonal, parents comparing", "Campus pages, fees, admission timing"],
        ["Healthcare (clinics, hospitals)", "Trust-driven, local", "Doctor credentials, procedure pages, local profiles"],
      ] },
      { type: "h2", text: "What a strong first audit looks like" },
      { type: "p", text: "The free or paid audit is the most revealing document you will receive during the selection process, because it shows how someone thinks before they have your money. A strong audit for an Islamabad business is short at the top and specific underneath. It opens with a plain-language summary of the three to five problems that matter most, then supports each with evidence from your site." },
      { type: "list", items: [
        "**It names your pages.** Not “improve your titles” but “your F-10 clinic page has the title Home and does not mention dentistry”.",
        "**It uses your data.** Queries from Search Console, pages that already get impressions, and calls or forms you already receive.",
        "**It compares you with real competitors.** The businesses actually ranking above you in Islamabad, not national brands you will never compete with.",
        "**It ranks fixes by impact.** You know what to do first, second and third.",
        "**It admits uncertainty.** Good experts say where they need more data or a few weeks of testing before committing to a forecast.",
      ] },
      { type: "callout", tone: "tip", title: "A practical test", text: "Send the same URL to three candidates and ask each for their top three recommendations. If two of them independently name the same problem, you have probably found your real constraint, and the candidate who explained it most clearly is likely the one to hire." },
      { type: "h2", text: "Agency, consultant or freelancer: which kind of expert suits you" },
      { type: "p", text: "The best SEO expert for your business might work in any of three models. Agencies offer capacity and a range of skills, but accounts are often handled by junior staff. Independent consultants offer direct access to experience, but have limited capacity. Freelancers offer flexibility and lower cost for defined tasks, but vary widely in experience and availability. None is automatically better. What matters is matching the model to your needs and knowing who will actually do the work." },
      { type: "bars", title: "What different Islamabad businesses usually need most", items: [
        { label: "Strategy and judgement", value: 5, display: "Consultant" },
        { label: "Ongoing multi-channel delivery", value: 4, display: "Agency" },
        { label: "Defined one-off tasks", value: 3, display: "Freelancer" },
        { label: "Training an in-house team", value: 3, display: "Consultant" },
      ], note: "A rough guide to matching the delivery model to the need." },
      { type: "h2", text: "What to expect in the first 90 days" },
      { type: "p", text: "Once you have chosen, the first quarter should follow a recognisable pattern. In the first two weeks, access is set up properly, tracking is installed and the audit is turned into a written plan. Weeks three to six focus on the fixes and quick wins with the highest impact: technical problems, the Google Business Profile and the most important service pages. Weeks seven to twelve build on that foundation with new pages for real search demand, local citations and the first authority-building work." },
      { type: "p", text: "By day 90 you should be able to see three things clearly: what was done, what changed in rankings and visibility, and what changed in enquiries. If you can see the first but not the second or third, ask why. Sometimes the answer is legitimate, such as a competitive category that takes longer, but you deserve a clear explanation and a revised plan rather than another month of activity reports." },
      { type: "checklist", title: "Signs your new SEO expert is on track at day 90", items: [
        "You received a written plan in the first two weeks",
        "Critical technical issues have been fixed and documented",
        "Your Google Business Profile is complete and reviews are growing",
        "Key service pages have been improved or created",
        "Calls, WhatsApp clicks and forms are tracked",
        "Rankings for priority terms are moving in the right direction",
        "The monthly report explains results in plain language",
      ] },
    ],
    faqs: [
      { q: "What questions should I ask the best SEO expert in Islamabad before hiring?", a: "Ask what they would fix first on your site and why, which numbers they will report monthly, how they earn links without paying, who will do the work each week, and whether you own the content and accounts if you stop." },
      { q: "How do I know if my SEO expert is doing a good job?", a: "By day 90 you should have a written plan, documented technical fixes, a complete Business Profile, improved service pages, working enquiry tracking and visible movement for priority terms, all explained in a clear monthly report." },
    ],
  },

  /* ------------------------------------------------------------------ 2 */
  "hire-seo-expert-islamabad": {
    blocks: [
      { type: "h2", text: "Writing a brief that attracts the right SEO expert" },
      { type: "p", text: "A good brief does two jobs. It helps strong candidates quote accurately, and it quietly filters out weak ones, who tend to respond with the same generic proposal regardless of what you wrote. The more specific you are about your business, the easier it is to see who actually read it." },
      { type: "p", text: "Here is an illustrative example of a brief for a physiotherapy clinic in Islamabad. Notice that it says nothing about keywords or backlinks; it describes the business and the outcome, and leaves the method to the expert." },
      { type: "quote", text: "We run a physiotherapy clinic in G-11 with three therapists. Most patients come from G-9 to G-13 and from F-10 and F-11. We want more bookings for back pain, sports injuries and post-surgery rehabilitation. A new patient is worth roughly PKR 25,000 over their treatment. Our budget is around PKR 60,000 a month. Our practice manager will approve content within two days. We can give access to our website, Search Console and Google Business Profile.", cite: "Illustrative brief for a G-11 physiotherapy clinic" },
      { type: "p", text: "From a brief like this, a capable SEO expert can immediately see the opportunity: sector-level local search, a few high-value treatment pages, a Business Profile to strengthen, and a realistic budget for ongoing work. A provider who replies with a package of “30 backlinks and 4 blog posts a month” has not engaged with your business at all." },
      { type: "h2", text: "Scoring candidates objectively" },
      { type: "p", text: "Hiring decisions often come down to who seemed most confident in a meeting. A simple scoring sheet reduces that bias. Score each candidate from one to five on each criterion, weight them, and compare totals. The exercise also makes it easier to explain the decision to partners or colleagues." },
      { type: "table", caption: "SEO hiring scorecard", head: ["Criterion", "What a 5 looks like", "Weight"], rows: [
        ["Audit quality", "Specific to your site, ranked by impact, clear evidence", "×3"],
        ["Relevant results", "Verified outcomes for similar businesses in the twin cities", "×3"],
        ["Plan clarity", "A 90-day plan you understand and could explain to someone else", "×2"],
        ["Reporting", "Enquiries, calls and WhatsApp tracked, not just rankings", "×2"],
        ["Communication", "Responsive, honest about limits, easy to understand", "×2"],
        ["Terms", "Monthly, with your ownership of content and accounts", "×1"],
        ["Price", "Fair for the scope described", "×1"],
      ] },
      { type: "callout", tone: "note", title: "Why price has the lowest weight", text: "Price matters, but it is meaningless on its own. A higher fee that produces enquiries is cheaper than a lower fee that produces reports. Score price only after you understand what each quote actually includes." },
      { type: "h2", text: "Running a short paid trial" },
      { type: "p", text: "If you are torn between two strong candidates, a paid trial of two to four weeks can settle it. Choose a task that is useful whatever happens, such as optimising your Google Business Profile and your two most important service pages, or carrying out a technical audit with fixes. Pay a fair price, agree the deliverables in writing, and judge both the quality of the work and how the person communicates along the way." },
      { type: "list", items: [
        "**Keep the trial small and useful.** The work should benefit your site even if you choose someone else.",
        "**Agree how you will judge it.** Quality of work, clarity of explanation, speed of response and respect for deadlines.",
        "**Pay properly.** Unpaid trials attract people with nothing better to do, not the experts you want.",
        "**Watch communication closely.** How someone handles questions during a trial is how they will handle problems later.",
      ] },
      { type: "h2", text: "Your responsibilities after hiring" },
      { type: "p", text: "SEO results depend partly on the client. The most successful Islamabad engagements we see share a few habits on the business side. Someone in the business owns the relationship and responds quickly. Content is reviewed within days, not weeks. Sales feedback flows back to the SEO expert: which enquiries were good, which were time-wasters, which services customers asked about. And the business keeps its side of the review routine, asking satisfied customers for reviews consistently." },
      { type: "compare", title: "Clients who get results versus clients who stall", left: { label: "Stalling clients", items: [
        "Take weeks to approve content",
        "Never share sales feedback",
        "Change priorities every month",
        "Forget to ask customers for reviews",
      ] }, right: { label: "Clients who get results", items: [
        "Approve content within a few days",
        "Share which enquiries became customers",
        "Hold priorities steady for a quarter",
        "Ask every happy customer for a review",
      ] } },
      { type: "h2", text: "When and how to end an SEO engagement" },
      { type: "p", text: "Not every hire works out. If after 90 days you cannot see clear progress, the reports are vague, or communication has broken down, it is reasonable to end the engagement. Doing it cleanly protects your site. Give the agreed notice, ask for a handover document listing every change made, links built and accounts touched, remove the provider’s user access from every tool, and change any password that was ever shared. Then review the site yourself or with a new expert before starting again, so you know exactly what you are inheriting." },
      { type: "checklist", title: "Clean exit checklist", items: [
        "Give written notice under the agreed terms",
        "Request a handover document of all changes and links",
        "Confirm you own every account and all content",
        "Remove user access from Search Console, Analytics, Business Profile and website",
        "Change any password that was shared",
        "Download the last reports and keep them on file",
      ] },
    ],
    faqs: [
      { q: "Should I run a paid trial before hiring an SEO expert?", a: "If you are choosing between two strong candidates, a paid two to four week trial on useful work, such as Business Profile and service page optimisation, shows how each person works and communicates." },
      { q: "What should an SEO handover include when I change providers?", a: "A list of every change made to the site, every link built, every account accessed and the latest reports. Then remove their access and change any shared passwords." },
    ],
  },

  /* ------------------------------------------------------------------ 3 */
  "seo-specialist-islamabad": {
    blocks: [
      { type: "h2", text: "A week in the life of an SEO specialist" },
      { type: "p", text: "It helps to know what an SEO specialist actually spends their time on, because it explains what you are paying for. The work is less about secret techniques and more about steady, careful attention across several areas at once. For a specialist handling a handful of Islamabad clients, a typical week might look like this." },
      { type: "table", caption: "A typical week", head: ["Day", "Main focus"], rows: [
        ["Monday", "Review rankings, Search Console changes and enquiries for each client; flag anything unusual"],
        ["Tuesday", "Technical work: fixing indexing issues, speed problems and redirects with developers"],
        ["Wednesday", "Content: briefing writers, editing service pages, adding FAQs and internal links"],
        ["Thursday", "Local and off-page: Business Profile updates, review replies, citation and outreach work"],
        ["Friday", "Reporting and planning: monthly reports, client calls and next week’s priorities"],
      ] },
      { type: "p", text: "The rhythm matters. A specialist who checks data first every week catches problems early: a page that dropped out of the index, a sudden fall in calls from the Business Profile, a competitor that launched a new set of area pages. That early warning is part of the value, and it is something no automated report replaces." },
      { type: "h2", text: "Skills that set great specialists apart" },
      { type: "p", text: "Most SEO specialists can list the same core skills. What sets the best apart is a handful of less visible abilities that only show up in practice." },
      { type: "list", items: [
        "**Prioritisation.** Knowing which three of the fifty possible fixes will actually move results this quarter.",
        "**Translation.** Explaining a technical problem to a developer and a business problem to an owner, in each person’s language.",
        "**Commercial sense.** Understanding margins, seasonality and sales cycles, so effort goes where revenue is.",
        "**Writing.** Clear, accurate English, and the ability to work naturally with Roman Urdu phrasing where customers use it.",
        "**Scepticism.** Testing claims, checking data and not accepting every tool score or industry rumour at face value.",
        "**Patience.** Holding a strategy steady long enough for it to work, instead of chasing every ranking fluctuation.",
      ] },
      { type: "callout", tone: "tip", title: "How to spot these skills", text: "Ask a candidate to explain one technical issue on your site as if you were the developer, and then again as if you were the owner. The quality of both explanations tells you a lot about how well they will work with your team." },
      { type: "h2", text: "Certifications: what they prove and what they do not" },
      { type: "p", text: "SEO has no licensing body, and certificates range from useful to meaningless. Google offers free certifications for products such as Analytics and Ads, which show a person has studied those tools. Paid courses and private institutes issue their own certificates. All of these show some learning; none proves the ability to rank a website. In Islamabad, as elsewhere, the reliable evidence is a portfolio of real work with measurable outcomes." },
      { type: "compare", title: "Credentials versus evidence", left: { label: "Useful but limited", items: [
        "Course completion certificates",
        "Tool certifications",
        "Years listed on a CV",
        "Number of followers on social media",
      ] }, right: { label: "Strong evidence", items: [
        "Live sites you can check yourself",
        "Dated Search Console screenshots",
        "References from current clients",
        "Clear explanations of past decisions",
      ] } },
      { type: "h2", text: "How SEO specialists work with your team" },
      { type: "p", text: "An SEO specialist rarely works alone. They depend on your developer to implement technical changes, your content writer or subject experts to provide accurate information, and your front desk or sales team to handle the enquiries that SEO produces. The best results come when these relationships are set up clearly from the start." },
      { type: "process", title: "Who does what", steps: [
        { title: "Specialist", text: "Diagnoses, plans, briefs, checks" },
        { title: "Developer", text: "Implements technical fixes" },
        { title: "Subject expert", text: "Provides accurate detail" },
        { title: "Front desk", text: "Converts enquiries" },
      ] },
      { type: "p", text: "In smaller Islamabad businesses, one person may cover several of these roles, and the specialist may do some implementation directly. That is fine, as long as everyone knows who is responsible for each task and how quickly it should happen." },
      { type: "h2", text: "In-house specialist or outsourced?" },
      { type: "p", text: "Larger businesses sometimes consider hiring a full-time SEO specialist instead of an outside provider. An in-house specialist knows the business deeply and is always available, but costs a full salary, may lack breadth of experience, and can become isolated without peers to learn from. An outsourced specialist brings experience from many sites and costs less, but has less time for your business specifically." },
      { type: "table", caption: "In-house versus outsourced SEO specialist", head: ["Factor", "In-house", "Outsourced"], rows: [
        ["Cost", "Full salary and benefits", "Monthly fee for agreed scope"],
        ["Business knowledge", "Deep", "Grows over time"],
        ["Breadth of experience", "Limited to your site", "Draws on many sites and sectors"],
        ["Availability", "Full-time", "Scheduled and on request"],
        ["Best for", "Large sites, many pages, constant changes", "Most small and mid-sized businesses"],
      ] },
      { type: "p", text: "A common middle path is a junior in-house marketer supported by an experienced outside specialist who sets strategy and reviews the work. It combines daily attention with expert judgement, at a cost that suits many growing Islamabad companies." },
      { type: "p", text: "Whichever route you choose, the test is the same: can you see, each month, what was done, why it was done and what it changed? A specialist who makes that visible is worth keeping, whether they sit in your office or work with you remotely from across the city." },
    ],
    faqs: [
      { q: "Do SEO certifications matter when hiring a specialist?", a: "They show some learning, but they do not prove the ability to rank websites. Live results, dated Search Console data and client references are far stronger evidence." },
      { q: "How many clients should an SEO specialist handle?", a: "It depends on the size of each account, but a specialist doing hands-on work for local businesses can usually give proper attention to a limited number at once. Ask how many active clients they have and how many hours a month your account will receive." },
      { q: "What should an SEO specialist report every month?", a: "Rankings for priority terms, organic traffic to key pages, Business Profile calls and direction requests, tracked enquiries from forms and WhatsApp, what was done that month, and the plan for the next one." },
      { q: "Should I hire an in-house SEO specialist or outsource?", a: "In-house suits large sites with constant changes. Most small and mid-sized businesses get better value from an outsourced specialist, or a junior in-house marketer supported by one." },
    ],
  },

  /* ------------------------------------------------------------------ 4 */
  "seo-consultant-islamabad": {
    blocks: [
      { type: "h2", text: "What an SEO consultant’s deliverables actually look like" },
      { type: "p", text: "Because consultants sell advice rather than hours of execution, it is important to know what you will physically receive. Vague deliverables are the main source of disappointment in consulting engagements. Before you sign, ask to see an anonymised example of each document the consultant will produce." },
      { type: "table", caption: "Typical consulting deliverables", head: ["Deliverable", "What it contains", "Who uses it"], rows: [
        ["Audit report", "Summary, top issues by impact, evidence, recommended fixes", "Owner and team"],
        ["Prioritised roadmap", "Actions by quarter with owners and effort", "Owner and project lead"],
        ["Developer tickets", "Technical fixes written as tasks with acceptance criteria", "Developer"],
        ["Content briefs", "Target topic, intent, outline, questions to answer, internal links", "Writers"],
        ["Session notes", "Decisions made, actions agreed, next review date", "Everyone"],
      ] },
      { type: "p", text: "Developer tickets and content briefs deserve special attention. A consultant who can turn findings into tasks your team can execute without further translation saves you a great deal of time. A consultant who hands over a 60-page report and leaves you to work out what to do with it has only done half the job." },
      { type: "h2", text: "An illustrative example: a migration done right" },
      { type: "p", text: "Imagine a mid-sized Islamabad training institute rebuilding its website on a new platform. It has eight years of rankings for course names and city terms, and the new design changes almost every URL. Without care, a migration like this can wipe out a large share of organic enquiries overnight. A consultant’s role would look something like this." },
      { type: "list", ordered: true, items: [
        "**Before design is final:** crawl the old site, export every URL with traffic or links, and identify the pages that matter most.",
        "**During development:** map every old URL to its new equivalent, review the new templates for titles, headings, internal links and structured data, and check the staging site is blocked from indexing.",
        "**At launch:** confirm 301 redirects are live, the staging block is removed, the sitemap is updated and Search Console is told about the change where relevant.",
        "**After launch:** monitor indexing, rankings and enquiries daily for the first two weeks and weekly for two months, fixing any missed redirects quickly.",
      ] },
      { type: "p", text: "The consultant does not build the site; the developer does. But the consultant’s checklist and monitoring are what protect eight years of accumulated visibility. This is a classic case where a few days of expert time are worth far more than they cost." },
      { type: "callout", tone: "warn", title: "The most expensive SEO mistake", text: "Launching a redesign without redirects is the single most damaging thing we see Pakistani businesses do to their own search visibility. If you are planning a new website, involve an SEO consultant before the design is signed off." },
      { type: "h2", text: "Overseeing an agency without micromanaging it" },
      { type: "p", text: "Many Islamabad businesses already pay an agency but have no way to judge whether the work is good. A consultant can provide that oversight. The aim is not to second-guess every task, but to check direction and quality at regular intervals." },
      { type: "slides", title: "A quarterly agency review", slides: [
        { title: "Results", points: ["Have enquiries from search grown?", "Are priority rankings moving?", "Is reporting honest about what did not work?"] },
        { title: "Work quality", points: ["Are technical fixes done properly?", "Is content accurate and useful?", "Are links relevant and safe?"] },
        { title: "Direction", points: ["Does the plan still fit the business?", "Is effort focused on the right services?", "What should change next quarter?"] },
      ] },
      { type: "p", text: "Agencies that do good work usually welcome this kind of review because it gives the client confidence. Agencies that resist any outside scrutiny are telling you something too." },
      { type: "h2", text: "Building an in-house SEO capability with a consultant" },
      { type: "p", text: "Some businesses want to bring SEO in-house over time. A consultant can accelerate that by training your team, setting up processes and gradually stepping back. A typical path runs over six to twelve months: the consultant leads at first, then shares the work, then reviews it, and finally checks in quarterly." },
      { type: "process", title: "From consultant-led to in-house", steps: [
        { title: "Lead", text: "Consultant plans and directs" },
        { title: "Share", text: "Team does tasks with guidance" },
        { title: "Review", text: "Team leads, consultant checks" },
        { title: "Advise", text: "Quarterly strategy reviews" },
      ] },
      { type: "p", text: "This approach builds lasting skills inside the business, which is valuable in a market where good SEO people are in demand and staff move on. Document processes and checklists as you go, so knowledge stays with the company rather than with one person." },
      { type: "h2", text: "Red flags in an SEO consultant" },
      { type: "list", items: [
        "**Refuses to show examples** of past deliverables, even anonymised.",
        "**Promises specific rankings** rather than explaining likely outcomes and risks.",
        "**Gives the same advice to every business**, regardless of sector or city.",
        "**Avoids data**, preferring opinions to Search Console and Analytics evidence.",
        "**Pushes long retainers** before you have seen the quality of their thinking.",
      ] },
      { type: "p", text: "The opposite signals are just as telling. A good consultant asks about your margins and sales process before talking about tactics, shows you how they reached each recommendation, is comfortable saying a question needs more data, and is happy to start with a small, well-defined piece of work. In a city like Islamabad, where many businesses depend on a modest number of high-value clients, that kind of careful, evidence-led advice is usually worth far more than a long list of generic SEO tasks." },
    ],
    faqs: [
      { q: "What deliverables should I expect from an SEO consultant?", a: "Typically an audit report, a prioritised roadmap, developer tickets for technical fixes, content briefs for writers and notes from each strategy session. Ask to see anonymised examples before signing." },
      { q: "How much time does an SEO consulting engagement need from my team?", a: "Expect a few hours a month for strategy sessions and reviews, plus time for your developer and writers to implement recommendations. Consulting only produces results when someone acts on the advice." },
      { q: "Is an SEO consultant worth it for a small business?", a: "Often yes for a one-off audit or a redesign, because a few days of expert advice can prevent costly mistakes. For ongoing work, a small business with no in-house team may be better served by a provider who also implements." },
      { q: "Can an SEO consultant help with a website redesign?", a: "Yes, and it is one of the most valuable times to involve one. A consultant maps old URLs to new ones, reviews templates and monitors the launch to protect existing rankings." },
    ],
  },
};
