import type { Deep } from "./deep";

export const DEEP_C: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 11 technical */
  "technical-seo-expert": {
    blocks: [
      { type: "h2", text: "Crawl budget: when it matters and when it does not" },
      { type: "p", text: "Crawl budget is the amount of attention Googlebot gives your site: how many URLs it is willing and able to crawl in a given period. For most small business websites in Islamabad, with a few dozen or a few hundred pages, crawl budget is not a real constraint and you should not worry about it. It becomes important for large sites: online stores with thousands of products and filter combinations, property portals with expiring listings, news sites and directories." },
      { type: "table", caption: "Does crawl budget matter for your site?", head: ["Site type", "Typical size", "Crawl budget concern"], rows: [
        ["Local business site", "10–200 pages", "Rarely"],
        ["Multi-location or multi-service business", "200–2,000 pages", "Sometimes, if many thin pages exist"],
        ["Online store with filters", "Thousands to hundreds of thousands of URLs", "Often"],
        ["Property or classified listings", "Large and constantly changing", "Usually"],
      ] },
      { type: "p", text: "On large sites, the main crawl budget problems are wasted URLs: filter combinations, session parameters, duplicate sort orders, internal search results and expired listings. A technical SEO expert finds where Googlebot spends its time using server logs and Search Console’s crawl stats, then reduces waste with better internal linking, canonical tags, parameter handling, robots rules and removal of genuinely useless URLs." },
      { type: "h2", text: "JavaScript websites and rendering" },
      { type: "p", text: "Many modern Pakistani websites, especially from software houses, are built with JavaScript frameworks. Google can render JavaScript, but rendering takes extra resources, may happen later than crawling, and fails if important content depends on actions such as clicking or scrolling. If your key content or links only appear after JavaScript runs in the browser, there is a risk Google will not see them, or will see them late." },
      { type: "compare", title: "Rendering approaches for SEO", left: { label: "Riskier for SEO", items: [
        "Content loaded only in the browser after page load",
        "Links that only work through click handlers",
        "Important text inside tabs that load on demand",
        "Different content for bots and users",
      ] }, right: { label: "Safer for SEO", items: [
        "Server-side rendering or static generation",
        "Real anchor links with href attributes",
        "Key content present in the initial HTML",
        "The same content for bots and users",
      ] } },
      { type: "p", text: "The quickest check is to use Search Console’s URL Inspection tool on an important page and look at the rendered HTML and screenshot. If the main content or links are missing, a technical SEO expert should work with your developers on server-side rendering, static generation or a hybrid approach." },
      { type: "h2", text: "Structured data that actually helps" },
      { type: "p", text: "Structured data, usually written in JSON-LD, describes your content to search engines in a machine-readable way. It does not directly boost rankings, but it can make pages eligible for richer search features and helps search and AI systems understand who you are and what you offer. The rule that matters most is that markup must reflect content visible on the page." },
      { type: "table", caption: "Useful structured data by page type", head: ["Page", "Schema types to consider"], rows: [
        ["Home and About", "Organization or LocalBusiness, with logo, contact details and sameAs profiles"],
        ["Location pages", "LocalBusiness with address, geo, opening hours"],
        ["Service pages", "Service, plus FAQPage only where FAQs are visible"],
        ["Products", "Product with offers, price and availability"],
        ["Articles", "Article or BlogPosting with author and dates"],
        ["Breadcrumbs", "BreadcrumbList on every inner page"],
      ] },
      { type: "callout", tone: "warn", title: "Never mark up what is not there", text: "Adding review stars, prices or FAQs to structured data when they are not visible on the page breaks Google’s guidelines and can lead to manual actions affecting rich results." },
      { type: "h2", text: "Monitoring: catching problems before they cost you" },
      { type: "p", text: "Technical SEO is not a one-time job. Sites change constantly: new plugins, theme updates, developer releases, content edits. Any of them can break something important. Basic monitoring catches problems early, often before rankings are affected." },
      { type: "checklist", title: "Technical monitoring routine", items: [
        "Weekly: check Search Console for new indexing errors and manual actions",
        "Weekly: confirm key pages still return a 200 status and are indexable",
        "Monthly: review Core Web Vitals and page speed on key templates",
        "Monthly: crawl the site to catch new broken links and redirect chains",
        "After every release: spot-check titles, canonicals and robots directives on changed templates",
        "Quarterly: review the XML sitemap and remove URLs that should not be there",
      ] },
      { type: "h2", text: "Working with developers effectively" },
      { type: "p", text: "Technical SEO only works if developers implement the fixes, and developers are busy. The best technical SEO experts write tickets that are easy to act on: the problem, the affected URLs, the expected behaviour, how to test it and why it matters to the business. Vague requests such as “improve site speed” sit in backlogs for months; precise tickets get done." },
      { type: "list", items: [
        "**Problem:** product pages return two canonical tags pointing to different URLs.",
        "**Affected:** all URLs under /products/.",
        "**Expected:** a single canonical tag pointing to the clean product URL.",
        "**Test:** view source on three product pages and confirm one canonical tag.",
        "**Impact:** conflicting canonicals can stop Google consolidating signals, weakening product rankings.",
      ] },
    ],
    faqs: [
      { q: "Does crawl budget matter for a small business website?", a: "Rarely. Crawl budget becomes important for large sites with thousands of URLs, such as online stores with filters or listing portals. Small sites are usually crawled fully without issue." },
      { q: "Can Google read JavaScript websites?", a: "Google can render JavaScript, but it takes extra resources and can be delayed or fail if content depends on user actions. Server-side rendering or static generation is safer for important content." },
      { q: "Does structured data improve rankings?", a: "Not directly. It helps search engines understand your content and can make pages eligible for rich results, as long as the markup matches what is visible on the page." },
    ],
  },

  /* ------------------------------------------------------------------ 12 WordPress */
  "wordpress-seo-expert": {
    blocks: [
      { type: "h2", text: "Choosing a WordPress theme with SEO in mind" },
      { type: "p", text: "Many SEO problems on WordPress sites start with the theme. Multipurpose themes bought for their demos often load sliders, animation libraries, icon fonts and page builder scripts on every page, whether you use them or not. A lightweight, well-coded theme gives you a far better starting point than any optimisation plugin can fix later." },
      { type: "checklist", title: "What to look for in a theme", items: [
        "Small page size on a default install, tested with PageSpeed Insights",
        "Clean heading structure with one H1 per page",
        "Compatibility with the block editor without a heavy page builder",
        "Regular updates and active support",
        "A legitimate licence, never a nulled copy",
        "Mobile layouts that keep phone numbers and buttons easy to tap",
      ] },
      { type: "p", text: "If you already have a heavy theme, you do not always need to rebuild. Often the biggest gains come from disabling unused features, replacing sliders with a single static image, and removing modules you never use. A WordPress SEO expert can tell you whether optimisation or a rebuild is the better investment." },
      { type: "h2", text: "Hosting choices for Pakistani WordPress sites" },
      { type: "p", text: "Hosting has a direct effect on speed, and speed affects both rankings and conversions. Cheap shared hosting can be fine for a small brochure site, but busy sites or sites with WooCommerce often outgrow it. Server location matters too: most of your visitors are in Pakistan, so a server or content delivery network with good routes to Pakistani users helps." },
      { type: "table", caption: "Hosting options compared", head: ["Option", "Good for", "Watch out for"], rows: [
        ["Basic shared hosting", "Small brochure sites with low traffic", "Slow response times at busy periods"],
        ["Managed WordPress hosting", "Business sites that want speed and support", "Higher cost; check what is included"],
        ["VPS or cloud server", "Larger sites, WooCommerce, custom needs", "Needs technical management and security"],
        ["Any of the above plus a CDN", "Faster delivery of images and files", "Correct cache configuration needed"],
      ] },
      { type: "h2", text: "WooCommerce SEO essentials" },
      { type: "p", text: "Many Pakistani online stores run on WooCommerce. It is flexible but needs care. Product categories should match how customers search, product pages need unique descriptions rather than supplier copy, and filter plugins can generate large numbers of near-duplicate URLs if left unchecked. Out-of-stock and discontinued products also need a plan, so customers and Google are not left with dead ends." },
      { type: "list", items: [
        "**Categories first.** Treat category pages as landing pages with short, helpful introductions.",
        "**Unique product copy.** Add fabric, size, compatibility, care and delivery details.",
        "**Control filters.** Keep sort and multi-filter URLs out of the index.",
        "**Product schema.** Make sure price, currency and availability are accurate.",
        "**Checkout speed.** Remove scripts that slow the cart and checkout pages.",
      ] },
      { type: "h2", text: "Security as an SEO issue" },
      { type: "p", text: "Hacked WordPress sites are common in Pakistan, often through outdated plugins or nulled themes. Hackers inject hidden spam links, create thousands of junk pages or redirect visitors to other sites. Google may warn users away from the site, and rankings can collapse. Recovery takes time, so prevention is far cheaper." },
      { type: "checklist", title: "WordPress security basics", items: [
        "Keep WordPress core, themes and plugins updated",
        "Use only licensed themes and plugins from trusted sources",
        "Use strong, unique passwords and two-factor login for admins",
        "Limit admin accounts to people who need them",
        "Keep automatic off-site backups",
        "Monitor Search Console for security issues and manual actions",
      ] },
      { type: "callout", tone: "tip", title: "Check for hidden spam", text: "Search site:yourdomain.pk followed by words like “casino” or “viagra” in Google. If results appear, your site may have injected spam pages that need urgent cleanup." },
      { type: "h2", text: "When to rebuild instead of optimise" },
      { type: "p", text: "Sometimes the honest answer is that a WordPress site is not worth saving: a theme that cannot be made fast, dozens of conflicting plugins, a hacked history and messy URLs. In those cases, a clean rebuild on a lightweight theme, with careful redirects from every old URL, can be the better investment. The key is to plan the SEO side before the rebuild starts, not after launch." },
    ],
    faqs: [
      { q: "Which WordPress theme is best for SEO?", a: "A lightweight, well-coded, regularly updated theme with a legitimate licence, clean heading structure and good mobile layouts. Avoid heavy multipurpose themes that load everything on every page." },
      { q: "Can a hacked WordPress site lose its rankings?", a: "Yes. Injected spam pages, hidden links and malicious redirects can trigger warnings and ranking drops. Keep everything updated, use licensed software and monitor Search Console." },
      { q: "Is WooCommerce good for SEO?", a: "Yes, when categories match search demand, products have unique descriptions, filters are controlled and product data is accurate." },
    ],
  },

  /* ------------------------------------------------------------------ 13 Shopify */
  "shopify-seo-expert": {
    blocks: [
      { type: "h2", text: "Shopify site structure and navigation" },
      { type: "p", text: "Shopify gives you collections, products and pages, and a navigation menu that ties them together. How you structure them decides which pages Google sees as important. A clear structure puts your main collections in the main menu, groups related sub-collections beneath them, and keeps important pages within a few clicks of the home page." },
      { type: "process", title: "A clear Shopify structure", steps: [
        { title: "Home", text: "Links to main collections" },
        { title: "Main collections", text: "Broad categories customers search" },
        { title: "Sub-collections", text: "Specific types, materials or uses" },
        { title: "Products", text: "Linked from the relevant collections" },
      ] },
      { type: "p", text: "Avoid creating collections purely for merchandising, such as dozens of seasonal or promotional collections that overlap heavily. They dilute signals and confuse both shoppers and search engines. If you need them for campaigns, consider keeping them out of the index or retiring them after the campaign." },
      { type: "h2", text: "International and multi-currency Shopify stores" },
      { type: "p", text: "Pakistani brands increasingly sell abroad, especially to the Gulf, the UK and North America. Shopify Markets lets you set up different currencies, prices and sometimes languages for different countries. From an SEO point of view, the important things are that each market version is reachable at a crawlable URL, that hreflang is set up correctly, and that content such as shipping times and duties is accurate for each market." },
      { type: "table", caption: "International Shopify checklist", head: ["Area", "What to check"], rows: [
        ["URLs", "Each market has its own crawlable URL, such as a subfolder"],
        ["Hreflang", "Correct language and country codes between versions"],
        ["Pricing", "Prices shown in the right currency for each market"],
        ["Shipping", "Delivery times and duties explained per market"],
        ["Content", "Sizes, spellings and examples adapted where needed"],
      ] },
      { type: "h2", text: "Product reviews and user-generated content" },
      { type: "p", text: "Genuine product reviews help shoppers decide and can add useful, unique text to product pages. Use a reputable review app, ask customers for reviews after delivery, and display them on product pages. Make sure any review structured data reflects real reviews shown on the page, never invented ratings." },
      { type: "list", items: [
        "Send review requests a few days after delivery, when customers have used the product.",
        "Encourage photos, especially for clothing and home products.",
        "Reply to negative reviews helpfully and publicly.",
        "Use questions from reviews to improve product descriptions and FAQs.",
      ] },
      { type: "h2", text: "Blogging that supports a Shopify store" },
      { type: "p", text: "Shopify includes a blog, and used well it can attract shoppers early in their journey. The key is to write content that helps people choose and use products, and to link clearly to the relevant collections." },
      { type: "slides", title: "Shopify blog content that sells", slides: [
        { title: "Buying guides", points: ["How to choose the right size or fabric", "Comparisons between product types", "Budget guides for different needs"] },
        { title: "Care and use", points: ["How to wash, store or maintain products", "Styling or usage ideas", "Common problems and fixes"] },
        { title: "Seasonal", points: ["Eid and wedding season guides", "Summer and winter collections", "Gift guides"] },
      ] },
      { type: "h2", text: "Measuring Shopify SEO properly" },
      { type: "p", text: "Shopify’s own analytics shows sales by channel, and Google Analytics 4 with ecommerce tracking adds detail on which landing pages produce revenue. Combine that with Search Console data on queries and clicks. The question to answer each month is simple: which collections and products are earning organic revenue, and which ones have impressions but few clicks or sales?" },
      { type: "stats", title: "Shopify SEO metrics to track", items: [
        { value: "Revenue", label: "Organic sales by landing page" },
        { value: "CTR", label: "Click-through rate of collection pages in search" },
        { value: "CVR", label: "Conversion rate of organic visitors" },
        { value: "Index", label: "Collections and products indexed" },
      ] },
    ],
    faqs: [
      { q: "How should I structure collections on Shopify for SEO?", a: "Put main collections that match search demand in the main menu, group related sub-collections beneath them, link products from relevant collections and avoid many overlapping promotional collections." },
      { q: "Can a Shopify store rank in other countries?", a: "Yes. Use Shopify Markets with crawlable URLs for each market, correct hreflang, accurate prices in local currency and shipping information adapted for each country." },
      { q: "Do product reviews help Shopify SEO?", a: "Genuine reviews help shoppers decide and add unique content. Display real reviews on product pages, and keep any review structured data matched to them." },
    ],
  },

  /* ------------------------------------------------------------------ 14 ecommerce */
  "ecommerce-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for online stores" },
      { type: "p", text: "Ecommerce keyword research is different from service businesses. You are mapping thousands of possible searches to a structure of categories and products. The aim is to understand which groups of searches deserve their own page and which belong together." },
      { type: "table", caption: "Ecommerce keyword types", head: ["Type", "Example", "Best page"], rows: [
        ["Category", "men’s leather shoes", "Category page"],
        ["Attribute", "black leather loafers", "Filtered landing page if demand is high"],
        ["Brand", "brand name sneakers Pakistan", "Brand page"],
        ["Product", "specific model name", "Product page"],
        ["Question", "how to clean leather shoes", "Guide linked to category"],
        ["Comparison", "loafers vs moccasins", "Guide or comparison page"],
      ] },
      { type: "p", text: "Use your own site search data and Search Console queries alongside keyword tools. Shoppers often use words your merchandising team does not, and Pakistani buyers mix English and Roman Urdu terms for many products." },
      { type: "h2", text: "Category page content that helps shoppers" },
      { type: "p", text: "Category pages carry most of an online store’s ranking potential. Yet many Pakistani stores leave them as bare product grids. A short introduction, helpful filters, buying advice and FAQs make a category page more useful to shoppers and more understandable to Google, without pushing products out of view." },
      { type: "checklist", title: "Category page essentials", items: [
        "A clear H1 that matches how customers search",
        "Two or three sentences of helpful introduction above the grid",
        "Useful filters for size, colour, price and type",
        "Links to related sub-categories",
        "Buying advice or FAQs below the grid",
        "Delivery, COD and returns information",
      ] },
      { type: "h2", text: "Technical issues specific to online stores" },
      { type: "p", text: "Stores face technical issues that brochure sites rarely encounter: pagination across long category lists, products in multiple categories, internal search pages being indexed, and seasonal URLs that disappear. Each needs a deliberate decision." },
      { type: "list", items: [
        "**Pagination:** make paginated pages crawlable with normal links, and keep the first page as the main target for category searches.",
        "**Products in several categories:** use one canonical product URL and link to it from every category.",
        "**Internal search results:** keep them out of the index; they create endless thin pages.",
        "**Seasonal pages:** keep evergreen URLs such as an Eid collection and update them each year rather than creating new ones.",
      ] },
      { type: "h2", text: "Speed, checkout and conversion" },
      { type: "p", text: "SEO brings shoppers to your store, but speed and checkout decide whether they buy. Pakistani shoppers often browse on mid-range phones over mobile data, so heavy pages lose sales. Fast product images, a simple cart, clear delivery charges and cash-on-delivery options all improve conversion, which improves the return on every visitor SEO brings." },
      { type: "bars", title: "Common checkout friction points", items: [
        { label: "Unexpected delivery charges", value: 5, display: "Very common" },
        { label: "Forced account creation", value: 4, display: "Common" },
        { label: "Slow pages on mobile data", value: 4, display: "Common" },
        { label: "No cash on delivery option", value: 3, display: "Frequent" },
        { label: "Unclear return policy", value: 3, display: "Frequent" },
      ], note: "From our experience reviewing Pakistani online stores." },
      { type: "h2", text: "Planning ecommerce SEO around sales seasons" },
      { type: "p", text: "Pakistani ecommerce has strong seasonal peaks: Eid, wedding season, winter, back to school and sale events. Pages for these peaks need to be live and improving well before demand starts. Keep evergreen seasonal URLs, refresh them every year with new products, and link them prominently from the home page and main categories as the season approaches." },
    ],
    faqs: [
      { q: "How do I do keyword research for an online store?", a: "Map category, attribute, brand, product, question and comparison searches to the right page types, using Search Console, your site search data and keyword tools, including Roman Urdu product terms." },
      { q: "Should internal search result pages be indexed?", a: "No. Internal search pages create endless thin URLs. Keep them out of the index and make sure categories cover real search demand instead." },
      { q: "How early should I prepare Eid collection pages?", a: "Several weeks to two months ahead. Keep an evergreen Eid collection URL and refresh it each year, so it keeps its ranking history." },
    ],
  },

  /* ------------------------------------------------------------------ 15 Google Maps */
  "google-maps-seo-expert": {
    blocks: [
      { type: "h2", text: "Proximity and how far you can realistically reach" },
      { type: "p", text: "Distance is one of the three main local ranking factors, and it cannot be changed. A business in F-8 will naturally appear more often for searches made in F-8 than for searches made in Bahria Town. A good Google Maps SEO expert sets realistic expectations about how far your profile can reach, then uses relevance and prominence to extend that reach as much as possible." },
      { type: "list", items: [
        "**Strengthen relevance** with accurate categories, complete services and website pages that match searches.",
        "**Build prominence** with reviews, citations and links from local sources.",
        "**Support with website area pages** for nearby areas where customers genuinely travel to you.",
        "**Use Google Ads** for areas beyond your natural reach if those customers are valuable.",
      ] },
      { type: "h2", text: "Grid tracking explained" },
      { type: "p", text: "Because local rankings depend on the searcher’s location, checking your rank from one phone tells you very little. Grid tracking checks your position for a keyword from many points across your service area, producing a map that shows where you rank well and where you do not. It is the most useful way to see Google Maps progress over time." },
      { type: "table", caption: "Reading a grid report", head: ["Pattern", "What it usually means", "What to do"], rows: [
        ["Strong near you, weak further out", "Normal distance effect", "Build prominence and area content"],
        ["Weak even nearby", "Relevance problem", "Review categories, services and website"],
        ["Strong for one keyword, weak for another", "Missing service relevance", "Add the service to the profile and website"],
        ["Sudden drop everywhere", "Possible suspension or major change", "Check profile status and recent edits"],
      ] },
      { type: "h2", text: "Handling fake listings and spam competitors" },
      { type: "p", text: "In some categories, competitors use keyword-stuffed names, fake addresses or multiple listings for one business. This is frustrating, and it can hold back honest businesses. Google provides ways to report misleading listings, such as suggesting an edit to a business name or reporting a listing that does not exist. A good Maps specialist documents these cases clearly and reports them through the proper channels, rather than copying the tactics." },
      { type: "callout", tone: "note", title: "Stay on the right side", text: "Reporting genuine spam is legitimate. Copying spam tactics to compete puts your own profile at risk. The safest long-term advantage is a complete, active, honest profile with strong reviews." },
      { type: "h2", text: "Google Maps and your website working together" },
      { type: "p", text: "Your Business Profile links to your website, and Google uses your website to understand your business. Pages that match your categories and services, show your address and contact details consistently, and include structured data with your business information all reinforce your Maps relevance. A strong profile with a weak website leaves results on the table." },
      { type: "checklist", title: "Website support for Maps", items: [
        "Name, address and phone shown exactly as on the profile",
        "A page for each main service listed on the profile",
        "LocalBusiness structured data matching the profile",
        "An embedded map and directions on the contact page",
        "Reviews or testimonials displayed where appropriate",
        "Fast mobile pages with click-to-call and WhatsApp",
      ] },
      { type: "h2", text: "Maps SEO for different business types" },
      { type: "slides", title: "Priorities by business type", slides: [
        { title: "Clinics", points: ["Specific medical categories", "Doctor names in reviews and website", "Accurate timings and emergencies"] },
        { title: "Restaurants", points: ["Cuisine categories and menu", "Fresh food photos", "Attributes like family seating"] },
        { title: "Home services", points: ["Service area set correctly", "Reviews mentioning areas", "Fast response on calls and WhatsApp"] },
        { title: "Shops", points: ["Products added to the profile", "Opening hours and holidays", "Exterior photos for recognition"] },
      ] },
    ],
    faqs: [
      { q: "Why does my business show on Maps near my shop but not in other areas?", a: "Distance is a major local ranking factor. Strengthen relevance and prominence, build area pages for nearby areas customers travel from, and consider ads for areas beyond your natural reach." },
      { q: "What is grid rank tracking?", a: "A method that checks your Maps ranking from many points across your service area, showing where you rank well and where you do not, which is more accurate than a single rank check." },
      { q: "What should I do about fake listings in my category?", a: "Report misleading listings through Google’s suggest-an-edit and reporting options with clear evidence. Do not copy spam tactics, which put your own profile at risk." },
    ],
  },

  /* ------------------------------------------------------------------ 16 on-page */
  "on-page-seo-expert": {
    blocks: [
      { type: "h2", text: "Search intent in detail" },
      { type: "p", text: "Search intent is the reason behind a search. Matching it is the foundation of on-page SEO, because Google ranks the type of page that best satisfies what searchers want. Getting the format wrong, for example offering a sales page when people want a guide, can stop a page ranking no matter how well it is optimised otherwise." },
      { type: "table", caption: "Types of search intent", head: ["Intent", "Example", "Page that usually ranks"], rows: [
        ["Informational", "how long does a root canal take", "Guide or FAQ answer"],
        ["Commercial investigation", "best physiotherapy clinic F-10", "Service page with proof, comparisons, reviews"],
        ["Transactional", "book dental appointment Islamabad", "Booking or service page with clear action"],
        ["Navigational", "clinic name timings", "Contact or location page"],
        ["Local", "dentist near me", "Business Profile and location page"],
      ] },
      { type: "p", text: "The quickest way to check intent is to search the keyword yourself and look at what ranks. If the top results are all guides, a service page will struggle. If they are all local businesses, your Business Profile and location page matter more than a blog post." },
      { type: "h2", text: "Writing for people and search engines at the same time" },
      { type: "p", text: "Good on-page copy reads naturally to customers while making the topic clear to search engines. That means using the words customers actually use, answering their questions in a logical order, and avoiding repetition for its own sake. Keyword stuffing makes pages worse for readers and does not help rankings." },
      { type: "compare", title: "Stuffed versus natural copy", left: { label: "Stuffed", items: [
        "Best dentist Islamabad, our dentist Islamabad clinic offers dentist Islamabad services",
        "Long keyword lists at the bottom of the page",
        "Headings repeating the same phrase",
      ] }, right: { label: "Natural", items: [
        "Our family dental clinic in F-10 offers check-ups, fillings, root canals and implants",
        "Related terms woven into helpful explanations",
        "Headings that describe each section clearly",
      ] } },
      { type: "h2", text: "Internal linking strategy" },
      { type: "p", text: "Internal links help Google discover pages, understand how they relate, and judge which pages matter most. They also guide visitors to the next useful step. A deliberate internal linking strategy is one of the most underused on-page tools on Pakistani websites." },
      { type: "checklist", title: "Internal linking rules of thumb", items: [
        "Link from the home page to your most important services",
        "Link each service page to related services and relevant area pages",
        "Link guides and blog posts to the service they relate to",
        "Use descriptive anchor text, not “click here”",
        "Fix links to redirected or deleted pages",
        "Avoid orphan pages with no internal links pointing to them",
      ] },
      { type: "h2", text: "Optimising for featured snippets and AI answers" },
      { type: "p", text: "Featured snippets and AI-generated answers often quote short, clear passages that directly answer a question. Pages that put a concise answer near the top, followed by detail, are more likely to be quoted. Lists, tables and step-by-step explanations are also easy for search and AI systems to extract." },
      { type: "list", items: [
        "Phrase key headings as the question people ask.",
        "Answer in 40 to 60 words directly under the heading.",
        "Follow with detail, examples and exceptions.",
        "Use lists for steps and tables for comparisons.",
        "Keep facts accurate and up to date.",
      ] },
      { type: "h2", text: "Measuring on-page changes" },
      { type: "p", text: "Every on-page change is a small experiment. Record the date, what changed and why, then watch Search Console for that page over the following weeks. Look at impressions, clicks, click-through rate and average position. Over time, this record shows which kinds of changes work best for your site and audience." },
      { type: "stats", title: "What to watch after an on-page change", items: [
        { value: "CTR", label: "Did the new title earn more clicks?" },
        { value: "Position", label: "Did the page move for its main queries?" },
        { value: "Queries", label: "Is it now showing for more related searches?" },
        { value: "Leads", label: "Did enquiries from the page change?" },
      ] },
    ],
    faqs: [
      { q: "What is search intent in SEO?", a: "The reason behind a search: informational, commercial investigation, transactional, navigational or local. Pages rank best when their format matches the intent shown by the current top results." },
      { q: "How many times should a keyword appear on a page?", a: "There is no ideal number. Use the main topic naturally in the title, heading and opening, and cover related terms through helpful explanations. Repetition for its own sake does not help." },
      { q: "How do I get a featured snippet?", a: "Phrase a heading as the question, answer it clearly in 40 to 60 words beneath, then add detail, lists or tables. Accurate, well-structured pages are more likely to be quoted." },
    ],
  },
};
