import type { Deep } from "./deep";

export const DEEP_B: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 5 freelance */
  "freelance-seo-expert-islamabad": {
    blocks: [
      { type: "h2", text: "Where to find good freelance SEO experts in the twin cities" },
      { type: "p", text: "Islamabad and Rawalpindi have one of the deepest pools of freelance digital talent in Pakistan, helped by universities, IT parks and years of remote work for international clients. Finding someone is easy. Finding the right person takes a little more method, because the most visible freelancers are not always the most capable ones." },
      { type: "table", caption: "Sources of freelance SEO talent", head: ["Source", "Strengths", "Watch out for"], rows: [
        ["Referrals from other business owners", "Proven track record, honest feedback", "Limited pool; may be fully booked"],
        ["LinkedIn", "Visible work history and recommendations", "Polished profiles without evidence"],
        ["International freelance platforms", "Reviews, escrow-style payments", "Reviews that reflect speed rather than SEO results"],
        ["Local Facebook and WhatsApp groups", "Quick responses, local knowledge", "Very mixed quality; check carefully"],
        ["Graduates of reputable training programmes", "Current skills, motivated", "Little real-world experience"],
      ] },
      { type: "p", text: "Whichever source you use, the same vetting applies: look at live work, set a small paid task and check how the person communicates. A freelancer with two or three solid, verifiable projects is usually a better bet than one with fifty five-star reviews for unrelated quick jobs." },
      { type: "h2", text: "Writing a scope of work a freelancer cannot misunderstand" },
      { type: "p", text: "Most disputes with freelancers come from scope that was clear in the client’s head but not on paper. The fix is a short scope of work that lists deliverables in concrete terms. Compare a vague scope with a clear one for the same job." },
      { type: "compare", title: "Vague scope versus clear scope", left: { label: "Vague", items: [
        "Do SEO for our website",
        "Improve our Google ranking",
        "Fix technical issues",
        "Make our Google profile better",
      ] }, right: { label: "Clear", items: [
        "Rewrite titles and descriptions for these 12 pages",
        "Fix all indexing errors listed in Search Console",
        "Compress and resize images on the five service pages",
        "Complete the Business Profile: categories, services, 20 photos, hours",
      ] } },
      { type: "p", text: "A clear scope also makes it obvious when extra work is being requested. If you want something outside the scope during the project, agree it separately with its own price and deadline. This protects both sides and keeps the relationship friendly." },
      { type: "h2", text: "Quality-checking a freelancer’s SEO work yourself" },
      { type: "p", text: "You do not need to be an SEO expert to check most freelance work. A few simple checks catch the majority of problems before you make the final payment." },
      { type: "checklist", title: "Simple checks before final payment", items: [
        "Open each changed page and confirm the new title appears in the browser tab",
        "Search site:yourdomain.pk in Google a week later to see updated titles appear",
        "Run PageSpeed Insights on pages where speed work was promised and compare with the earlier score",
        "Check Search Console for new errors since the work started",
        "Open your Business Profile and confirm the categories, services and photos were added",
        "Ask for the list of every link built, and open a sample yourself",
      ] },
      { type: "callout", tone: "tip", title: "Keep a before snapshot", text: "Before any freelancer starts, take screenshots of Search Console, PageSpeed results and your Business Profile. Without a baseline, it is hard to judge what changed." },
      { type: "h2", text: "Turning a good freelancer into a long-term partner" },
      { type: "p", text: "When you find a freelancer whose work is reliable, it is worth keeping them. Continuity matters in SEO: someone who already knows your site, your customers and your past decisions works faster and makes fewer mistakes. Pay on time, give clear feedback, and offer a small monthly retainer for ongoing tasks such as Business Profile updates, reporting and fixing new issues. Many of the best long-term SEO relationships in Islamabad began as a single small freelance project." },
      { type: "p", text: "As the relationship grows, consider adding light oversight: a quarterly review by an experienced consultant who checks direction and quality. It costs little, keeps standards high and gives the freelancer useful feedback to grow." },
      { type: "h2", text: "Fair rates for freelance SEO work" },
      { type: "p", text: "Freelance rates vary widely in Pakistan, depending on experience, whether the freelancer usually works for overseas clients, and the complexity of the task. Rather than looking for the lowest price, compare what each freelancer will deliver and how they will prove it. A slightly higher rate for someone with verifiable results and clear communication almost always works out cheaper than paying twice to fix poor work." },
      { type: "bars", title: "What tends to drive a freelancer’s rate", items: [
        { label: "Verified results and portfolio", value: 5, display: "Strongest" },
        { label: "Overseas client experience", value: 4, display: "Strong" },
        { label: "Technical depth", value: 4, display: "Strong" },
        { label: "Years active", value: 2, display: "Moderate" },
      ], note: "General patterns, not a formula; always compare scope and evidence." },
    ],
    faqs: [
      { q: "Where can I find a reliable freelance SEO expert in Islamabad?", a: "Referrals from other business owners are the most reliable source, followed by LinkedIn profiles with verifiable work. Freelance platforms and local groups can work too, but vet candidates carefully with a small paid task." },
      { q: "How do I check a freelancer’s SEO work without being an expert?", a: "Confirm changed titles in the browser and in Google, compare PageSpeed results, check Search Console for new errors, review your Business Profile and open a sample of any links they built." },
    ],
  },

  /* ------------------------------------------------------------------ 6 small business */
  "seo-expert-for-small-business-islamabad": {
    blocks: [
      { type: "h2", text: "What a small business can do itself, and what to outsource" },
      { type: "p", text: "Small business owners in Islamabad and Rawalpindi often ask whether they can do SEO themselves. The honest answer is: partly. Some of the most valuable work, such as collecting reviews, taking photos and answering customer questions, is best done by the business itself because nobody else knows the customers as well. Other tasks, such as technical fixes and strategy, benefit from experience." },
      { type: "table", caption: "Do it yourself or outsource?", head: ["Task", "Who should do it", "Why"], rows: [
        ["Asking customers for reviews", "You", "Customers respond to the business, not an agency"],
        ["Taking photos of premises and work", "You", "Real photos beat stock images"],
        ["Answering customer questions in writing", "You, with help editing", "You know the real questions and answers"],
        ["Business Profile setup", "You or an expert", "Easy to start; categories benefit from experience"],
        ["Technical fixes and speed", "Expert or developer", "Mistakes can hide your site from Google"],
        ["Strategy and keyword planning", "Expert", "Experience avoids wasted effort"],
      ] },
      { type: "p", text: "A practical split is to handle reviews, photos and customer questions in-house, and pay an expert for setup, technical work and a clear plan. That keeps costs manageable while making sure the work that needs experience is done properly." },
      { type: "h2", text: "A weekly 30-minute SEO routine for owners" },
      { type: "p", text: "Consistency beats intensity for small businesses. Thirty minutes a week, done every week, will do more for your local visibility than a burst of effort once a year. Here is a simple routine any owner or staff member can follow." },
      { type: "slides", title: "The 30-minute weekly routine", slides: [
        { title: "10 minutes: reviews", points: ["Send review requests to this week’s happy customers", "Reply to every new review", "Note any complaints to fix"] },
        { title: "10 minutes: Business Profile", points: ["Upload two or three new photos", "Publish a short update or offer", "Check hours and holiday changes"] },
        { title: "10 minutes: questions and data", points: ["Write down questions customers asked this week", "Check calls and messages from your profile", "Pass new questions to whoever updates your website"] },
      ] },
      { type: "h2", text: "Turning customer questions into content" },
      { type: "p", text: "Every question a customer asks on the phone or WhatsApp is a clue to what people search for. A salon gets asked how long keratin treatment lasts. A tutor gets asked whether online O level classes are as effective as in person. A plumber gets asked how much a geyser installation costs. Each of these questions, answered clearly on your website, can attract new customers searching the same thing." },
      { type: "list", items: [
        "Keep a running list of questions in a notebook or shared document.",
        "Group similar questions together each month.",
        "Answer the most common ones on the relevant service page as an FAQ.",
        "For bigger questions, write a short dedicated page.",
        "Link those pages to your contact and WhatsApp buttons.",
      ] },
      { type: "h2", text: "An illustrative example: a home tutoring business" },
      { type: "p", text: "Consider an illustrative example of a home tutoring service covering F-10, F-11, G-11 and E-11 in Islamabad. Its website had one page listing every subject and a Business Profile with three reviews. Over three months, a small business SEO approach might focus on a few simple steps." },
      { type: "process", title: "Three-month plan for a tutoring business", steps: [
        { title: "Month 1", text: "Business Profile completed; review requests to every parent" },
        { title: "Month 2", text: "Separate pages for O level, A level and primary tutoring" },
        { title: "Month 3", text: "Sector pages for the four areas served; FAQ on fees" },
      ] },
      { type: "p", text: "Nothing here is complicated, and none of it requires a large budget. What makes it work is focus: the business stops trying to rank for everything and concentrates on the services and sectors where its real customers are." },
      { type: "h2", text: "Budgeting SEO alongside other marketing" },
      { type: "p", text: "Most small businesses also spend on Facebook and Instagram posts, printed flyers or occasional ads. SEO should not replace all of these overnight. A sensible approach is to fund local SEO steadily for at least three months while keeping what already works, then shift budget towards whichever channel produces the cheapest enquiries. Tracking calls and WhatsApp messages by source makes that decision easy rather than a guess." },
      { type: "callout", tone: "note", title: "Measure every channel the same way", text: "Ask every new customer how they found you, and record the answer. Over a few months, this simple habit shows which marketing actually brings business." },
    ],
    faqs: [
      { q: "Can I do SEO for my small business myself?", a: "Partly. Reviews, photos, Business Profile updates and answering customer questions are best done by you. Technical fixes and strategy usually benefit from an experienced expert." },
      { q: "How much time does small business SEO take each week?", a: "A consistent 30 minutes a week on reviews, Business Profile updates and noting customer questions makes a real difference, alongside any work done by your SEO expert." },
    ],
  },

  /* ------------------------------------------------------------------ 7 price */
  "seo-expert-price-islamabad": {
    blocks: [
      { type: "h2", text: "Three illustrative budget scenarios" },
      { type: "p", text: "Prices make more sense with examples. The scenarios below are illustrative, not quotes, and show how scope changes the budget for different kinds of Islamabad businesses." },
      { type: "table", caption: "Illustrative budget scenarios", head: ["Business", "Scope", "Indicative monthly budget"], rows: [
        ["Single-location salon in F-7", "Business Profile, reviews, five service pages, basic reporting", "PKR 30,000 – 50,000"],
        ["Dental clinic with two branches", "Two profiles, procedure pages, doctor profiles, local links, enquiry tracking", "PKR 70,000 – 120,000"],
        ["Property developer with several projects", "Project pages, overseas buyer content, technical SEO, links, detailed reporting", "PKR 150,000 – 300,000+"],
      ] },
      { type: "p", text: "Notice what drives the difference: number of locations, number of services or projects, the competitiveness of the category, and how much content needs to be written. The salon does not need the same investment as the developer, and should not pay for it." },
      { type: "h2", text: "Hidden costs to ask about" },
      { type: "p", text: "Headline monthly fees sometimes leave out costs that appear later. Ask about each of these before you sign, so you can compare quotes on the same basis." },
      { type: "checklist", title: "Costs that are often excluded", items: [
        "Content writing beyond a small number of pages",
        "Developer time for technical fixes",
        "Paid tools the provider wants you to subscribe to",
        "Photography or video for your Business Profile",
        "Directory listing fees for paid directories",
        "Google Ads spend, if paid search is part of the plan",
        "Website hosting upgrades needed for speed",
      ] },
      { type: "callout", tone: "warn", title: "Ad spend is not the agency fee", text: "If a proposal includes Google Ads, make sure the media budget paid to Google is shown separately from the management fee. Mixing them hides how much you are really paying for management." },
      { type: "h2", text: "How to calculate return on SEO spend" },
      { type: "p", text: "SEO is an investment, so judge it like one. The calculation does not need to be complicated. Estimate the profit from a typical new customer, count the new customers that came from organic search in a period, and compare the total profit with what you spent." },
      { type: "process", title: "A simple SEO return calculation", steps: [
        { title: "Customers from search", text: "Tracked enquiries that became sales" },
        { title: "× Profit per customer", text: "Include repeat business over a year" },
        { title: "= Gross return", text: "Profit attributable to SEO" },
        { title: "− SEO cost", text: "Fees, content and tools" },
      ] },
      { type: "p", text: "Remember that SEO returns build over time. The first few months often cost more than they return, because pages and authority take time to establish. Pages that rank then keep producing enquiries for months or years with relatively little extra cost, which is why the return in year two is usually much better than in year one." },
      { type: "h2", text: "Negotiating a fair SEO fee" },
      { type: "p", text: "Negotiation in SEO should be about scope, not just price. Squeezing the fee down without changing the scope usually means the provider quietly does less. A better conversation is about priorities: which work matters most, what can wait, and what you can handle in-house." },
      { type: "list", items: [
        "**Reduce scope, not quality.** Start with fewer services or areas and expand once they rank.",
        "**Take on tasks yourself.** Reviews, photos and answering questions can lower the fee.",
        "**Agree a review point.** A lower starting fee with a planned increase if results justify it.",
        "**Ask about payment terms.** Some providers offer a small discount for quarterly payment, but keep the right to stop monthly.",
      ] },
      { type: "h2", text: "When SEO is not worth the money" },
      { type: "p", text: "SEO is not right for every business at every moment. If very few people search for what you sell, if your margins are too thin to justify a few months of investment, or if your website and operations cannot handle more enquiries, the money may be better spent elsewhere first. A trustworthy SEO expert will tell you this rather than take the fee. That honesty is itself one of the best indicators that a provider’s price is fair." },
    ],
    faqs: [
      { q: "What costs are not included in a typical SEO fee?", a: "Often extra content writing, developer time, paid tools, photography, paid directory listings, hosting upgrades and any Google Ads spend. Ask each provider to list exclusions in writing." },
      { q: "How do I measure the return on SEO spending?", a: "Count customers who came from organic search, multiply by the profit per customer including repeat business, and compare with total SEO cost. Expect returns to improve after the first few months." },
    ],
  },

  /* ------------------------------------------------------------------ 8 best Pakistan */
  "best-seo-expert-in-pakistan": {
    blocks: [
      { type: "h2", text: "How SEO in Pakistan differs from SEO elsewhere" },
      { type: "p", text: "Much SEO advice online is written for the United States or Europe. Some of it applies everywhere, but Pakistani search has its own characteristics, and the best SEO experts in Pakistan understand them deeply." },
      { type: "stats", title: "Features of Pakistani search", items: [
        { value: "Mobile", label: "Most searches happen on phones, often on mobile data" },
        { value: "Bilingual", label: "English mixed with Roman Urdu, sometimes Urdu script" },
        { value: "WhatsApp", label: "The preferred way to contact a business" },
        { value: "City-level", label: "Competition and behaviour differ sharply by city" },
      ] },
      { type: "p", text: "These features change practical decisions. Pages must be light enough to load well on mid-range phones. Keyword research must include Roman Urdu phrasing that international tools underreport. Every page needs an easy WhatsApp contact option. And a strategy that works in Karachi may need to be rebuilt for Quetta or Multan. An expert who has only worked on international sites may miss all of this." },
      { type: "h2", text: "Pakistani SEO specialisms" },
      { type: "p", text: "Within Pakistan, SEO experts tend to specialise. Knowing the main specialisms helps you look in the right place." },
      { type: "table", caption: "Common SEO specialisms in Pakistan", head: ["Specialism", "Typical clients", "Key skills"], rows: [
        ["Local SEO", "Clinics, salons, restaurants, schools, services", "Business Profile, reviews, area pages"],
        ["Ecommerce SEO", "Online stores competing with marketplaces", "Category architecture, product data, technical SEO"],
        ["Export and international SEO", "Manufacturers and exporters", "International targeting, trust signals, product content"],
        ["SaaS and software SEO", "Software houses selling abroad", "Use-case content, comparisons, technical SEO"],
        ["Real estate SEO", "Developers and agencies", "Project pages, overseas buyers, lead tracking"],
        ["Healthcare SEO", "Hospitals and clinics", "E-E-A-T, credentials, accurate medical content"],
      ] },
      { type: "h2", text: "Running a fair comparison between top experts" },
      { type: "p", text: "Once you have a shortlist of three, run them through the same process so the comparison is fair. Give each the same brief and access, ask for the same deliverable, and judge with the same criteria. The goal is to remove the influence of presentation skills and focus on substance." },
      { type: "checklist", title: "A fair comparison process", items: [
        "Send the same written brief to each expert",
        "Ask each for a short audit with their top five recommendations",
        "Give the same deadline and the same data access",
        "Score audits on specificity, evidence and prioritisation",
        "Check one reference per expert with the same questions",
        "Compare proposals on scope, reporting and terms before price",
      ] },
      { type: "h2", text: "Questions that reveal integrity" },
      { type: "p", text: "Skill is only half of what makes an SEO expert the best choice. Integrity is the other half, because SEO involves trust: access to your website, your accounts and your reputation. A few questions reveal a great deal." },
      { type: "list", items: [
        "**“Have you ever turned down a client?”** Good experts have, usually because SEO was not the right fit.",
        "**“What happens if rankings drop after an update?”** Listen for calm diagnosis rather than blame or panic.",
        "**“Do you ever buy links?”** The answer should be clear, and if any sponsored placements are used, they should be disclosed properly.",
        "**“Who owns the work if we part ways?”** You should own all content, accounts and data.",
      ] },
      { type: "callout", tone: "tip", title: "Trust what they decline", text: "An expert who explains what they will not do, such as fake reviews or paid link networks, is often more trustworthy than one who promises to do everything." },
      { type: "h2", text: "Building a long-term relationship with your SEO expert" },
      { type: "p", text: "The best results in Pakistani SEO usually come from long relationships, not short projects. An expert who has worked on your site for two years understands your customers, your seasonality and your history, and can make faster, better decisions. Choose someone you can see yourself working with for several years, and invest in the relationship with regular reviews, honest feedback and clear priorities." },
    ],
    faqs: [
      { q: "How is SEO in Pakistan different from international SEO?", a: "Pakistani search is mobile-first, mixes English and Roman Urdu, favours WhatsApp contact and varies sharply by city. Experts need local knowledge alongside general SEO skills." },
      { q: "How do I compare SEO experts fairly?", a: "Give each the same brief, data access and deadline, ask for a short audit with their top recommendations, score them on the same criteria and check one reference each." },
    ],
  },

  /* ------------------------------------------------------------------ 9 Rawalpindi */
  "seo-expert-rawalpindi-hiring-guide": {
    blocks: [
      { type: "h2", text: "Industries that do well with SEO in Rawalpindi" },
      { type: "p", text: "Rawalpindi’s economy is broad: wholesale and retail markets, healthcare, education, construction and property, automotive services and a large population of families who need everyday services. Some categories respond to SEO particularly quickly because competition online is still light compared with the volume of real demand." },
      { type: "table", caption: "SEO opportunity by industry in Rawalpindi", head: ["Industry", "Why SEO works", "Main focus"], rows: [
        ["Clinics and diagnostic labs", "Patients search for nearby, trusted care", "Business Profile, test and procedure pages"],
        ["Schools and academies", "Parents compare across areas", "Campus pages, fees, admission dates"],
        ["Home services", "Urgent, local, mobile searches", "Map pack, reviews, WhatsApp contact"],
        ["Automotive workshops and dealers", "Specific searches by car model and service", "Service pages, reviews, prices"],
        ["Wholesale and retail", "Buyers search for specific products and markets", "Product categories, location and timings"],
        ["Property and construction", "Bahria Town and DHA demand", "Project pages, overseas owner content"],
      ] },
      { type: "h2", text: "Understanding Rawalpindi customers" },
      { type: "p", text: "Rawalpindi customers tend to be practical. They want to know the price, the location, the timings and whether the business is trustworthy, and they often want to ask a quick question on WhatsApp before committing. Many are comparing several options at once. Pages that answer these practical questions upfront, with clear prices or price ranges, directions from known landmarks and an obvious WhatsApp button, consistently convert better than polished pages that hide the essentials." },
      { type: "list", items: [
        "**Landmarks matter.** Directions such as “near Committee Chowk” or “opposite the main gate of a known hospital” help customers more than a postcode.",
        "**Prices build trust.** Even a range helps customers decide whether to contact you.",
        "**Timings must be accurate,** including Friday breaks and holiday changes.",
        "**Replies must be fast.** A message answered in five minutes often wins against a competitor who replies tomorrow.",
      ] },
      { type: "h2", text: "Optimising for Roman Urdu searches" },
      { type: "p", text: "Roman Urdu searches are common in Rawalpindi, especially for everyday services. Phrases like “sasta mobile repair Saddar” or “acha dentist Satellite Town” rarely appear in keyword tools, but they show up in Search Console data. The right approach is not to create separate Roman Urdu pages, but to weave natural Roman Urdu phrases into English pages where customers actually use them, for example in FAQs, headings or short descriptions." },
      { type: "callout", tone: "tip", title: "Use your own data", text: "Open Search Console, go to the Performance report and filter queries for words like “acha”, “sasta”, “kahan” or “kitna”. These reveal exactly how your customers phrase searches." },
      { type: "h2", text: "Choosing between a Rawalpindi-based and an Islamabad-based expert" },
      { type: "p", text: "Many SEO providers serving Rawalpindi are based in Islamabad, and vice versa. Location matters less than knowledge. What you need is someone who understands Rawalpindi’s areas, its customers and its competitors. Ask any candidate to describe how they would treat Saddar differently from Bahria Town. If the answer is specific and sensible, their office address hardly matters." },
      { type: "h2", text: "Tracking Rawalpindi results properly" },
      { type: "p", text: "Map rankings in Rawalpindi can look very different depending on where the search happens. A business in Satellite Town may rank first for searches nearby and not appear at all from Bahria Town. Good reporting reflects this, using rank tracking across several points in your service area rather than a single position from one location." },
      { type: "stats", title: "What a good Rawalpindi report shows", items: [
        { value: "Grid", label: "Map rankings across several areas" },
        { value: "Calls", label: "Phone calls from the Business Profile" },
        { value: "WhatsApp", label: "Clicks on WhatsApp buttons" },
        { value: "Areas", label: "Which areas enquiries came from" },
      ] },
      { type: "p", text: "Combined with a simple question to every new customer about how they found you, this gives a clear picture of whether SEO is working and which areas to expand into next." },
    ],
    faqs: [
      { q: "Which industries benefit most from SEO in Rawalpindi?", a: "Clinics and labs, schools and academies, home services, automotive workshops, wholesale and retail, and property and construction businesses in Bahria Town and DHA often see strong results." },
      { q: "Should I create separate Roman Urdu pages?", a: "Usually not. Weave natural Roman Urdu phrases into English pages, especially in FAQs and descriptions, based on the queries you see in Search Console." },
    ],
  },

  /* ------------------------------------------------------------------ 10 local SEO */
  "local-seo-expert-islamabad": {
    blocks: [
      { type: "h2", text: "Choosing the right categories in detail" },
      { type: "p", text: "Category selection is one of the most influential local SEO decisions, and one of the most often rushed. Your primary category tells Google what your business fundamentally is. Secondary categories add relevance for other services you genuinely provide. Choosing badly limits which searches you can appear for, no matter how many reviews you collect." },
      { type: "table", caption: "Category choices: weaker and stronger examples", head: ["Business", "Weaker primary category", "Stronger primary category"], rows: [
        ["Teeth whitening and implants clinic", "Health", "Dentist or Cosmetic dentist"],
        ["Bridal makeup studio", "Beauty", "Beauty salon or Make-up artist"],
        ["Corporate law practice", "Consultant", "Law firm or Corporate lawyer"],
        ["O level coaching", "School", "Tutoring service or Coaching centre"],
        ["AC installation and repair", "Contractor", "Air conditioning repair service"],
      ] },
      { type: "p", text: "The available categories change over time, so check the current list in your Business Profile and look at which categories the businesses ranking above you use. Pick the most specific accurate option, and add secondary categories only where you really offer that service." },
      { type: "h2", text: "Photos, posts and products that help" },
      { type: "p", text: "A complete, active profile signals to customers that the business is real and well run. Photos are the most powerful element: customers look at them before deciding to call or visit. Posts and products add useful detail and keep the profile fresh." },
      { type: "slides", title: "Keeping your profile active", slides: [
        { title: "Photos", points: ["Exterior so customers recognise the building", "Interior, team and work examples", "New photos every week or two"] },
        { title: "Posts", points: ["Offers, events and seasonal updates", "Short, specific and with a clear action", "Regular rather than occasional"] },
        { title: "Products and services", points: ["Each service with a short description", "Price or price range where possible", "Link to the relevant page on your site"] },
      ] },
      { type: "h2", text: "Replying to reviews well" },
      { type: "p", text: "Replies are read by every future customer who looks at your profile. A thoughtful reply to a complaint can win more trust than a dozen five-star reviews. Keep replies personal, short and professional, and never argue in public." },
      { type: "compare", title: "Review replies that hurt and help", left: { label: "Hurts", items: [
        "Copy-pasted thank-you messages",
        "Arguing with or blaming the customer",
        "Sharing private details about the customer",
        "Ignoring complaints entirely",
      ] }, right: { label: "Helps", items: [
        "Thanking reviewers by name and mentioning the service",
        "Acknowledging the problem calmly",
        "Offering to resolve it privately by phone or WhatsApp",
        "Explaining any changes you made as a result",
      ] } },
      { type: "h2", text: "Citations: which Pakistani directories matter" },
      { type: "p", text: "Citations matter most when they are consistent and relevant, not when there are many of them. Focus first on the platforms customers actually use and the directories most relevant to your industry, then on general business directories. Make sure your name, address and phone number are written exactly the same everywhere." },
      { type: "checklist", title: "Citation priorities", items: [
        "Google Business Profile and Apple Business Connect",
        "Bing Places for Business",
        "Facebook and Instagram business profiles with accurate details",
        "Your industry association or council directory",
        "Chamber of commerce member listings",
        "Well-known Pakistani business directories relevant to your sector",
      ] },
      { type: "h2", text: "Measuring local SEO success" },
      { type: "p", text: "Your Business Profile’s performance data shows how many people found you through search and Maps, and how many called, asked for directions or visited your website. Combine that with rank tracking across a grid of points in your service area and a simple record of how new customers found you. Together, these show not only whether your visibility improved, but whether it produced business." },
      { type: "bars", title: "Local SEO metrics, from most to least important", items: [
        { label: "Calls and WhatsApp enquiries", value: 5, display: "Primary" },
        { label: "Direction requests", value: 4, display: "Primary" },
        { label: "Website clicks from the profile", value: 3, display: "Supporting" },
        { label: "Grid ranking positions", value: 3, display: "Supporting" },
        { label: "Profile views", value: 2, display: "Context" },
      ], note: "Our recommended order for judging local SEO." },
    ],
    faqs: [
      { q: "How do I choose the right Google Business Profile category?", a: "Choose the most specific category that accurately describes your core business, check which categories top-ranking competitors use, and add secondary categories only for services you really provide." },
      { q: "Which directories should Islamabad businesses be listed in?", a: "Start with Google Business Profile, Apple Business Connect, Bing Places and your social profiles, then industry association and chamber directories, then relevant Pakistani business directories, with identical details everywhere." },
    ],
  },
};
