import type { Block } from "@/lib/blog";

/* Meta descriptions (155 characters or fewer) used in search results.
   The longer `description` on each post is shown on the page itself. */
export const META: Record<string, string> = {
  "best-seo-expert-in-islamabad": "How to find the best SEO expert in Islamabad: what to verify, questions to ask, red flags to avoid and how to compare SEO proposals fairly.",
  "hire-seo-expert-islamabad": "A step-by-step process to hire an SEO expert in Islamabad: the brief, the audit, contract clauses that protect you and the first 30 days.",
  "seo-specialist-islamabad": "What an SEO specialist in Islamabad does: core skills, services, tools and the business benefits you should expect from the work.",
  "seo-consultant-islamabad": "When to hire an SEO consultant in Islamabad instead of an agency, how consulting works and how to judge whether the advice is good.",
  "freelance-seo-expert-islamabad": "Hiring a freelance SEO expert in Islamabad: when a freelancer fits, how to vet them, milestone payments and the risks to manage.",
  "seo-expert-for-small-business-islamabad": "SEO for small businesses in Islamabad on a limited budget: what to prioritise, what to skip and a practical 90-day plan.",
  "seo-expert-price-islamabad": "Indicative 2026 SEO prices in Islamabad for freelancers, agencies and consultants, what drives cost and how to judge a quote.",
  "best-seo-expert-in-pakistan": "Who is the best SEO expert in Pakistan for your business? The criteria that matter, how to verify claims and the signals that mislead.",
  "seo-expert-rawalpindi-hiring-guide": "Hiring an SEO expert in Rawalpindi: how Pindi search differs from Islamabad, which areas to target and how to evaluate providers.",
  "local-seo-expert-islamabad": "How a local SEO expert improves Google Maps rankings in Islamabad: Business Profile, reviews, citations and sector pages.",
  "technical-seo-expert": "Signs you need a technical SEO expert, what a technical audit covers, Core Web Vitals explained and which fixes matter first.",
  "wordpress-seo-expert": "What a WordPress SEO expert fixes: plugin bloat, Rank Math or Yoast setup, archives, speed and schema, with a practical checklist.",
  "shopify-seo-expert": "How a Shopify SEO expert grows store traffic: collection pages, product content, duplicate URLs, apps, speed and Pakistani buyers.",
  "ecommerce-seo-expert": "How an ecommerce SEO expert increases sales: category architecture, faceted navigation, product data and competing with marketplaces.",
  "google-maps-seo-expert": "How to choose a Google Maps SEO expert: services to expect, questions to ask, tactics that cause suspensions and how to measure results.",
  "on-page-seo-expert": "What an on-page SEO expert delivers: keyword mapping, titles, headings, content, internal links, images and schema, page by page.",
  "off-page-seo-expert": "How an off-page SEO expert builds authority safely: earned links, PR, citations, reviews and mentions that work in Pakistan.",
  "seo-audit-expert": "How an SEO audit expert finds what holds a site back, what a full audit covers and how to turn findings into a prioritised fix list.",
  "link-building-expert": "How to evaluate a link building expert: judging link quality, reading link reports, spotting paid networks and methods that last.",
  "real-estate-seo-expert": "Real estate SEO in Islamabad: society and project pages, overseas Pakistani buyers, portal competition and lead tracking.",
  "healthcare-seo-expert": "How healthcare SEO attracts patients in Pakistan: E-E-A-T, doctor profiles, procedure pages, local search and easy booking.",
  "dental-seo-expert": "How dentists get more appointments with SEO: map pack visibility, procedure pages with prices, reviews and booking tracking.",
  "lawyer-seo-expert": "How law firms in Pakistan improve search visibility responsibly: practice area pages, lawyer profiles, guides and local search.",
  "restaurant-seo-expert": "How restaurants grow local search traffic: Google Business Profile, text menus, photos, reviews, delivery apps and direct orders.",
  "hotel-seo-expert": "How hotels increase direct bookings with SEO: brand search, Google hotel listings, room pages, local guides and reviews.",
  "travel-seo-expert": "How Pakistani travel websites rank higher: seasonal calendars, Hajj and Umrah, northern tours, itinerary pages and trust signals.",
  "education-seo-expert": "How schools in Pakistan attract students with SEO: admission timing, fee pages, campus and programme pages and parent trust.",
  "saas-seo-expert": "How a SaaS SEO expert grows trials and demos: use-case, integration and comparison pages, technical SEO and pipeline reporting.",
  "international-seo-expert": "International SEO for Pakistani exporters and firms: market choice, site structure, hreflang, localisation and global trust signals.",
  "seo-expert-near-me": "Searching “SEO expert near me”? How to judge local results, when proximity matters and how to vet the specialists you find.",
  "seo-expert-blue-area-islamabad": "SEO for Blue Area, Islamabad businesses: B2B buyers, credibility content, office-tower Business Profiles and lead tracking.",
  "seo-expert-dha-islamabad": "Hiring an SEO expert in DHA Islamabad: phase-level search, premium buyers, overseas owners and what to ask providers.",
  "seo-expert-bahria-town": "SEO for Bahria Town Rawalpindi businesses: phase-level search, core local services and indicative 2026 pricing.",
  "seo-expert-vs-digital-marketing-expert": "SEO expert vs digital marketing expert: skills, timelines and costs compared, and how to decide which to hire first.",
  "seo-expert-vs-seo-freelancer": "SEO expert or SEO freelancer? How they differ in experience, accountability, cost and risk, and which suits your project.",
  "how-to-become-seo-expert-pakistan": "A practical roadmap to become an SEO expert in Pakistan: skills in order, free tools, portfolio building and realistic timelines.",
  "seo-expert-salary-pakistan": "Indicative 2026 SEO salaries in Pakistan by level, remote and freelance earnings, and the skills that push pay higher.",
  "ai-seo-expert": "How AI is changing SEO: AI Overviews, AI-assisted workflows, citable content and the risks of scaled AI content.",
  "seo-for-chatgpt-and-google-ai-search": "A practical GEO guide: how ChatGPT, Gemini, Perplexity and Google AI Overviews choose sources and how to get cited.",
};

/* Extra sections inserted before each post's closing paragraph. */
export const EXTRAS: Record<string, Block[]> = {
  "hire-seo-expert-islamabad": [
    { type: "h2", text: "Common hiring mistakes Islamabad businesses make" },
    { type: "list", items: [
      "**Hiring the cheapest quote without comparing scope.** A low fee that excludes content and links means you pay for them later or go without.",
      "**Letting the provider create accounts in their name.** If your Google Business Profile or Analytics belongs to the agency, leaving becomes painful.",
      "**Judging after two weeks.** SEO needs time; judge at 90 days against the plan, not after the first report.",
      "**Skipping the reference call.** Five minutes with a current client tells you more than any proposal.",
      "**Not naming an internal owner.** Someone in your business must approve content and answer questions, or work stalls.",
    ] },
    { type: "p", text: "Most of these mistakes come from treating SEO as a purchase rather than a working relationship. The businesses that get the best results in Islamabad usually treat their SEO expert like a part-time team member: they share sales feedback, answer questions quickly and review results together every month." },
  ],
  "seo-specialist-islamabad": [
    { type: "h2", text: "An example: what a specialist changes in the first quarter" },
    { type: "p", text: "Consider an illustrative example: a physiotherapy clinic in G-11 with a five-page website, a half-complete Business Profile and almost no enquiries from search. A capable SEO specialist would not start by writing blog posts." },
    { type: "list", ordered: true, items: [
      "Fix the basics: the site was not mobile-friendly and the contact number was an image, so it could not be tapped.",
      "Complete the Business Profile with the right category, every treatment as a service, real photos and correct hours.",
      "Replace one generic services page with separate pages for back pain, sports injuries and post-surgery rehabilitation, each with a price range.",
      "Start a review routine at reception and add call and WhatsApp tracking.",
      "Create pages for G-10 and G-9, where many patients travel from.",
    ] },
    { type: "p", text: "None of these steps is glamorous, but together they address relevance, trust and conversion. That order of work, foundations first, is what separates a specialist from someone who simply produces content." },
  ],
  "seo-consultant-islamabad": [
    { type: "h2", text: "Mistakes that waste consulting budgets" },
    { type: "list", items: [
      "**No one to implement.** Advice sitting in a document helps no one. Line up a developer or writer before the engagement.",
      "**Too many priorities.** A list of forty recommendations is a sign of poor consulting. Ask for the top five.",
      "**Changing direction every month.** Give each priority enough time to show results before switching.",
      "**Hiding data.** Consultants can only advise on what they can see. Share Search Console, Analytics and sales feedback.",
    ] },
    { type: "p", text: "The best consulting relationships in Islamabad we have seen share one habit: a short monthly meeting where the business reports what was implemented, the consultant reviews the effect, and both agree the next two or three actions. It keeps the work focused and the costs predictable." },
  ],
  "freelance-seo-expert-islamabad": [
    { type: "h2", text: "A simple brief template for freelancers" },
    { type: "p", text: "Freelancers do their best work with a clear brief. Copy this structure into a message or document before you post a project or approach someone directly." },
    { type: "table", caption: "Freelance SEO brief template", head: ["Section", "What to write"], rows: [
      ["Goal", "One sentence, for example “Fix technical issues so all service pages are indexed”"],
      ["Scope", "Exactly what is included and what is not"],
      ["Access", "Which tools they will get user access to"],
      ["Deliverables", "Files, changes or reports you expect"],
      ["Timeline", "Start date, midpoint check and deadline"],
      ["Payment", "Amount per milestone and how it is paid"],
      ["Communication", "Update day, preferred channel and response time"],
    ] },
    { type: "p", text: "A brief like this filters out freelancers who are not a fit and gives good ones the clarity to quote accurately. It also gives you something objective to check the work against when the project ends." },
  ],
  "seo-expert-for-small-business-islamabad": [
    { type: "h2", text: "Common small business SEO mistakes" },
    { type: "list", items: [
      "**One page for everything.** A single “Services” page cannot rank for ten different services.",
      "**Phone numbers as images.** Customers on mobile cannot tap them, and Google cannot read them.",
      "**No prices at all.** Customers compare prices and skip businesses that hide them.",
      "**Ignoring negative reviews.** A calm, helpful reply often wins more trust than the complaint costs.",
      "**Copying a competitor’s content.** Duplicate content rarely ranks and makes you look generic.",
      "**Stopping too early.** Most small businesses that quit SEO do so just before it starts working.",
    ] },
    { type: "p", text: "Fixing these takes little money but some attention. For many small businesses in Islamabad and Rawalpindi, simply correcting them produces more enquiries than any paid campaign they have tried." },
  ],
  "seo-expert-price-islamabad": [
    { type: "h2", text: "SEO pricing models explained" },
    { type: "table", caption: "Common ways SEO is priced", head: ["Model", "How it works", "Best for"], rows: [
      ["Monthly retainer", "Fixed monthly fee for an agreed scope", "Ongoing SEO and local search"],
      ["Project fee", "One price for a defined project", "Audits, migrations, setups"],
      ["Hourly", "Pay for time used", "Consulting and training"],
      ["Performance-based", "Fees tied to results", "Rare; often encourages easy keywords"],
    ] },
    { type: "p", text: "Monthly retainers are the most common in Islamabad because SEO is ongoing work. Project fees suit audits, Business Profile setups and website migrations. Be cautious with pure performance pricing: it sounds attractive but often leads providers to chase easy keywords that bring little business. A fair arrangement ties the retainer to a clear scope and reports results honestly." },
  ],
  "best-seo-expert-in-pakistan": [
    { type: "h2", text: "Matching expertise to your market" },
    { type: "table", caption: "What to look for by business type", head: ["Business type", "Expertise to prioritise"], rows: [
      ["Local service business", "Google Business Profile, reviews, area pages"],
      ["Exporter", "International SEO, product content, buyer trust signals"],
      ["Online store", "Category architecture, product data, marketplace competition"],
      ["Software company", "Use-case and comparison content, technical SEO"],
      ["Healthcare or legal", "E-E-A-T, credentials, accuracy and compliance"],
      ["Multi-city brand", "City-level strategy and consistent local data"],
    ] },
    { type: "p", text: "Once you know which row describes you, the search for the best SEO expert becomes much easier. You are no longer comparing everyone in Pakistan, just the few people with evidence in your kind of market." },
  ],
  "seo-expert-rawalpindi-hiring-guide": [
    { type: "h2", text: "Mistakes Rawalpindi businesses make with SEO" },
    { type: "list", items: [
      "**Treating Rawalpindi as one market.** Saddar and Bahria Town customers search differently.",
      "**Using an Islamabad address to look premium.** It confuses customers and Google, and risks your Business Profile.",
      "**Ignoring Roman Urdu.** Many Pindi customers type in Roman Urdu; your Search Console shows the phrases.",
      "**No WhatsApp button.** Many customers would rather message than call or fill in a form.",
      "**Copying Islamabad competitors’ pages.** Your customers, prices and areas are different, so your content should be too.",
    ] },
    { type: "p", text: "Avoiding these keeps your SEO grounded in how Rawalpindi actually buys. The businesses that win in Pindi are usually those that look most clearly local: real photos, real areas, real prices and fast replies on WhatsApp." },
  ],
  "local-seo-expert-islamabad": [
    { type: "h2", text: "Common Google Maps mistakes in Islamabad" },
    { type: "list", items: [
      "**Wrong primary category.** Choosing a broad category like “Health” instead of “Physiotherapist” makes you less relevant.",
      "**Address without the sector.** Customers search by sector; your address should make it clear.",
      "**Stock photos.** Real photos of your premises and team build more trust and engagement.",
      "**Hours not updated for Ramadan or holidays.** Wrong hours frustrate customers and lead to negative reviews.",
      "**Never replying to reviews.** Replies show you care and give context to complaints.",
    ] },
    { type: "p", text: "Each of these is quick to fix. In our experience, correcting categories and photos alone often produces visible movement in Islamabad map results within a few weeks." },
  ],
  "technical-seo-expert": [
    { type: "h2", text: "Technical problems we see most on Pakistani sites" },
    { type: "list", items: [
      "**Staging or test sites indexed** alongside the live site, creating duplicates.",
      "**Both http and https, or www and non-www, accessible** without redirects.",
      "**Huge uncompressed images** uploaded straight from phones.",
      "**Contact details in images** that search engines cannot read.",
      "**JavaScript-only menus** that hide links from crawlers.",
      "**Redesigns launched without redirects**, losing years of rankings overnight.",
    ] },
    { type: "p", text: "Most of these are inexpensive to fix once identified. The costly ones are migrations without redirects, which is why we recommend involving a technical SEO expert before, not after, any website redesign." },
  ],
  "wordpress-seo-expert": [
    { type: "h2", text: "WordPress mistakes that quietly cost rankings" },
    { type: "list", items: [
      "**“Discourage search engines” left ticked** after launch, hiding the site from Google.",
      "**Changing permalinks without redirects**, breaking every indexed URL.",
      "**Nulled themes and plugins** that inject spam links and malware.",
      "**Page builders loading every module on every page.**",
      "**Hundreds of thin tag pages** created by adding many tags to each post.",
    ] },
    { type: "p", text: "Nulled, pirated themes deserve special mention: they are common in Pakistan because they are free, but they often contain hidden spam links or malware that can damage rankings and trust. A legitimate licence costs far less than recovering a hacked site." },
  ],
  "shopify-seo-expert": [
    { type: "h2", text: "Shopify mistakes Pakistani stores make" },
    { type: "list", items: [
      "**Supplier descriptions copied across products**, identical to every other reseller.",
      "**Dozens of near-duplicate collections** such as “New”, “Latest” and “New Arrivals”.",
      "**Delivery and COD details hidden** in a policy page nobody reads.",
      "**Apps installed for every small feature** and never removed.",
      "**Product images without alt text**, missing image search traffic.",
    ] },
    { type: "p", text: "Fixing these turns a store that looks like every other reseller into one that answers buyers’ questions better than the competition, which is exactly what search engines and shoppers reward." },
  ],
  "ecommerce-seo-expert": [
    { type: "h2", text: "An illustrative example: restructuring a fashion store" },
    { type: "p", text: "Imagine an online clothing store in Lahore with one category called “Women” containing 900 products, filters for size and colour generating thousands of URLs, and supplier descriptions throughout." },
    { type: "list", ordered: true, items: [
      "Split “Women” into categories that match searches: lawn suits, kurtis, formal wear, bridal and accessories.",
      "Create indexable pages for a few high-demand combinations, such as “printed lawn suits”, and keep other filter URLs out of the index.",
      "Rewrite the top fifty product descriptions with fabric, fit and care details.",
      "Add delivery times, COD and returns information to every category and product page.",
      "Track organic revenue by category to decide where to expand next.",
    ] },
    { type: "p", text: "Changes like these focus Google on the pages that matter and give shoppers clearer choices. The exact results vary by store, but the structure is the foundation everything else builds on." },
  ],
  "google-maps-seo-expert": [
    { type: "h2", text: "What to do if your profile is suspended" },
    { type: "p", text: "Suspensions happen, sometimes even to businesses that did nothing wrong. A good Google Maps SEO expert handles them calmly and by the book." },
    { type: "list", ordered: true, items: [
      "Do not create a new profile; it can make the situation worse.",
      "Review the profile against Google’s guidelines and correct anything that breaks them, such as keywords in the name.",
      "Gather proof of your business: utility bills, registration documents, signage and premises photos.",
      "Submit a reinstatement request through Google with the evidence.",
      "Keep details consistent everywhere while you wait.",
    ] },
    { type: "p", text: "Ask any Maps specialist you hire how they would handle a suspension. A clear, guideline-based answer is a good sign; vague promises of a quick fix are not." },
  ],
  "on-page-seo-expert": [
    { type: "h2", text: "On-page mistakes we fix most often" },
    { type: "list", items: [
      "**Several pages targeting the same keyword**, splitting signals between them.",
      "**Titles starting with the brand name** on every page instead of the topic.",
      "**H1 tags used for styling** rather than structure.",
      "**Service details hidden in images or PDFs.**",
      "**No internal links** from the home page to key services.",
      "**Outdated prices or information** that undermine trust.",
    ] },
    { type: "p", text: "Each of these is fixable in hours rather than weeks, which is why on-page work is often the fastest way to see movement on an existing site." },
  ],
  "off-page-seo-expert": [
    { type: "h2", text: "Off-page ideas specific to Pakistan" },
    { type: "list", items: [
      "**Chambers of commerce** in Islamabad, Rawalpindi, Lahore, Karachi and other cities list members.",
      "**Trade associations** for your industry often have member directories and news sections.",
      "**University and college partnerships**, such as internships or guest lectures, can earn educational links.",
      "**Local news and business publications** look for expert comment on market trends.",
      "**Supplier and distributor pages** listing where to buy or certified partners.",
      "**Community initiatives**, such as sponsoring local sports or charity events.",
    ] },
    { type: "p", text: "These sources take more effort than buying links, but they are relevant, durable and safe, and many also bring referral traffic and customers directly, not just ranking signals." },
    { type: "callout", tone: "tip", title: "Unlinked mentions", text: "Search for your business name in news and directories. Where you are mentioned without a link, a polite request often turns the mention into a link." },
  ],
  "seo-audit-expert": [
    { type: "h2", text: "When to commission an audit" },
    { type: "list", items: [
      "**Before a redesign or migration**, to protect existing rankings.",
      "**After a sudden traffic drop**, to diagnose the cause.",
      "**Before hiring an SEO agency**, so you can judge their plan against an independent baseline.",
      "**Once a year**, as routine maintenance.",
      "**When entering a new market**, such as a new city or country.",
    ] },
    { type: "p", text: "Timing matters. An audit before a redesign costs a fraction of the recovery work after a botched migration, and an independent audit before hiring an agency gives you a fair standard to measure their proposal against." },
  ],
  "link-building-expert": [
    { type: "h2", text: "Questions to ask before hiring a link builder" },
    { type: "list", items: [
      "How do you find and approach linking sites?",
      "Do you pay for any links? If so, are they labelled as sponsored?",
      "Will I receive a list of every link with the date and target page?",
      "What happens if a link is removed or the site is penalised?",
      "Which of your past links are you most proud of, and why?",
    ] },
    { type: "p", text: "Good link builders answer these openly and enjoy talking about their best placements. Evasive answers about methods or reluctance to share link lists are reasons to walk away." },
  ],
  "real-estate-seo-expert": [
    { type: "h2", text: "Mistakes property businesses make online" },
    { type: "list", items: [
      "**Hiding prices** and asking buyers to call for details.",
      "**Anonymous websites** with no team, registration or office information.",
      "**Thousands of expired listings** left live without redirects.",
      "**Copying portal descriptions** instead of writing original project content.",
      "**No overseas contact options**, such as WhatsApp or time-zone friendly hours.",
    ] },
    { type: "p", text: "Property is the sector where Pakistani buyers are most cautious. Every one of these mistakes reduces trust, and trust is what decides whether a serious buyer contacts you or moves on to the next agency." },
  ],
  "healthcare-seo-expert": [
    { type: "h2", text: "Mistakes hospitals and clinics should avoid" },
    { type: "list", items: [
      "**Generic health articles copied or spun** from other sites.",
      "**Doctor pages without credentials** or registration details.",
      "**Promising cures or guaranteed outcomes.**",
      "**One Business Profile for several locations.**",
      "**Phone-only booking** during limited hours.",
      "**Reviews incentivised with discounts**, which breaks Google’s policies.",
    ] },
    { type: "p", text: "Healthcare is where trust matters most, and where mistakes cost the most. A careful approach, built on accurate information and real credentials, protects patients and rankings alike." },
  ],
  "dental-seo-expert": [
    { type: "h2", text: "Mistakes dental clinics make with SEO" },
    { type: "list", items: [
      "**One generic “Treatments” page** instead of a page per procedure.",
      "**Stock photos** instead of the real clinic and team.",
      "**No evening or weekend information**, when many patients look for after-work appointments.",
      "**Ignoring negative reviews** about waiting times or billing.",
      "**Dentist names missing** from the website entirely.",
    ] },
    { type: "p", text: "Patients choose dentists they feel they know. Putting real people, real prices and real photos on your website and profile is the simplest way to stand out in a crowded local market." },
  ],
  "lawyer-seo-expert": [
    { type: "h2", text: "An illustrative example: a family law practice" },
    { type: "p", text: "Imagine a family law practice in Islamabad with a single-page website listing every service in one paragraph. A careful SEO approach might look like this:" },
    { type: "list", ordered: true, items: [
      "Create separate, factual pages for khula and divorce, child custody, maintenance and family settlements, describing the process in plain language.",
      "Publish profiles for each lawyer with qualifications, enrolment and areas of focus.",
      "Add a guide explaining the general steps of a family court case, reviewed by a senior lawyer and dated.",
      "Optimise the Business Profile with the correct category, office photos and consultation timings.",
      "Track enquiries by practice area to see which pages bring clients.",
    ] },
    { type: "p", text: "Everything here informs rather than solicits, which keeps the firm within professional expectations while making it far easier for clients to find and evaluate it." },
  ],
  "restaurant-seo-expert": [
    { type: "h2", text: "Mistakes restaurants make online" },
    { type: "list", items: [
      "**Different phone numbers and names** across delivery apps, Maps and social media.",
      "**Old photos** that no longer match the food or interior.",
      "**Hours not updated during Ramadan**, sending iftar customers to a closed door.",
      "**Arguing with reviewers** publicly.",
      "**A website that is just a logo and an Instagram link.**",
    ] },
    { type: "p", text: "Most restaurants in Islamabad and Rawalpindi can fix these in a week. The payoff is immediate, because restaurant decisions are made in minutes on a phone." },
  ],
  "hotel-seo-expert": [
    { type: "h2", text: "Mistakes hotels make with direct bookings" },
    { type: "list", items: [
      "**A slow or confusing booking engine**, especially on mobile.",
      "**Higher prices on the official site** than on booking platforms.",
      "**No real photos of rooms**, only marketing renders.",
      "**Ignoring reviews on platforms**, which guests read before booking anywhere.",
      "**No event or corporate pages**, missing valuable group business.",
    ] },
    { type: "p", text: "Guests book directly when it is easy and when they trust it is the best option. Fixing these issues is often worth more than any amount of new content." },
  ],
  "travel-seo-expert": [
    { type: "h2", text: "Mistakes travel agencies make online" },
    { type: "list", items: [
      "**Publishing seasonal pages during the season**, too late to rank.",
      "**Vague packages** without day-by-day itineraries or inclusions.",
      "**Stock photos of destinations** instead of photos from real trips.",
      "**No licence or registration details** visible on the site.",
      "**Mixing Umrah, northern tours and visas** on one generic page.",
    ] },
    { type: "p", text: "Travellers, especially families and pilgrims, need confidence before they pay. Clear itineraries, real photos and visible credentials do more for bookings than any discount banner." },
  ],
  "education-seo-expert": [
    { type: "h2", text: "Mistakes schools make online" },
    { type: "list", items: [
      "**Admission pages updated after the season starts.**",
      "**One page for all campuses**, so no campus ranks locally.",
      "**No fee information**, forcing parents to call for basics.",
      "**Outdated results and staff lists.**",
      "**No transport route information**, a key question for many parents.",
    ] },
    { type: "p", text: "Parents make one of their biggest decisions on the information schools publish. Schools that answer their questions clearly and early win more applications and more qualified ones." },
  ],
  "saas-seo-expert": [
    { type: "h2", text: "Mistakes software companies make with SEO" },
    { type: "list", items: [
      "**Only product-name pages**, nothing for problems or use cases.",
      "**Blogs about the company** instead of customers’ problems.",
      "**Pricing hidden behind a demo request.**",
      "**App and staging subdomains indexed**, creating duplicate or empty pages.",
      "**Reporting traffic instead of pipeline.**",
    ] },
    { type: "p", text: "Pakistani software companies selling abroad often have excellent products and invisible websites. Shifting content towards buyers’ problems and decisions is usually the single biggest improvement." },
  ],
  "international-seo-expert": [
    { type: "h2", text: "Mistakes exporters make online" },
    { type: "list", items: [
      "**Machine-translated pages** that read poorly to native buyers.",
      "**Prices or minimum orders not stated**, slowing enquiries.",
      "**No certifications shown**, despite having them.",
      "**Contact options only in Pakistan time.**",
      "**Hreflang added without return links**, so Google ignores it.",
    ] },
    { type: "p", text: "International buyers often decide whether a supplier is credible within seconds. Clear credentials, specifications and responsive contact options make the difference between an enquiry and a closed tab." },
  ],
  "seo-expert-near-me": [
    { type: "h2", text: "Red flags in “near me” results" },
    { type: "list", items: [
      "**Dozens of five-star reviews posted in the same week**, often a sign of fake reviews.",
      "**Business names stuffed with keywords**, such as “Best SEO Expert Islamabad No 1”.",
      "**No website or a template site** with no real people.",
      "**Guarantees of first-page rankings** in the profile description.",
      "**Addresses that are residential or virtual** with no office.",
    ] },
    { type: "p", text: "Ironically, some of the businesses ranking for “SEO expert near me” use the very tactics a good SEO expert would warn you against. Treat those signals as a reason to look further down the list." },
  ],
  "seo-expert-blue-area-islamabad": [
    { type: "h2", text: "Content ideas for Blue Area firms" },
    { type: "list", items: [
      "**Regulation explainers**, such as company registration steps or tax filing deadlines.",
      "**Process guides** for procurement, contracts or onboarding a new client.",
      "**Sector updates** on changes affecting your clients’ industries.",
      "**Case studies** with client permission, showing the problem, approach and outcome.",
      "**Comparison guides**, such as in-house versus outsourced services.",
    ] },
    { type: "p", text: "Professional buyers in the capital read before they call. Content that shows you understand their problems positions your firm as the obvious shortlist choice." },
  ],
  "seo-expert-dha-islamabad": [
    { type: "h2", text: "Mistakes DHA businesses make" },
    { type: "list", items: [
      "**Using a vague address** such as “DHA Islamabad” without the phase.",
      "**Generic Islamabad content** that ignores the community.",
      "**No English content for overseas owners**, a large and valuable audience.",
      "**Slow replies to WhatsApp enquiries**, which premium customers notice.",
    ] },
    { type: "p", text: "Residents and owners in DHA expect a polished experience. The businesses that win are the ones that feel local, precise and responsive from the first search." },
  ],
  "seo-expert-bahria-town": [
    { type: "h2", text: "Mistakes Bahria Town businesses make" },
    { type: "list", items: [
      "**Address pins in the wrong phase**, sending customers the wrong way.",
      "**No price information** in a price-conscious market.",
      "**Generic Rawalpindi content** ignoring the community.",
      "**Relying only on Facebook groups** for visibility.",
    ] },
    { type: "p", text: "Community Facebook groups help, but they are temporary. A well-optimised Business Profile keeps working every day, for every resident who searches." },
  ],
  "seo-expert-vs-digital-marketing-expert": [
    { type: "h2", text: "An illustrative example: two businesses, two choices" },
    { type: "p", text: "Consider two illustrative businesses. A tax consultancy in Blue Area finds that most new clients search Google for specific services. Its best first hire is an SEO expert who builds detailed service pages and a strong Business Profile." },
    { type: "p", text: "A clothing brand in Lahore launching a new collection needs sales in the next six weeks and sells visually. Its best first hire is a digital marketing expert who can run Meta and Google ads, coordinate social content and set up tracking, with SEO added as the store grows." },
    { type: "p", text: "Neither choice is universally right. The decision follows where customers come from and how quickly results are needed." },
  ],
  "seo-expert-vs-seo-freelancer": [
    { type: "h2", text: "Questions that reveal experience" },
    { type: "list", items: [
      "Tell me about a site where SEO did not work. What did you learn?",
      "How do you decide what to fix first on a new site?",
      "How have recent Google updates changed your approach?",
      "What would you not do, even if a client asked?",
    ] },
    { type: "p", text: "Experienced people answer these with specific stories and clear reasoning. Less experienced people tend to answer with general principles. Both can be valuable hires, as long as the role matches the experience." },
  ],
  "how-to-become-seo-expert-pakistan": [
    { type: "h2", text: "Mistakes beginners make" },
    { type: "list", items: [
      "**Collecting certificates** instead of practising on real sites.",
      "**Chasing tools** before understanding fundamentals.",
      "**Selling black-hat services** for quick freelance income, which damages reputations.",
      "**Ignoring writing skills.** Clear English writing is a big part of SEO work.",
      "**Not documenting results**, leaving nothing to show employers.",
    ] },
    { type: "p", text: "Avoiding these puts you ahead of most beginners. The SEO professionals who progress fastest in Pakistan are those who practise constantly, write clearly and can show what they achieved." },
  ],
  "seo-expert-salary-pakistan": [
    { type: "h2", text: "Freelance and remote earnings" },
    { type: "p", text: "Many Pakistani SEO professionals work remotely for agencies and businesses abroad or freelance on international platforms. Earnings vary hugely: beginners competing on price often earn less than local salaries, while specialists with strong portfolios and reliable communication can earn well above them." },
    { type: "list", items: [
      "**Specialise** in a niche, such as ecommerce, local SEO or technical audits.",
      "**Build long-term clients** rather than one-off gigs.",
      "**Communicate reliably** across time zones.",
      "**Receive payments legally** through approved channels and keep records.",
    ] },
    { type: "p", text: "Remote work rewards reliability as much as skill. Professionals who meet deadlines, report clearly and stay with clients for years tend to earn the most." },
  ],
  "ai-seo-expert": [
    { type: "h2", text: "Mistakes businesses make with AI and SEO" },
    { type: "list", items: [
      "**Publishing hundreds of AI articles** without editing or expertise.",
      "**Trusting AI facts without checking**, including invented statistics.",
      "**Blocking all AI crawlers by accident** through firewall or CDN settings.",
      "**Ignoring how AI describes the business**, including outdated information.",
      "**Abandoning SEO fundamentals**, which AI search still depends on.",
    ] },
    { type: "p", text: "AI rewards the same things good SEO always has: accurate, helpful, clearly structured content from real experts. Businesses that use AI to do that faster benefit most." },
  ],
  "seo-for-chatgpt-and-google-ai-search": [
    { type: "h2", text: "Mistakes that keep businesses out of AI answers" },
    { type: "list", items: [
      "**Blocking AI search crawlers unintentionally** with bot protection.",
      "**Key facts only in images**, such as price lists or menus.",
      "**Conflicting information** across the website, Business Profile and directories.",
      "**No About page** or named people behind the business.",
      "**Thin pages** that never directly answer the question in the title.",
    ] },
    { type: "p", text: "Each of these makes it harder for AI systems to understand and trust your business. Fixing them also improves traditional SEO, which is why GEO and SEO work best as one plan." },
  ],
};
