import type { PostInput } from "@/lib/blog";
import { SRC } from "./part1";

export const PART8: PostInput[] = [
  /* ------------------------------------------------------------------ 33 */
  {
    slug: "seo-expert-dha-islamabad",
    title: "SEO Expert in DHA Islamabad: Hiring Guide",
    keyword: "SEO expert DHA Islamabad",
    description: "How businesses in DHA Islamabad should hire an SEO expert: how search works in a self-contained community, phase-level targeting, premium buyers, property and services, and what to ask providers.",
    category: "Local SEO",
    icon: "house",
    accent: "green",
    answer: "Businesses in DHA Islamabad serve a self-contained, premium community where residents search by phase and expect polished, trustworthy websites. Hire an SEO expert who targets phase-level searches, optimises your Google Business Profile for the exact DHA location, builds content for premium buyers and overseas owners, and tracks calls and WhatsApp enquiries from the community.",
    takeaways: [
      "DHA Islamabad residents often search by phase and nearby landmarks.",
      "Premium buyers expect credible, polished websites and clear pricing.",
      "Many property owners live abroad, so English content for overseas owners matters.",
      "Precise addresses and map pins are essential in large housing societies.",
      "Hire for local relevance and verified results, not just proximity.",
    ],
    body: [
      { type: "h2", text: "How search works in DHA Islamabad" },
      { type: "p", text: "DHA Islamabad is spread across several phases along the GT Road and Islamabad Expressway corridor, with its own commercial areas, schools, clinics and services. Residents often search for what is inside the community, for example “salon DHA Phase 2” or “school near DHA Islamabad”, rather than for Islamabad as a whole. A **local SEO expert** builds around that behaviour." },
      { type: "stats", title: "DHA search behaviour", items: [
        { value: "Phase", label: "Searches often include the phase or sector" },
        { value: "Premium", label: "Higher expectations for quality and credibility" },
        { value: "Overseas", label: "Many property owners and investors live abroad" },
        { value: "Mobile", label: "Most local searches happen on a phone" },
      ] },
      { type: "h2", text: "Categories that perform in DHA" },
      { type: "table", caption: "Common DHA business categories", head: ["Category", "What to prioritise"], rows: [
        ["Real estate and construction", "Phase and block pages, overseas owner content, completed projects"],
        ["Interiors and home services", "Portfolio photos, service areas within DHA, reviews"],
        ["Schools and tuition", "Campus page, fees, transport routes within DHA"],
        ["Clinics and salons", "Business Profile, treatments with price ranges, booking"],
        ["Restaurants and cafes", "Menu as text, photos, family seating, timings"],
      ] },
      { type: "h2", text: "What to ask an SEO provider" },
      { type: "slides", title: "Questions for DHA businesses", slides: [
        { title: "Local knowledge", points: ["How do residents search for my service?", "Which phases should I target first?", "How will you handle nearby Bahria and Rawalpindi searches?"] },
        { title: "Profile setup", points: ["How will you set my address and pin precisely?", "Which categories fit my business?", "How will we grow reviews?"] },
        { title: "Content", points: ["Will you create content for overseas owners?", "How will pricing be presented?", "What will my service pages include?"] },
      ] },
      { type: "callout", tone: "tip", title: "Get the pin exactly right", text: "Large housing societies confuse map pins and delivery riders alike. Place your Business Profile pin on the correct building and add landmarks to your directions." },
      { type: "h2", text: "Reaching overseas DHA owners" },
      { type: "p", text: "Many plot and house owners in DHA live abroad. They search in English for construction companies, property managers, maintenance services and agents they can trust remotely. Content with clear processes, progress updates, references and WhatsApp contact across time zones reaches this valuable audience." },
      { type: "video", title: "Hiring an SEO expert for a DHA business", steps: [
        { title: "Map your audience", text: "Separate residents, nearby communities and overseas owners, and note what each searches for." },
        { title: "Check local results", text: "Search your service plus DHA and the phase on your phone and note who appears." },
        { title: "Shortlist providers", text: "Choose providers who understand housing-society search and can show local results." },
        { title: "Compare audits", text: "Ask for an audit covering your profile, website and content opportunities." },
        { title: "Start focused", text: "Begin with the profile, two key service pages and overseas owner content where relevant." },
      ] },
      { type: "p", text: "See our [Islamabad SEO guide](/seo-expert/seo-expert-islamabad/) and [real estate SEO guide](/seo-for/seo-for-real-estate/), or [request a free audit](/contact/)." },
      { type: "sources", items: [SRC.gbp, SRC.local] },
    ],
    faqs: [
      { q: "How do DHA Islamabad residents search for services?", a: "Often by phase or with “DHA Islamabad” in the search, on mobile, looking for services inside or near the community." },
      { q: "Should DHA businesses target overseas owners?", a: "If you offer property, construction, maintenance or management services, yes. Many owners live abroad and search in English for trustworthy providers." },
      { q: "How do I make my DHA business show on Google Maps?", a: "Create a complete Business Profile with a precise address and pin, the right categories, real photos and a steady review routine." },
      { q: "Do I need a different SEO strategy for DHA than for Islamabad?", a: "The fundamentals are the same, but targeting should reflect phase-level searches, premium expectations and overseas owners." },
    ],
    related: [
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "SEO for real estate", href: "/seo-for/seo-for-real-estate/" },
      { label: "Local SEO services", href: "/services/local-seo/" },
    ],
  },

  /* ------------------------------------------------------------------ 34 */
  {
    slug: "seo-expert-bahria-town",
    title: "SEO Expert in Bahria Town Rawalpindi: Services and Pricing",
    keyword: "SEO expert Bahria Town",
    description: "SEO for businesses in Bahria Town Rawalpindi: how residents search across phases, which services matter most, indicative pricing for local SEO and what a good provider should deliver.",
    category: "Local SEO",
    icon: "building",
    accent: "amber",
    answer: "Businesses in Bahria Town Rawalpindi need SEO that targets phase-level searches, wins the Google map pack inside the community, and reaches nearby DHA and Rawalpindi residents. Core services are Google Business Profile optimisation, service pages with prices, reviews and citations. As an indicative 2026 guide, local SEO for a single Bahria Town business often costs roughly PKR 25,000 to 80,000 a month depending on scope and competition.",
    takeaways: [
      "Bahria Town is a large, self-contained community where searches often name the phase.",
      "The map pack decides most local service searches inside the society.",
      "Pricing depends on competition and scope; treat ranges as indicative.",
      "Combine Bahria Town targeting with nearby DHA and Rawalpindi where you serve them.",
      "Track enquiries by phase to see where customers come from.",
    ],
    body: [
      { type: "h2", text: "How search works in Bahria Town" },
      { type: "p", text: "Bahria Town Rawalpindi spans multiple phases with commercial areas, schools, hospitals, restaurants and home services. Residents search for services nearby, often naming the phase or the civic centre. Businesses that appear in the map pack for those searches win most of the local demand." },
      { type: "process", title: "How a Bahria Town customer finds a business", steps: [
        { title: "Search", text: "Service plus phase or Bahria Town" },
        { title: "Map pack", text: "Top three listings compared" },
        { title: "Check", text: "Reviews, photos, prices" },
        { title: "Contact", text: "Call or WhatsApp" },
      ] },
      { type: "h2", text: "SEO services Bahria Town businesses need" },
      { type: "slides", title: "Core services", slides: [
        { title: "Google Business Profile", points: ["Accurate phase and address", "Right categories and services", "Photos and regular updates"] },
        { title: "Service pages", points: ["Prices or price ranges", "Phases and nearby areas served", "WhatsApp contact"] },
        { title: "Reviews", points: ["A routine for asking customers", "Replies to every review", "No incentives or fake reviews"] },
        { title: "Citations", points: ["Consistent details across directories", "Community and association listings", "Social profiles"] },
      ] },
      { type: "h2", text: "Indicative pricing" },
      { type: "table", caption: "Indicative local SEO costs for a Bahria Town business (2026)", head: ["Scope", "Indicative range", "Typical inclusions"], rows: [
        ["Business Profile setup", "PKR 10,000 – 25,000 one-off", "Setup, categories, services, photos, review link"],
        ["Basic local SEO", "PKR 25,000 – 45,000 / month", "Profile management, citations, small on-page fixes"],
        ["Full local SEO", "PKR 45,000 – 80,000 / month", "Profile, service and area pages, content, links, reporting"],
      ] },
      { type: "callout", tone: "note", title: "Indicative only", text: "These ranges reflect what we commonly see in the twin cities and will vary with competition, scope and provider. Always compare written scopes, not headline prices." },
      { type: "h2", text: "Extending beyond Bahria Town" },
      { type: "p", text: "Many Bahria Town businesses also serve DHA Rawalpindi and Islamabad, and neighbouring areas along the Expressway. If you genuinely serve those areas, add useful pages for them and set your service area accordingly, while keeping your Business Profile address accurate." },
      { type: "bars", title: "Where Bahria Town SEO effort pays off first", items: [
        { label: "Business Profile optimisation", value: 5, display: "Highest" },
        { label: "Reviews", value: 4, display: "High" },
        { label: "Service pages with prices", value: 4, display: "High" },
        { label: "Area pages for nearby communities", value: 3, display: "Medium" },
        { label: "Citations", value: 2, display: "Supporting" },
      ], note: "Our view based on local campaigns in the twin cities." },
      { type: "video", title: "Getting started in Bahria Town", steps: [
        { title: "Claim and verify", text: "Claim your Business Profile and verify the correct phase address." },
        { title: "Complete everything", text: "Add categories, services, photos, timings and attributes." },
        { title: "Start reviews", text: "Ask every satisfied customer for a review with a direct link." },
        { title: "Build service pages", text: "Create a page per main service with price ranges and the phases you serve." },
        { title: "Review monthly", text: "Check calls, directions and WhatsApp enquiries and adjust." },
      ] },
      { type: "p", text: "Our training campus is in Scheme 3, Rawalpindi, and we work with Bahria Town businesses regularly. See our [Rawalpindi SEO guide](/seo-expert/seo-expert-rawalpindi/) or [request a free audit](/contact/)." },
      { type: "sources", items: [SRC.gbp, SRC.local] },
    ],
    faqs: [
      { q: "How much does SEO cost for a Bahria Town business?", a: "Indicatively, local SEO often costs around PKR 25,000 to 80,000 a month depending on scope and competition, with one-off Business Profile setup around PKR 10,000 to 25,000." },
      { q: "How do I rank in Google Maps in Bahria Town?", a: "Complete your Business Profile with the correct phase address, categories and services, add real photos, build reviews and keep details consistent across directories." },
      { q: "Should I target DHA and Islamabad too?", a: "If you genuinely serve those areas, yes, with useful pages for each and an accurate service area setting." },
      { q: "How long does local SEO take in Bahria Town?", a: "Map pack improvements often appear within four to eight weeks once the profile is optimised and reviews start coming in." },
    ],
    related: [
      { label: "SEO Expert in Rawalpindi", href: "/seo-expert/seo-expert-rawalpindi/" },
      { label: "Local SEO services", href: "/services/local-seo/" },
      { label: "Request a free audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 35 */
  {
    slug: "seo-expert-vs-digital-marketing-expert",
    title: "SEO Expert vs Digital Marketing Expert: What's the Difference?",
    keyword: "SEO expert vs digital marketing expert",
    description: "The difference between an SEO expert and a digital marketing expert: skills, responsibilities, timelines and costs, and how to decide which one your business should hire first.",
    category: "Comparison",
    icon: "git-compare",
    accent: "blue",
    answer: "An SEO expert specialises in earning visibility in Google and AI search through technical work, content and authority. A digital marketing expert manages a wider mix: SEO, paid ads, social media, email and analytics. Hire an SEO expert when organic search is your main growth channel; hire a digital marketing expert when you need several channels planned and coordinated together.",
    takeaways: [
      "SEO is one channel; digital marketing covers many channels.",
      "SEO builds long-term, compounding visibility; ads deliver immediate but paid traffic.",
      "Specialists go deeper; generalists coordinate better.",
      "Many small businesses start with SEO and local search, then add paid channels.",
      "The best setups combine a strategist with channel specialists.",
    ],
    body: [
      { type: "h2", text: "Two roles, different scope" },
      { type: "p", text: "An **SEO expert** focuses on organic search: making your website and Business Profile appear when people search. A **digital marketing expert** plans and manages the whole online mix: SEO, Google and Meta ads, social media, email, content and analytics. Both are valuable; they solve different problems." },
      { type: "compare", title: "SEO expert versus digital marketing expert", left: { label: "SEO expert", items: [
        "Deep expertise in search",
        "Technical SEO, content and links",
        "Results build over months and compound",
        "Ideal when search is the main channel",
      ] }, right: { label: "Digital marketing expert", items: [
        "Broad expertise across channels",
        "Ads, social, email, SEO and analytics",
        "Can deliver quick wins through paid media",
        "Ideal when several channels must work together",
      ] } },
      { type: "h2", text: "How the timelines differ" },
      { type: "bars", title: "Typical time to first results by channel", items: [
        { label: "Google Ads", value: 1, display: "Days" },
        { label: "Meta ads", value: 1, display: "Days" },
        { label: "Local SEO (map pack)", value: 2, display: "Weeks" },
        { label: "Organic SEO", value: 4, display: "Months" },
      ], note: "Indicative; paid channels stop when spending stops, while SEO tends to compound." },
      { type: "h2", text: "Which should you hire first?" },
      { type: "table", caption: "Matching the hire to the situation", head: ["Your situation", "Hire first"], rows: [
        ["Customers search Google for what you sell", "SEO expert"],
        ["You need leads this month", "Digital marketing expert (with paid ads)"],
        ["You sell visually, e.g. fashion or food", "Digital marketing expert (social focus)"],
        ["You run several channels already and lack coordination", "Digital marketing expert"],
        ["Your site has technical or ranking problems", "SEO expert"],
      ] },
      { type: "slides", title: "Questions to decide", slides: [
        { title: "Where do customers come from?", points: ["Search, social or referrals?", "Which channel brings the best customers?", "Where are competitors winning?"] },
        { title: "How fast do you need results?", points: ["This month or this year?", "Can you fund ads while SEO builds?", "What is the cost of waiting?"] },
        { title: "What do you already have?", points: ["An in-house team?", "Existing agencies?", "Good tracking in place?"] },
      ] },
      { type: "callout", tone: "tip", title: "Combine them", text: "A common, effective setup is a digital marketing strategist who plans the mix and measures results, working with an SEO specialist and an ads specialist who execute in depth." },
      { type: "video", title: "Choosing between an SEO and a digital marketing expert", steps: [
        { title: "List your channels", text: "Write down every channel you use or want to use, and what each produces today." },
        { title: "Identify the main gap", text: "Is the biggest missed opportunity in search, ads or social?" },
        { title: "Decide on timing", text: "If you need leads quickly, include paid ads; if you can wait, SEO compounds." },
        { title: "Hire for the gap", text: "Choose a specialist for a single gap, a generalist for coordination across several." },
        { title: "Measure the same way", text: "Judge every channel on enquiries and cost per lead so you can compare fairly." },
      ] },
      { type: "p", text: "MrSEO.pk offers [SEO](/services/seo/), [Google Ads](/services/ppc/) and [social media](/services/social-media/) as one plan. Students interested in both paths can compare our [SEO course](/courses/seo/) and [complete digital marketing course](/courses/digital-marketing/)." },
      { type: "sources", items: [SRC.needSeo, SRC.starter] },
    ],
    faqs: [
      { q: "What is the difference between an SEO expert and a digital marketing expert?", a: "An SEO expert specialises in organic search visibility. A digital marketing expert manages a wider mix including ads, social media, email and analytics, often with SEO as one part." },
      { q: "Should I hire an SEO expert or a digital marketing expert first?", a: "Hire an SEO expert if search is your main channel and you can wait months for compounding results. Hire a digital marketing expert if you need several channels coordinated or leads quickly through ads." },
      { q: "Is SEO part of digital marketing?", a: "Yes. SEO is one channel within digital marketing, alongside paid ads, social media, email and content." },
      { q: "Which career pays better in Pakistan?", a: "Both can pay well. Specialists with proven results and generalists who can manage budgets and teams are both in demand." },
    ],
    related: [
      { label: "SEO services", href: "/services/seo/" },
      { label: "Google Ads management", href: "/services/ppc/" },
      { label: "Complete digital marketing course", href: "/courses/digital-marketing/" },
    ],
  },

  /* ------------------------------------------------------------------ 36 */
  {
    slug: "seo-expert-vs-seo-freelancer",
    title: "SEO Expert vs SEO Freelancer: Which Should You Hire?",
    keyword: "SEO expert vs SEO freelancer",
    description: "SEO expert or SEO freelancer: how they differ in experience, accountability, cost and risk, and a simple framework for deciding which suits your project and budget.",
    category: "Comparison",
    icon: "users",
    accent: "violet",
    answer: "“SEO expert” describes a level of experience and strategic ability; “SEO freelancer” describes a working arrangement. A senior SEO expert can work as a freelancer, and a freelancer can be a beginner. Hire for proven experience and accountability: use freelancers for defined tasks, and an experienced expert or consultant for strategy, ongoing campaigns and high-stakes work.",
    takeaways: [
      "Expert describes experience; freelancer describes how someone works.",
      "Defined, one-off tasks suit freelancers well.",
      "Strategy, ongoing campaigns and recovery work need proven experience.",
      "Price differences usually reflect experience and accountability.",
      "Whoever you hire, verify results and keep ownership of your accounts.",
    ],
    body: [
      { type: "h2", text: "Clearing up the terms" },
      { type: "p", text: "The comparison is often framed as either-or, but the terms describe different things. **SEO expert** is about experience and judgement: someone who has delivered results across many sites and can plan strategy. **SEO freelancer** is about working arrangement: an independent person working on projects, often for several clients. A freelancer can be an expert; an agency employee can be a beginner." },
      { type: "compare", title: "Typical differences", left: { label: "Typical SEO freelancer", items: [
        "Works on defined tasks or projects",
        "Lower cost per hour",
        "Experience varies widely",
        "Availability shared across many clients",
      ] }, right: { label: "Typical SEO expert or consultant", items: [
        "Owns strategy and outcomes",
        "Higher fee, more accountability",
        "Proven track record across sites",
        "Fewer clients, deeper involvement",
      ] } },
      { type: "h2", text: "When each makes sense" },
      { type: "table", caption: "Choosing by project type", head: ["Project", "Better fit"], rows: [
        ["Fixing a list of on-page issues", "Freelancer"],
        ["Business Profile setup", "Freelancer or expert"],
        ["Content sprint with a clear brief", "Freelancer"],
        ["Overall SEO strategy", "Expert"],
        ["Website migration", "Expert"],
        ["Recovering from a traffic drop", "Expert"],
        ["Ongoing campaign with reporting to owners", "Expert, possibly with freelancers"],
      ] },
      { type: "h2", text: "Cost and risk" },
      { type: "bars", title: "Relative risk when the hire is a poor match", items: [
        { label: "Beginner freelancer on strategy work", value: 5, display: "High" },
        { label: "Beginner freelancer on defined tasks", value: 3, display: "Medium" },
        { label: "Expert on defined tasks", value: 1, display: "Low (but costly)" },
        { label: "Expert on strategy work", value: 1, display: "Low" },
      ], note: "A simple way to think about matching experience to the job." },
      { type: "slides", title: "Hiring safely either way", slides: [
        { title: "Verify", points: ["Ask for live examples", "Check claimed rankings yourself", "Speak to a past client"] },
        { title: "Scope", points: ["Write deliverables and deadlines", "Agree reporting", "Ban paid link schemes in writing"] },
        { title: "Protect", points: ["Keep accounts in your name", "Use user access, not passwords", "Pay by milestone"] },
      ] },
      { type: "video", title: "Deciding in five minutes", steps: [
        { title: "Describe the job", text: "Is it a defined task with a clear finish, or an ongoing responsibility for results?" },
        { title: "Assess the stakes", text: "Would a mistake be costly, such as during a migration or penalty recovery?" },
        { title: "Check your oversight", text: "Do you have someone who can check the work, or do you need the hire to own it?" },
        { title: "Match the hire", text: "Defined, lower-stakes tasks suit freelancers; strategy and high-stakes work need an expert." },
        { title: "Verify before signing", text: "Whoever you choose, check results and agree written scope and terms." },
      ] },
      { type: "p", text: "Syed Mudassir Shah works as an independent consultant with direct involvement in every account. If you already use freelancers, we can also oversee and check their work. [Get in touch](/contact/)." },
      { type: "sources", items: [SRC.needSeo, SRC.spam] },
    ],
    faqs: [
      { q: "What is the difference between an SEO expert and an SEO freelancer?", a: "Expert describes experience and strategic ability; freelancer describes an independent working arrangement. A freelancer can be an expert or a beginner." },
      { q: "Is a freelancer cheaper than an SEO expert?", a: "Usually per hour, yes. But hiring an inexperienced freelancer for strategy or high-stakes work can cost more in lost time and fixes." },
      { q: "Can I use both?", a: "Yes. A common setup is an expert who sets the strategy and checks quality, with freelancers delivering defined tasks." },
      { q: "How do I verify either one?", a: "Ask for live examples, check claimed rankings yourself, speak to a past client and start with a defined scope and milestone payments." },
    ],
    related: [
      { label: "Freelancing starter course", href: "/courses/freelancing/" },
      { label: "SEO services", href: "/services/seo/" },
      { label: "Get in touch", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 37 */
  {
    slug: "how-to-become-seo-expert-pakistan",
    title: "How to Become an SEO Expert in Pakistan",
    keyword: "how to become SEO expert",
    description: "A practical roadmap to become an SEO expert in Pakistan: the skills to learn in order, free tools, building a portfolio on real sites, getting your first clients or job, and how long it takes.",
    category: "Careers",
    icon: "rocket",
    accent: "green",
    answer: "To become an SEO expert in Pakistan, learn the fundamentals from Google’s own documentation, practise on a real website you control, master free tools like Search Console and Analytics, then build a portfolio by improving real sites for local businesses or as an intern. Most people reach junior job level in three to six months and genuine expertise after two to three years of real client work.",
    takeaways: [
      "Learn in order: fundamentals, technical basics, content, local SEO, links, analytics.",
      "A real website you control teaches more than any course alone.",
      "Free Google tools cover most of what you need at the start.",
      "A portfolio of real results matters more than certificates.",
      "Expertise comes from years of real client work and learning from failures.",
    ],
    body: [
      { type: "h2", text: "What an SEO expert really knows" },
      { type: "p", text: "Being an SEO expert means knowing how search engines find, understand and rank pages, and having the judgement to decide what to do first on a real site with real constraints. That judgement comes from practice. Courses help you start faster, but expertise is built on real websites." },
      { type: "h2", text: "The learning roadmap" },
      { type: "process", title: "Skills to learn, in order", steps: [
        { title: "Fundamentals", text: "How search works" },
        { title: "Technical", text: "Crawling, indexing, speed" },
        { title: "Content", text: "Intent, keywords, writing" },
        { title: "Local", text: "Business Profile, reviews" },
        { title: "Authority", text: "Links and mentions" },
        { title: "Analytics", text: "Measuring results" },
      ] },
      { type: "slides", title: "Your first six months", slides: [
        { title: "Month 1: fundamentals", points: ["Read Google’s SEO Starter Guide", "Learn how crawling and indexing work", "Set up your own practice website"] },
        { title: "Month 2: tools", points: ["Google Search Console", "Google Analytics 4", "PageSpeed Insights"] },
        { title: "Month 3: on-page and content", points: ["Keyword research from real data", "Writing pages that match intent", "Titles, headings and internal links"] },
        { title: "Month 4: local SEO", points: ["Google Business Profile", "Reviews and citations", "Help a local business for free or low cost"] },
        { title: "Month 5: technical and links", points: ["Technical audits", "Ethical link earning", "Structured data basics"] },
        { title: "Month 6: portfolio and jobs", points: ["Document results with screenshots", "Apply for internships and junior roles", "Start freelance projects"] },
      ] },
      { type: "h2", text: "Free tools to master" },
      { type: "checklist", title: "Tools every beginner should know", items: [
        "Google Search Console: queries, indexing and performance",
        "Google Analytics 4: traffic and conversions",
        "PageSpeed Insights: performance and Core Web Vitals",
        "Google Business Profile: local search",
        "A free crawler, such as the free tier of Screaming Frog",
        "Google Trends: seasonality and demand",
      ] },
      { type: "h2", text: "Building a portfolio" },
      { type: "p", text: "Employers and clients in Pakistan hire on evidence. Build case studies: a practice site you grew, a local shop whose Business Profile you fixed, a friend’s business whose enquiries increased. For each, show the problem, what you did, and the result with dated screenshots." },
      { type: "callout", tone: "tip", title: "Learn from real accounts", text: "Supervised work on live client accounts is the fastest way to build judgement. That is why our professional courses include a free internship on real accounts." },
      { type: "h2", text: "How long it takes" },
      { type: "bars", title: "Typical progression", items: [
        { label: "Basic understanding", value: 1, display: "1–2 months" },
        { label: "Junior job or first freelance clients", value: 2, display: "3–6 months" },
        { label: "Independent mid-level work", value: 4, display: "1–2 years" },
        { label: "Genuine expertise across many sites", value: 6, display: "2–3+ years" },
      ], note: "Indicative timelines with consistent practice; everyone’s pace differs." },
      { type: "video", title: "Your first SEO project, step by step", steps: [
        { title: "Pick a real site", text: "Use your own site or help a local business that agrees to let you practise." },
        { title: "Connect the tools", text: "Set up Search Console and Analytics and record the starting numbers." },
        { title: "Audit and plan", text: "Find the top five issues and decide what to fix first." },
        { title: "Make changes", text: "Fix issues, improve key pages and optimise the Business Profile, noting dates." },
        { title: "Write the case study", text: "After eight to twelve weeks, document what changed with screenshots." },
      ] },
      { type: "p", text: "Our [SEO course](/courses/seo/) in Scheme 3, Rawalpindi, and online, includes a free internship on live client accounts. Beginners can also start with the [AI basics course](/courses/ai-basics/) or the [complete digital marketing course](/courses/digital-marketing/)." },
      { type: "sources", items: [SRC.starter, SRC.helpful] },
    ],
    faqs: [
      { q: "How can I become an SEO expert in Pakistan?", a: "Learn the fundamentals from Google’s documentation, practise on a real website, master free tools like Search Console and Analytics, build a portfolio from real results and gain experience through internships, jobs or freelance work." },
      { q: "How long does it take to learn SEO?", a: "Basic understanding takes one to two months. Junior job level usually takes three to six months of practice, and genuine expertise two to three years of real client work." },
      { q: "Do I need a degree to become an SEO expert?", a: "No. Employers in Pakistan generally hire on portfolio and practical ability. Working English helps because most tools and documentation are in English." },
      { q: "Is SEO a good career in Pakistan?", a: "Yes. Local businesses, agencies and international clients all need SEO, and remote work for overseas clients is common." },
    ],
    related: [
      { label: "SEO course with a free internship", href: "/courses/seo/" },
      { label: "Complete digital marketing course", href: "/courses/digital-marketing/" },
      { label: "All courses and fees", href: "/courses/" },
    ],
  },
];
