import type { PostInput } from "@/lib/blog";
import { SRC } from "./part1";

export const PART2: PostInput[] = [
  /* ------------------------------------------------------------------ 2 */
  {
    slug: "hire-seo-expert-islamabad",
    title: "How to Hire a Professional SEO Expert in Islamabad",
    keyword: "hire SEO expert Islamabad",
    description: "A step-by-step process to hire an SEO expert in Islamabad: writing the brief, running a paid trial, the contract clauses that protect you and how to onboard them in the first 30 days.",
    category: "Hiring guide",
    icon: "user-check",
    accent: "blue",
    answer: "To hire an SEO expert in Islamabad, write a one-page brief with your goal and budget, invite three candidates to audit your site, check one reference each, then start with a 90-day engagement on monthly terms. Put ownership of content, accounts and data in writing, and give them Search Console and Analytics access on day one.",
    takeaways: [
      "Hiring goes better when you write the brief first: goal, area, budget and what a lead is worth to you.",
      "A paid or free audit is the best interview: it shows how someone thinks about your actual site.",
      "Contracts should be monthly, and you must own the website, content, Google Business Profile and analytics.",
      "Give access through user roles, never by sharing your passwords.",
      "The first 30 days should produce an audit, a 90-day plan and a reporting baseline, not instant rankings.",
    ],
    body: [
      { type: "h2", text: "Before you hire: write a one-page brief" },
      { type: "p", text: "Most hiring mistakes happen before the first call. Business owners ask for “SEO” and receive proposals for everything from blog posts to backlinks, with no way to compare them. A one-page brief fixes that. It forces you to decide what success looks like and lets candidates quote against the same scope." },
      { type: "checklist", title: "What your brief should contain", items: [
        "The business goal in one sentence, for example more appointment calls from F-10 and F-11",
        "Your main services and the areas or cities you actually serve",
        "What one enquiry or customer is worth to you, roughly",
        "A monthly budget range, including any paid ads budget",
        "Who will approve content and answer questions on your side",
        "Access you can provide: website admin, Search Console, Analytics, Google Business Profile",
      ] },
      { type: "h2", text: "The hiring process, step by step" },
      { type: "video", title: "Hiring an SEO expert in Islamabad", steps: [
        { title: "Publish the brief", text: "Send the same brief to three to five candidates: referrals, local agencies you found on Google Maps, and independent consultants with visible results." },
        { title: "Ask for an audit", text: "Request a short written audit of your site. Strong candidates name specific problems on your pages; weak ones send a template." },
        { title: "Interview the person doing the work", text: "Speak to whoever will actually handle your account weekly, not only the salesperson. Ask how they would spend the first month." },
        { title: "Check one reference", text: "Call a current client. Ask what changed in enquiries and how problems were communicated." },
        { title: "Agree a 90-day scope", text: "Sign monthly terms with a written 90-day plan, a reporting format and a review meeting at day 90." },
      ] },
      { type: "h2", text: "Where to find SEO experts in Islamabad" },
      { type: "p", text: "Referrals from businesses in a similar category are the most reliable source because you can see their results. After that, search Google Maps for SEO consultants near Blue Area, F-7 or I-8 and read reviews carefully: look for detailed reviews that mention outcomes, not one-line five-star ratings. LinkedIn is useful for checking an individual’s history. Freelance platforms work for one-off technical fixes but are a weaker fit for ongoing local SEO, which needs someone who understands Islamabad’s sector-based search behaviour." },
      { type: "bars", title: "Where reliable SEO hires usually come from", items: [
        { label: "Referral from a similar business", value: 5, display: "Best" },
        { label: "Google Maps with detailed reviews", value: 4, display: "Good" },
        { label: "LinkedIn track record", value: 3, display: "Good" },
        { label: "Freelance marketplaces", value: 2, display: "Mixed" },
        { label: "Cold calls and spam emails", value: 1, display: "Avoid" },
      ], note: "A qualitative ranking from our experience of what tends to produce good outcomes, not survey data." },
      { type: "h2", text: "Contract terms that protect you" },
      { type: "p", text: "SEO contracts in Pakistan are often vague, which leads to disputes when the relationship ends. Insist on these points in writing before any work starts." },
      { type: "table", caption: "Clauses to include", head: ["Clause", "Why it matters"], rows: [
        ["Monthly terms, 30 days notice", "You can stop if the work is not producing results"],
        ["You own all content and code", "Pages written for you stay with you when you leave"],
        ["Accounts in your name", "Google Business Profile, Search Console and Analytics must belong to your business email"],
        ["No paid link schemes or fake reviews", "Protects you from penalties caused by someone else’s shortcuts"],
        ["Defined monthly report", "Agree the metrics now: rankings, enquiries, calls, WhatsApp and cost per lead"],
        ["Named account owner", "You know exactly who is responsible each week"],
      ] },
      { type: "callout", tone: "warn", title: "Never share passwords", text: "Add your SEO expert as a user in Search Console, Analytics, your Google Business Profile and your website admin. Shared passwords are a security risk and make it hard to remove access later." },
      { type: "h2", text: "What the first 30 days should look like" },
      { type: "slides", title: "A healthy first month with a new SEO expert", slides: [
        { title: "Week 1: access and audit", points: ["User access set up for every tool", "Full technical and content audit", "Competitor review for your main keywords"] },
        { title: "Week 2: the plan", points: ["A written 90-day plan with priorities", "Keyword map tied to your services and areas", "Agreement on what gets reported monthly"] },
        { title: "Week 3: quick wins", points: ["Fix critical technical issues", "Complete and correct the Google Business Profile", "Improve titles and descriptions on key pages"] },
        { title: "Week 4: baseline report", points: ["Rankings, traffic and enquiries recorded as a starting point", "Call and WhatsApp tracking in place", "Next month’s priorities confirmed"] },
      ] },
      { type: "p", text: "Expect visible ranking movement for local terms in 30 to 60 days and meaningful growth in enquiries around month three. If you see nothing but activity reports after 90 days, that is the moment to review, which is exactly why the 90-day checkpoint matters." },
      { type: "h2", text: "Hiring MrSEO.pk" },
      { type: "p", text: "If you want to include us in your shortlist, send your brief or just your URL. You get a written audit within 24 hours and a 90-day plan on monthly terms, delivered by Syed Mudassir Shah personally. [Request the audit here](/contact/)." },
      { type: "sources", items: [SRC.needSeo, SRC.starter, SRC.spam] },
    ],
    faqs: [
      { q: "How do I hire an SEO expert in Islamabad?", a: "Write a short brief with your goal and budget, ask three candidates to audit your site, interview the person who will do the work, check one reference, and start with a 90-day engagement on monthly terms." },
      { q: "What access should I give a new SEO expert?", a: "User access, not passwords, to Google Search Console, Google Analytics, your Google Business Profile and your website admin. Keep ownership of every account under your business email." },
      { q: "Should I sign a 12-month SEO contract?", a: "Usually not at the start. A 90-day engagement on monthly terms lets you judge real results before committing. Long lock-in contracts mostly protect the provider." },
      { q: "What should I expect in the first month?", a: "An audit, a written 90-day plan, fixes to critical technical problems, a completed Google Business Profile and a baseline report. Big ranking gains in month one are unusual." },
    ],
    related: [
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "Local SEO services", href: "/services/local-seo/" },
      { label: "Request a free SEO audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 4 */
  {
    slug: "seo-specialist-islamabad",
    title: "SEO Specialist in Islamabad: Skills, Services and Benefits",
    keyword: "SEO specialist Islamabad",
    description: "What an SEO specialist in Islamabad actually does: the core skills to look for, the services they deliver, the tools they use and the business benefits you should expect.",
    category: "SEO skills",
    icon: "wrench",
    accent: "teal",
    answer: "An SEO specialist in Islamabad improves how a business appears in Google and AI search by fixing technical issues, optimising pages, building local visibility and earning links. The core skills are technical auditing, keyword research, content optimisation, Google Business Profile management and analytics. The benefit is a steady flow of qualified enquiries without paying for every click.",
    takeaways: [
      "An SEO specialist combines technical, content, local and analytics skills; few people are strong in all four.",
      "In Islamabad, local SEO and sector-level targeting matter more than chasing national keywords.",
      "Services should map to business outcomes: calls, bookings and enquiries.",
      "The tools matter less than the person’s judgement about what to fix first.",
      "Benefits compound: pages that rank keep producing leads long after the work is done.",
    ],
    body: [
      { type: "h2", text: "What an SEO specialist does" },
      { type: "p", text: "An **SEO specialist** is someone who makes a website the result search engines prefer to show for the searches that matter to a business. In practice that means four areas of work: making the site technically easy for Google to crawl and understand, building pages that match what people actually search, earning credibility through links and reviews, and measuring the effect on real enquiries." },
      { type: "process", title: "The four pillars of SEO work", steps: [
        { title: "Technical", text: "Crawling, speed, mobile, structure" },
        { title: "On-page", text: "Keywords, titles, content, schema" },
        { title: "Off-page", text: "Links, citations, reviews, mentions" },
        { title: "Measurement", text: "Rankings, leads, cost per enquiry" },
      ] },
      { type: "h2", text: "The skills to look for" },
      { type: "p", text: "When you assess an SEO specialist in Islamabad, look for evidence of each skill below rather than a list of certificates. Ask them to show you how they would apply it to your site." },
      { type: "table", caption: "Core SEO specialist skills", head: ["Skill", "What good looks like"], rows: [
        ["Technical auditing", "Finds crawl, indexing, speed and mobile problems and explains their impact in plain language"],
        ["Keyword research", "Uses your own Search Console data and real buyer language, including Roman Urdu where relevant"],
        ["Content optimisation", "Improves existing pages before writing new ones; writes for people first"],
        ["Local SEO", "Manages Google Business Profile categories, services, photos, reviews and area pages"],
        ["Link earning", "Gets links from directories, associations and partners without paid networks"],
        ["Analytics", "Tracks calls, WhatsApp clicks and forms, not only traffic"],
        ["Communication", "Writes clear monthly reports and admits when something is not working"],
      ] },
      { type: "h2", text: "Services an SEO specialist delivers" },
      { type: "slides", title: "Typical SEO specialist services", slides: [
        { title: "Audit and strategy", points: ["Technical and content audit", "Competitor analysis", "A prioritised 90-day roadmap"] },
        { title: "On-page optimisation", points: ["Titles, descriptions and headings", "Internal linking between services and areas", "Schema markup for the business, services and FAQs"] },
        { title: "Local SEO", points: ["Google Business Profile setup and management", "Citations on Pakistani directories", "Area and sector pages for Islamabad"] },
        { title: "Content", points: ["Service pages that answer buyer questions", "Pricing and comparison pages", "FAQ content written for AI answers"] },
        { title: "Reporting", points: ["Weekly rank tracking", "Monthly enquiry reports", "Recommendations for the next month"] },
      ] },
      { type: "callout", tone: "note", title: "Specialist or generalist?", text: "Some specialists focus on one area, such as technical SEO or local SEO. That is useful for large sites or specific problems. Most small and mid-sized Islamabad businesses get better value from one person who can cover all four pillars and coordinate the work." },
      { type: "h2", text: "Tools an SEO specialist uses" },
      { type: "p", text: "Free Google tools do most of the heavy lifting: **Search Console** for queries and indexing, **Google Analytics 4** for behaviour and conversions, **PageSpeed Insights** for performance, and the **Google Business Profile** dashboard for local visibility. Paid tools such as Ahrefs, Semrush or Screaming Frog add competitor and crawl data. Be cautious of anyone who relies only on paid keyword volumes; Pakistani data in these tools is often incomplete." },
      { type: "h2", text: "Benefits for an Islamabad business" },
      { type: "stats", title: "What good SEO work changes", items: [
        { value: "24/7", label: "Pages keep attracting enquiries after the work is done" },
        { value: "Lower", label: "Cost per lead over time compared with paying per click" },
        { value: "Trust", label: "Buyers in the capital research before calling; ranking pages build credibility" },
        { value: "Data", label: "Search Console shows exactly what customers are looking for" },
      ] },
      { type: "p", text: "The biggest benefit is compounding. A well-built service page that ranks for “family dentist F-10” or “corporate lawyer Blue Area” keeps producing enquiries month after month. Paid ads stop the moment you stop paying." },
      { type: "video", title: "How a specialist approaches a new Islamabad site", steps: [
        { title: "Read the data first", text: "Check Search Console for the queries already bringing impressions, and Analytics for the pages that produce enquiries." },
        { title: "Fix what blocks Google", text: "Resolve indexing errors, duplicate pages, slow mobile pages and broken internal links before writing anything new." },
        { title: "Strengthen the money pages", text: "Improve the service and location pages closest to a sale, adding prices, FAQs and clear calls to action." },
        { title: "Build local visibility", text: "Complete the Google Business Profile, add the right categories and services, and start a review process." },
        { title: "Measure and expand", text: "Track enquiries monthly and widen into nearby sectors and related services once the core pages rank." },
      ] },
      { type: "p", text: "If you want a specialist who covers all four pillars and reports on enquiries, read about our [SEO services](/services/seo/) or [request a free audit](/contact/)." },
      { type: "sources", items: [SRC.starter, SRC.helpful, SRC.local] },
    ],
    faqs: [
      { q: "What does an SEO specialist do?", a: "They improve a website’s visibility in Google and AI search through technical fixes, page optimisation, local SEO, link earning and measurement, with the goal of producing more qualified enquiries." },
      { q: "What skills should an SEO specialist in Islamabad have?", a: "Technical auditing, keyword research using real search data, content optimisation, Google Business Profile management, ethical link earning, analytics and clear communication." },
      { q: "Is an SEO specialist different from an SEO expert?", a: "The terms are used interchangeably. Some people use specialist for someone focused on one area such as technical or local SEO, and expert for someone who covers strategy across all areas." },
      { q: "Which tools do SEO specialists use?", a: "Google Search Console, Google Analytics 4, PageSpeed Insights and Google Business Profile, often alongside paid tools like Ahrefs, Semrush or Screaming Frog for competitor and crawl data." },
    ],
    related: [
      { label: "SEO services in Pakistan", href: "/services/seo/" },
      { label: "SEO course with a free internship", href: "/courses/seo/" },
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
    ],
  },

  /* ------------------------------------------------------------------ 5 */
  {
    slug: "seo-consultant-islamabad",
    title: "How to Choose the Right SEO Consultant in Islamabad",
    keyword: "SEO consultant Islamabad",
    description: "When you need an SEO consultant rather than an agency, how consulting engagements work in Islamabad, what to expect from strategy sessions and how to judge whether the advice is any good.",
    category: "Hiring guide",
    icon: "messages-square",
    accent: "violet",
    answer: "Choose an SEO consultant in Islamabad when you need strategy and judgement more than hands-on labour: deciding priorities, auditing an agency, planning a migration or training an in-house team. The right consultant asks about your business model first, gives specific written recommendations, explains trade-offs and is happy for your own team to do the implementation.",
    takeaways: [
      "A consultant sells judgement; an agency sells execution. Many businesses need the first more than the second.",
      "Good consulting engagements end with a written plan your team or developer can follow.",
      "Consultants are ideal for audits, migrations, agency oversight and in-house training.",
      "Judge advice by how specific it is to your site, not by how impressive it sounds.",
      "Retainers should be tied to decisions and reviews, not to hours of activity.",
    ],
    body: [
      { type: "h2", text: "Consultant, agency or freelancer: what is the difference?" },
      { type: "p", text: "An **SEO consultant** advises on what to do and why. An agency usually does the work for you. A freelancer often does specific tasks you assign. The lines blur, but the distinction matters when you decide who to hire. If your business already has a developer and a content writer, paying an agency to duplicate them is waste. What you may lack is someone who can tell them what to work on first." },
      { type: "compare", title: "Consultant versus agency", left: { label: "Typical agency model", items: [
        "Sells a monthly package of deliverables",
        "Work done by an account team you rarely meet",
        "Success measured in tasks completed",
        "Harder to leave without losing the work",
      ] }, right: { label: "Consultant model", items: [
        "Sells judgement and a clear plan",
        "You work directly with the expert",
        "Success measured in decisions that move results",
        "Your team keeps the knowledge and the work",
      ] } },
      { type: "h2", text: "When an Islamabad business should hire a consultant" },
      { type: "list", items: [
        "**You have an in-house team** and need direction rather than more hands.",
        "**You are paying an agency** and are not sure the work is producing results.",
        "**You are redesigning or migrating** your website and cannot afford to lose rankings.",
        "**Your traffic dropped** after a Google update and you need a diagnosis.",
        "**You are entering a new market**, such as targeting overseas Pakistanis or a new city.",
      ] },
      { type: "h2", text: "How consulting engagements usually work" },
      { type: "slides", title: "Common SEO consulting formats", slides: [
        { title: "One-off audit", points: ["A detailed written audit of your site", "A prioritised fix list with effort and impact", "A walkthrough call with your team"] },
        { title: "Strategy retainer", points: ["Monthly or fortnightly strategy sessions", "Review of what your team shipped", "Updated priorities for the next period"] },
        { title: "Migration support", points: ["Redirect mapping before launch", "Pre-launch checks on staging", "Monitoring for the first eight weeks"] },
        { title: "Agency oversight", points: ["Review of the agency’s reports and work", "Questions to ask them", "An honest view on whether to continue"] },
        { title: "Team training", points: ["Workshops for writers and developers", "Checklists and processes", "Follow-up reviews"] },
      ] },
      { type: "h2", text: "How to judge whether a consultant’s advice is good" },
      { type: "p", text: "Generic advice is the easiest thing in SEO to produce and the least valuable. Good advice is specific to your site, explains the reasoning, ranks recommendations by impact, and admits uncertainty where it exists." },
      { type: "checklist", title: "Signs of high-quality SEO consulting", items: [
        "Recommendations name your actual pages and queries",
        "Every recommendation has a reason and an expected effect",
        "Priorities are ranked; you know what to do first",
        "Trade-offs are explained, for example speed versus design",
        "They ask about margins, sales process and seasonality",
        "They are comfortable saying “I don’t know yet, let’s test it”",
      ] },
      { type: "callout", tone: "tip", title: "Ask for a sample", text: "Before a retainer, ask the consultant to review one important page on your site and send three recommendations. You will learn more from that than from any proposal deck." },
      { type: "video", title: "Running a productive first consultation", steps: [
        { title: "Share context in advance", text: "Send your goals, your main services, your best customers and any recent traffic changes before the call." },
        { title: "Give read-only data access", text: "Add the consultant to Search Console and Analytics so the conversation is grounded in your real numbers." },
        { title: "Agree the decision you need", text: "Frame the session around a decision, for example whether to rebuild the site or fix it, or which city to target first." },
        { title: "Get it in writing", text: "Ask for a short written summary with priorities and owners within 48 hours of the call." },
        { title: "Book the review", text: "Schedule a follow-up four to six weeks later to check what was implemented and what changed." },
      ] },
      { type: "h2", text: "Pricing consulting work fairly" },
      { type: "p", text: "Consultants in Islamabad typically charge for a defined audit, a monthly strategy retainer, or hourly sessions. Prefer fixed-scope work where possible, so you pay for outcomes such as a completed migration plan rather than open-ended hours. The more clearly you define the decision you need help with, the easier it is to quote accurately." },
      { type: "p", text: "Syed Mudassir Shah works as a consultant as well as running full engagements, and is happy to work alongside your developer or agency. [Talk to him directly](/contact/)." },
      { type: "sources", items: [SRC.needSeo, SRC.helpful] },
    ],
    faqs: [
      { q: "What does an SEO consultant do?", a: "An SEO consultant diagnoses problems, sets priorities and gives specific written recommendations. Your own team, developer or agency usually carries out the work." },
      { q: "Is an SEO consultant cheaper than an agency?", a: "Often yes, because you pay for expertise rather than a full delivery team. It works best when you already have people who can implement the recommendations." },
      { q: "Can an SEO consultant review my current agency?", a: "Yes. Agency oversight is a common engagement: the consultant reviews reports and deliverables, checks methods for risk and gives an honest view on whether the work is producing results." },
      { q: "How long is a typical SEO consulting engagement?", a: "A one-off audit takes one to three weeks. Strategy retainers commonly run month to month, with a review every quarter." },
    ],
    related: [
      { label: "About Syed Mudassir Shah", href: "/about/" },
      { label: "SEO services in Pakistan", href: "/services/seo/" },
      { label: "Book a consultation", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 6 */
  {
    slug: "freelance-seo-expert-islamabad",
    title: "Freelance SEO Expert in Islamabad: Complete Hiring Guide",
    keyword: "freelance SEO expert Islamabad",
    description: "How to hire a freelance SEO expert in Islamabad: when a freelancer is the right choice, how to vet them, how to structure payment and how to avoid the common risks.",
    category: "Hiring guide",
    icon: "laptop",
    accent: "amber",
    answer: "A freelance SEO expert in Islamabad is a good choice for defined projects such as an audit, a technical fix list, Google Business Profile setup or a content sprint. Vet them with a small paid task, pay by milestone rather than upfront, keep every account in your own name, and agree weekly updates so the work never disappears into silence.",
    takeaways: [
      "Freelancers are best for clearly scoped projects; ongoing strategy needs more continuity.",
      "A small paid test task is the most reliable way to vet a freelancer.",
      "Pay by milestone, with the final payment after you have checked the work.",
      "Keep ownership of your website, profiles and analytics at all times.",
      "Agree availability and a weekly update in writing; disappearing is the most common freelancer risk.",
    ],
    body: [
      { type: "h2", text: "When a freelancer is the right choice" },
      { type: "p", text: "Islamabad and Rawalpindi have a large pool of capable freelancers, many of them trained on international projects. Hiring one can be excellent value, provided the work suits the model. Freelancers shine on **projects with a clear finish line**. They are a weaker fit for ongoing local SEO, where results depend on months of consistent attention and someone has to own the overall plan." },
      { type: "compare", title: "Good and poor fits for a freelance SEO expert", left: { label: "Poor fit", items: [
        "Owning your whole marketing strategy",
        "Ongoing local SEO with no oversight",
        "Urgent recovery from a Google penalty",
        "Work that needs daily communication with your team",
      ] }, right: { label: "Good fit", items: [
        "A one-off technical SEO audit",
        "Google Business Profile setup and cleanup",
        "Fixing a defined list of on-page issues",
        "A content sprint of service or FAQ pages",
      ] } },
      { type: "h2", text: "How to vet a freelance SEO expert" },
      { type: "p", text: "Profiles on freelance platforms can be polished and still misleading. Ratings often reflect friendliness and speed rather than SEO outcomes. Use this sequence instead." },
      { type: "video", title: "Vetting a freelancer in a week", steps: [
        { title: "Review real work", text: "Ask for two live sites they have worked on and what they changed. Check those sites in Google yourself." },
        { title: "Set a paid test", text: "Pay for a small, real task: audit one key page, or set up schema on your home page. Judge the quality and the communication." },
        { title: "Ask how they would measure it", text: "A good freelancer talks about rankings, clicks and enquiries. A weak one talks only about tasks completed." },
        { title: "Confirm availability", text: "Agree hours, response times and a weekly update day. Many freelancers juggle several clients and time zones." },
        { title: "Write the scope", text: "List deliverables, deadlines and payment milestones in a short written agreement before the main project starts." },
      ] },
      { type: "h2", text: "Structuring payment safely" },
      { type: "table", caption: "A milestone structure for a typical project", head: ["Milestone", "Deliverable", "Payment"], rows: [
        ["Start", "Agreed scope and access set up", "20–30%"],
        ["Midpoint", "Audit or first half of fixes delivered", "30–40%"],
        ["Completion", "All work delivered and checked by you", "Remaining balance"],
      ] },
      { type: "callout", tone: "warn", title: "Keep everything in your name", text: "Your domain, hosting, Google Business Profile, Search Console and Analytics should all sit under your own business email. Add the freelancer as a user and remove access when the project ends." },
      { type: "h2", text: "Risks to manage" },
      { type: "slides", title: "The five common freelancer risks and how to handle them", slides: [
        { title: "Disappearing mid-project", points: ["Agree a weekly update day", "Pay by milestone, not upfront", "Keep a written list of what is done"] },
        { title: "Black-hat shortcuts", points: ["Ban paid link packages in writing", "Ask for a list of every link built", "Check new links in Search Console"] },
        { title: "Template work", points: ["Insist on site-specific findings", "Ask for before-and-after screenshots", "Spot-check a few changes yourself"] },
        { title: "Access left open", points: ["Use user roles, never shared passwords", "Remove access when the project ends", "Change any password that was shared"] },
        { title: "No handover", points: ["Ask for a short handover document", "List every change made and why", "Note what should happen next"] },
      ] },
      { type: "h2", text: "Freelancer, consultant or agency?" },
      { type: "bars", title: "Which option suits which need", items: [
        { label: "Defined one-off project", value: 5, display: "Freelancer" },
        { label: "Strategy and oversight", value: 4, display: "Consultant" },
        { label: "Full ongoing delivery", value: 3, display: "Agency or consultant" },
      ], note: "A simple guide to matching the hiring model to the job." },
      { type: "p", text: "Many Islamabad businesses combine them: a consultant sets the plan and checks quality, while freelancers deliver specific tasks. If you would like help structuring that, or a second opinion on a freelancer’s work, [get in touch](/contact/). Students who want to freelance in SEO can also look at our [freelancing course](/courses/freelancing/)." },
      { type: "sources", items: [SRC.spam, SRC.starter] },
    ],
    faqs: [
      { q: "Is it safe to hire a freelance SEO expert in Islamabad?", a: "Yes, if you scope the work clearly, vet them with a small paid task, pay by milestone and keep every account in your own name. Most problems come from vague scope and upfront payment." },
      { q: "What should a freelance SEO expert deliver?", a: "Whatever is in the written scope, plus a short handover note listing every change made, why it was made and what should happen next." },
      { q: "Can a freelancer do ongoing local SEO?", a: "Some can, but ongoing local SEO needs consistent attention over months. If you hire a freelancer for it, agree weekly updates and a monthly report tied to enquiries." },
      { q: "How do I check a freelancer’s past SEO work?", a: "Ask for live sites they worked on, search for those sites’ keywords yourself, and ask what specifically they changed. Ratings on platforms alone are not reliable evidence." },
    ],
    related: [
      { label: "Freelancing starter course", href: "/courses/freelancing/" },
      { label: "SEO services in Pakistan", href: "/services/seo/" },
      { label: "Get a second opinion on your SEO", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 7 */
  {
    slug: "seo-expert-for-small-business-islamabad",
    title: "SEO Expert in Islamabad for Small Businesses",
    keyword: "SEO expert for small business",
    description: "How small businesses in Islamabad and Rawalpindi can get real results from SEO on a limited budget: what to prioritise, what to skip, and how to work with an SEO expert efficiently.",
    category: "Small business",
    icon: "store",
    accent: "green",
    answer: "A small business in Islamabad should start SEO with three things: a complete Google Business Profile with a steady flow of genuine reviews, one strong page for each main service, and accurate tracking of calls and WhatsApp enquiries. An SEO expert for small business should focus your limited budget on the searches closest to a sale, not on blogging or national keywords.",
    takeaways: [
      "For most small businesses, the Google Business Profile produces more enquiries than the website at first.",
      "One strong page per service beats twenty thin blog posts.",
      "Target your actual service area: your sector, nearby sectors and the twin city.",
      "Track calls and WhatsApp clicks from day one, or you cannot tell what is working.",
      "Small budgets work best with a focused 90-day plan and clear monthly priorities.",
    ],
    body: [
      { type: "h2", text: "Why SEO works differently for small businesses" },
      { type: "p", text: "A salon in F-7, a tuition centre in G-11, a plumber in Bahria Town or an accountant in I-8 does not need to rank for “best salon in Pakistan”. Their customers are nearby, they search on mobile, and they usually contact the business within minutes of searching. That makes small business SEO in Islamabad a **local, mobile and conversion-focused** discipline. The budget should follow that." },
      { type: "stats", title: "Where small-business enquiries come from", items: [
        { value: "Maps", label: "The local pack and Google Maps drive most first contacts" },
        { value: "Mobile", label: "Most local searches happen on a phone" },
        { value: "Near me", label: "Proximity is a major factor in local results" },
        { value: "WhatsApp", label: "The most common way Pakistani customers make contact" },
      ] },
      { type: "h2", text: "The three priorities for a limited budget" },
      { type: "process", title: "Small business SEO in order of impact", steps: [
        { title: "Google Business Profile", text: "Categories, services, photos, reviews" },
        { title: "Service pages", text: "One strong page per main service" },
        { title: "Tracking", text: "Calls, WhatsApp and forms measured" },
        { title: "Local signals", text: "Citations, area content, links" },
      ] },
      { type: "h3", text: "1. A complete Google Business Profile" },
      { type: "p", text: "Choose the most accurate primary category, add every service you offer, upload real photos of your premises and team, set correct hours including Friday prayer adjustments, and publish updates. Most importantly, build a simple habit of asking happy customers for a review, for example with a QR code at the counter or a WhatsApp message after the job." },
      { type: "h3", text: "2. One strong page for each main service" },
      { type: "p", text: "Each service page should answer what a buyer actually wants to know: what is included, roughly what it costs, how long it takes, which areas you cover and how to contact you. A page like this ranks better and converts better than a generic “Services” page listing everything in one paragraph." },
      { type: "h3", text: "3. Tracking that counts enquiries" },
      { type: "p", text: "Set up click tracking on your phone number and WhatsApp button, and connect Google Analytics 4 to your forms. Without this, you will judge SEO on gut feeling." },
      { type: "h2", text: "What small businesses should skip at first" },
      { type: "compare", title: "Where small budgets get wasted", left: { label: "Skip for now", items: [
        "Daily blog posts on general topics",
        "Ranking for national keywords",
        "Expensive backlink packages",
        "A full website redesign before fixing basics",
      ] }, right: { label: "Do this instead", items: [
        "Answer your customers’ real questions on service pages",
        "Target your sector, nearby sectors and the twin city",
        "Earn local links from associations and partners",
        "Fix speed, mobile layout and contact buttons first",
      ] } },
      { type: "h2", text: "Working with an SEO expert on a small budget" },
      { type: "slides", title: "Getting the most from a small SEO budget", slides: [
        { title: "Start with an audit", points: ["Free or fixed-price audit first", "Agree the top five priorities", "Skip anything that does not affect enquiries"] },
        { title: "Do some work yourself", points: ["Collect reviews and photos", "Answer customer questions in writing", "Approve content quickly"] },
        { title: "Review monthly", points: ["Check enquiries, not just rankings", "Drop tasks that are not working", "Add one new service page a month"] },
      ] },
      { type: "video", title: "A 90-day SEO plan for a small Islamabad business", steps: [
        { title: "Days 1 to 14", text: "Audit, fix critical technical problems, complete the Google Business Profile and install call and WhatsApp tracking." },
        { title: "Days 15 to 45", text: "Rewrite or create a strong page for each main service, with prices, FAQs and a clear WhatsApp button." },
        { title: "Days 46 to 75", text: "Build local citations, ask partners and associations for links, and start a weekly review routine." },
        { title: "Days 76 to 90", text: "Review enquiries by source, keep what works, and plan the next 90 days around the best-performing services." },
      ] },
      { type: "p", text: "MrSEO.pk works with many small Islamabad and Rawalpindi businesses on monthly terms with no lock-in. Our [local SEO service](/services/local-seo/) is usually the best starting point, and the [free audit](/contact/) will tell you honestly whether SEO is worth your budget right now." },
      { type: "sources", items: [SRC.gbp, SRC.local, SRC.starter] },
    ],
    faqs: [
      { q: "Is SEO worth it for a small business in Islamabad?", a: "Usually yes, if customers search for your service locally. Start with the Google Business Profile, strong service pages and enquiry tracking, and judge results after 90 days." },
      { q: "What should a small business do first for SEO?", a: "Complete and optimise the Google Business Profile, then create one strong page for each main service, and set up tracking for calls and WhatsApp clicks." },
      { q: "Do small businesses need a blog for SEO?", a: "Not at first. Service pages that answer real customer questions usually produce more enquiries than general blog posts. Add content once the core pages are strong." },
      { q: "How can a small business get more Google reviews?", a: "Ask every satisfied customer at the right moment, make it easy with a direct review link or QR code, and reply to every review. Never buy reviews or offer rewards for positive ones." },
    ],
    related: [
      { label: "Local SEO services", href: "/services/local-seo/" },
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "SEO Expert in Rawalpindi", href: "/seo-expert/seo-expert-rawalpindi/" },
    ],
  },
];
