import type { Deep } from "./deep";

export const DEEP_E: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 22 dental */
  "dental-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for dental clinics" },
      { type: "p", text: "Dental searches in Pakistan fall into clear groups: urgent problems, specific treatments, cosmetic procedures, children’s dentistry and price questions. Each group needs a different page and a different tone. Urgent searches need reassurance and fast contact; cosmetic searches need before-and-after evidence and clear pricing; children’s dentistry needs a gentle, family-friendly approach." },
      { type: "table", caption: "Dental search groups and the pages that serve them", head: ["Search group", "Examples", "Best page"], rows: [
        ["Urgent", "tooth pain dentist near me, emergency dentist F-11", "Business Profile and an emergency care page"],
        ["Treatment", "root canal Islamabad, tooth extraction Rawalpindi", "Treatment pages"],
        ["Cosmetic", "teeth whitening price, veneers Islamabad", "Cosmetic treatment pages with photos"],
        ["Orthodontic", "braces price Pakistan, clear aligners Islamabad", "Orthodontics page"],
        ["Children", "child dentist F-10, kids dental check-up", "Paediatric dentistry page"],
        ["Cost", "dental implant cost Islamabad", "Price sections on treatment pages"],
      ] },
      { type: "p", text: "Your Search Console data will show which of these groups already bring impressions. Strengthen those first, then fill the gaps with pages for treatments you offer but do not yet rank for. Many clinics discover they have no dedicated page for their most profitable treatment, simply because it was always listed in a long paragraph on the services page." },
      { type: "h2", text: "Building trust before the first visit" },
      { type: "p", text: "Dental anxiety is common, and many patients delay treatment because they fear pain or cost. A clinic website that addresses these fears directly earns trust and bookings. Explain how you manage pain, what modern equipment you use, how long appointments take and what patients can expect at the first visit. Introduce the dentists with friendly photos and short personal notes alongside their qualifications." },
      { type: "checklist", title: "Trust builders on a dental website", items: [
        "Dentist profiles with photos, qualifications and PM&DC registration",
        "A clear explanation of what happens at the first appointment",
        "Information on pain management and sedation if offered",
        "Photos of the clinic, equipment and sterilisation area",
        "Price ranges and payment options",
        "Genuine reviews and, with consent, before-and-after photos",
      ] },
      { type: "h2", text: "Reviews that mention treatments" },
      { type: "p", text: "Reviews that mention a specific treatment and dentist are especially valuable. They reassure future patients considering the same treatment and add relevant language to your profile. Encourage this naturally: after a successful implant or braces treatment, ask the patient if they would be willing to share their experience, and make it easy with a direct review link sent on WhatsApp." },
      { type: "callout", tone: "warn", title: "Never discuss treatment in replies", text: "Even if a patient mentions their treatment in a review, do not confirm or discuss it in your reply. Thank them in general terms and invite them to contact the clinic directly with any questions." },
      { type: "h2", text: "Dental clinics with several branches" },
      { type: "p", text: "Dental groups with branches in Islamabad and Rawalpindi need a profile and a location page for each staffed branch, with the dentists, timings and services available there. Make it easy for patients to choose the nearest branch, and avoid duplicating the same content across branch pages; each should describe its own team, facilities and location." },
      { type: "h2", text: "Paid search alongside dental SEO" },
      { type: "p", text: "Google Ads can fill appointment gaps quickly, especially for high-value treatments such as implants and orthodontics or for new clinics still building organic visibility. Run ads to the same detailed treatment pages you build for SEO, so both channels benefit from strong content. Track calls and WhatsApp messages from each channel, and shift budget towards whichever produces bookings at the lowest cost." },
      { type: "bars", title: "Typical dental marketing mix", items: [
        { label: "Google Business Profile", value: 5, display: "Foundation" },
        { label: "Treatment pages (SEO)", value: 4, display: "Long-term" },
        { label: "Google Ads for high-value treatments", value: 3, display: "Fast fill" },
        { label: "Social media for cosmetic work", value: 3, display: "Awareness" },
      ], note: "A common balance for clinics; adjust to your treatments and budget." },
      { type: "h2", text: "Measuring dental SEO" },
      { type: "p", text: "The key measure is new patient bookings by treatment. Track calls and WhatsApp messages from the website and Business Profile, ask new patients how they found you, and note which treatment they came for. Over a few months, this shows which pages and channels bring your most valuable patients, and where to invest next." },
    ],
    faqs: [
      { q: "What keywords should a dental clinic target?", a: "Urgent care, specific treatments, cosmetic procedures, orthodontics, children’s dentistry and cost questions, each mapped to a dedicated page, starting with groups that already bring impressions in Search Console." },
      { q: "Should dental clinics run Google Ads as well as SEO?", a: "Often yes, especially for high-value treatments or new clinics. Point ads to the same detailed treatment pages built for SEO and track bookings from each channel." },
      { q: "How can dental websites reduce patient anxiety?", a: "Explain pain management, the first appointment, modern equipment and sterilisation, introduce the dentists personally and share clear price ranges." },
    ],
  },

  /* ------------------------------------------------------------------ 23 lawyer */
  "lawyer-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for law firms" },
      { type: "p", text: "Legal searches in Pakistan combine a practice area, a location and often a specific situation. People search “property lawyer Islamabad”, “how to file khula in Pakistan”, “company registration lawyer Rawalpindi” or “bail procedure Pakistan”. Mapping these to practice area pages and informational guides is the foundation of legal SEO." },
      { type: "table", caption: "Legal search patterns", head: ["Pattern", "Example", "Page type"], rows: [
        ["Practice + city", "family lawyer Islamabad", "Practice area page"],
        ["Process question", "how to register a company in Pakistan", "Guide"],
        ["Document question", "documents required for property transfer", "Guide or checklist"],
        ["Cost question", "lawyer fee for divorce case Pakistan", "Practice page section on fees"],
        ["Court or procedure", "family court process Islamabad", "Guide"],
      ] },
      { type: "p", text: "Fee questions deserve particular thought. Many firms hesitate to publish fees, and professional rules may affect how fees are presented. Even without specific figures, explaining how fees are structured, for example consultation fees, fixed fees for certain matters or stage-based fees, helps clients understand what to expect and reduces uncertainty." },
      { type: "h2", text: "Showing expertise without self-promotion" },
      { type: "p", text: "Within professional rules, the most effective legal content demonstrates expertise rather than claiming it. A clear explanation of a complex process shows competence far more convincingly than any statement about being the best. Detailed, accurate guides also earn links from news sites, forums and educational resources, which strengthens the firm’s authority in search." },
      { type: "checklist", title: "Ways to demonstrate expertise", items: [
        "Explain processes clearly and accurately, step by step",
        "Publish updates when relevant laws or procedures change",
        "Answer common questions in plain language",
        "Show lawyers’ qualifications, experience and areas of focus",
        "Contribute expert commentary to news and legal publications",
        "Speak at professional events and link to recordings or summaries",
      ] },
      { type: "h2", text: "Handling enquiries and confidentiality" },
      { type: "p", text: "Legal enquiries often contain sensitive personal information. Contact forms should ask only for what is needed to arrange a consultation, explain how information will be handled, and avoid encouraging people to share detailed case facts before a lawyer has responded. WhatsApp is convenient, but firms should be clear about which communications are confidential and how they will be stored." },
      { type: "callout", tone: "note", title: "Keep forms simple", text: "Ask for name, contact details, the practice area and a brief description. Detailed case information is better discussed in the consultation itself." },
      { type: "h2", text: "Local visibility for law firms" },
      { type: "p", text: "Clients often prefer lawyers near the courts or their workplace, such as offices close to the district courts or in Blue Area. A complete Business Profile with the correct legal category, accurate office location, real office photos and practice areas listed as services helps the firm appear for local searches. Each office of a multi-office firm should have its own profile and page." },
      { type: "h2", text: "Measuring legal SEO" },
      { type: "stats", title: "What law firms should track", items: [
        { value: "Enquiries", label: "Consultation requests by practice area" },
        { value: "Calls", label: "Calls from the Business Profile and website" },
        { value: "Guides", label: "Visits to informational guides" },
        { value: "Matters", label: "Enquiries that became client matters" },
      ] },
      { type: "p", text: "Over time, firms usually find that a handful of detailed guides attract most of their qualified enquiries. Those guides deserve regular updates and should link clearly to the relevant practice area and contact options." },
    ],
    faqs: [
      { q: "Can law firms publish their fees online?", a: "Check your bar council’s rules first. Even without exact figures, explaining how fees are structured helps clients understand what to expect." },
      { q: "What legal content attracts clients?", a: "Accurate, plain-language guides to common processes, document checklists and procedure explanations, reviewed by qualified lawyers and linked to the relevant practice area pages." },
      { q: "How should law firms handle enquiries online?", a: "Keep forms short, explain how information is handled, avoid encouraging detailed case facts before a consultation and be clear about confidentiality on WhatsApp." },
    ],
  },

  /* ------------------------------------------------------------------ 24 restaurant */
  "restaurant-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for restaurants" },
      { type: "p", text: "Restaurant searches combine cuisine, dish, occasion, area and price. People search “best karahi in Islamabad”, “family restaurant F-7”, “rooftop restaurant Rawalpindi”, “iftar deals Islamabad” or “BBQ near me”. Knowing which of these your restaurant can genuinely win helps you choose categories, menu wording and website pages." },
      { type: "table", caption: "Restaurant search types", head: ["Type", "Example", "Where to win"], rows: [
        ["Cuisine + area", "Chinese restaurant G-11", "Business Profile categories"],
        ["Dish", "best biryani Islamabad", "Menu text and signature dish page"],
        ["Occasion", "birthday dinner restaurant Islamabad", "Events and private dining page"],
        ["Seasonal", "iftar buffet Rawalpindi", "Seasonal page and profile posts"],
        ["Feature", "rooftop restaurant, family hall", "Attributes and photos"],
      ] },
      { type: "h2", text: "Photography that sells food" },
      { type: "p", text: "Photos are often the deciding factor when people choose a restaurant on Google Maps. Professional-looking photos do not require expensive equipment: natural light, clean plates, simple backgrounds and a steady phone produce good results. Photograph every popular dish, the dining area at a busy but tidy moment, the exterior so people can find you, and special features such as rooftop seating or a family hall." },
      { type: "checklist", title: "Restaurant photo checklist", items: [
        "Each signature dish in natural light",
        "The dining area, showing seating and atmosphere",
        "The exterior and entrance for easy recognition",
        "Family halls, rooftop or outdoor areas",
        "The team and kitchen, if presentable",
        "Seasonal deals and buffets when running",
      ] },
      { type: "h2", text: "Managing reviews for restaurants" },
      { type: "p", text: "Restaurants receive more reviews than most businesses, and many mention specific dishes, service or waiting times. Reply to as many as you can, especially complaints. A calm reply that acknowledges the problem and explains what you changed, such as adding staff on weekend nights, shows future diners that you care. Use recurring complaints as operational feedback; fixing the cause improves both reviews and repeat business." },
      { type: "compare", title: "Handling a complaint about slow service", left: { label: "Poor reply", items: [
        "“We were very busy that day.”",
        "Blaming the customer’s timing",
        "No reply at all",
      ] }, right: { label: "Good reply", items: [
        "Thanking them for the feedback",
        "Apologising for the wait",
        "Explaining a concrete improvement made",
      ] } },
      { type: "h2", text: "Catering and events as an SEO opportunity" },
      { type: "p", text: "Catering and private events are often more profitable than everyday dining, and they are searched for specifically: office lunch catering, birthday hall booking, wedding catering per head. A dedicated page for each, with menus, per-head pricing, capacity and booking details, can rank well because few restaurants publish this information clearly. These pages also give you something useful to share with corporate clients and event planners." },
      { type: "h2", text: "Multiple branches and food chains" },
      { type: "p", text: "Chains need a Business Profile and a location page for each branch, with accurate timings, menus where they differ, photos of that branch and its own reviews. Keep branding consistent, but make each location page genuinely local, with directions, parking and branch-specific features. Customers searching near a branch should immediately see the right address and phone number." },
      { type: "h2", text: "Measuring restaurant SEO" },
      { type: "stats", title: "Restaurant metrics to watch", items: [
        { value: "Calls", label: "Reservation and order calls from Maps" },
        { value: "Directions", label: "Direction requests to each branch" },
        { value: "Menu", label: "Views of your online menu" },
        { value: "Direct", label: "Orders placed directly rather than via apps" },
      ] },
    ],
    faqs: [
      { q: "How can my restaurant rank for dish searches like best biryani?", a: "Include the dish clearly in your menu text, create a page for signature dishes with photos and descriptions, and encourage reviews that mention the dish." },
      { q: "Should restaurants have catering and events pages?", a: "Yes. Catering and events are searched for specifically and are often profitable. Dedicated pages with menus, per-head pricing, capacity and booking details can rank well." },
      { q: "How should a restaurant reply to complaints about waiting times?", a: "Thank the reviewer, apologise for the wait and explain a concrete improvement you made, such as adding staff at peak times. Avoid excuses or blaming the customer." },
    ],
  },

  /* ------------------------------------------------------------------ 25 hotel */
  "hotel-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for hotels and guest houses" },
      { type: "p", text: "Hotel searches combine location, type, purpose and features: “guest house in F-7 Islamabad”, “hotel near Islamabad airport”, “family hotel Murree with parking”, “conference hall Islamabad”. Understanding which of these your property can serve best shapes your website structure and Business Profile." },
      { type: "table", caption: "Hotel search patterns", head: ["Pattern", "Example", "Page"], rows: [
        ["Location", "hotel in Blue Area Islamabad", "Home and location page"],
        ["Proximity", "hotel near the airport or a landmark", "Location and directions page"],
        ["Purpose", "business hotel Islamabad, honeymoon hotel Murree", "Purpose-based landing pages"],
        ["Feature", "hotel with parking, family rooms", "Room and facility pages"],
        ["Events", "wedding venue, conference hall", "Events pages"],
      ] },
      { type: "h2", text: "Rates, parity and the direct booking promise" },
      { type: "p", text: "Guests compare prices across your website and booking platforms. If your own website shows a higher price than a platform, guests will book through the platform. Keep your direct rates competitive and make the benefits of booking direct clear, such as flexible cancellation, a free breakfast, an airport pickup or a room upgrade when available. Make sure any promise you make is delivered at check-in." },
      { type: "checklist", title: "Direct booking benefits to consider", items: [
        "Best available rate on the official website",
        "Flexible cancellation or free date changes",
        "Breakfast or welcome drink included",
        "Airport or bus station pickup",
        "Early check-in or late check-out when possible",
        "Direct WhatsApp contact with the front desk",
      ] },
      { type: "h2", text: "Reviews across platforms" },
      { type: "p", text: "Guests read reviews on Google and on booking platforms before choosing. Reply professionally to reviews everywhere, thank guests for specific praise and address complaints calmly with concrete improvements. Encourage satisfied guests to leave a Google review at checkout, which strengthens your local visibility and your brand search results." },
      { type: "h2", text: "Corporate and group business" },
      { type: "p", text: "Islamabad hotels attract business travellers, government delegations, NGOs and conference organisers. Dedicated pages for corporate rates, meeting rooms and group bookings, with capacity, equipment, catering options and a quick enquiry form, help these customers find and contact you directly. Corporate clients often book repeatedly, so a direct relationship is especially valuable." },
      { type: "h2", text: "Seasonality in hill station and city hotels" },
      { type: "p", text: "Hotels in Murree, Nathia Gali and the northern areas see strong seasonal peaks, while city hotels see different patterns around conferences, holidays and events. Publish and refresh seasonal content well before demand: summer escape pages early in the year, winter snow pages in the autumn, Eid holiday packages several weeks ahead. Keep the same URLs each year and update them, so they keep their ranking history." },
      { type: "bars", title: "When to update seasonal hotel content", items: [
        { label: "Summer hill station stays", value: 4, display: "Jan–Mar" },
        { label: "Winter snow trips", value: 3, display: "Sep–Oct" },
        { label: "Eid holiday packages", value: 2, display: "6–8 weeks before" },
        { label: "Conference season (city hotels)", value: 2, display: "Ongoing" },
      ], note: "Indicative timings based on typical search seasonality." },
      { type: "h2", text: "Measuring hotel SEO" },
      { type: "p", text: "Track direct bookings and revenue from your website separately from platform bookings, along with calls and WhatsApp enquiries from your Business Profile. Watch the share of total bookings that come direct; a rising share means you are paying less commission and owning more guest relationships." },
    ],
    faqs: [
      { q: "Why do guests book through platforms instead of my website?", a: "Usually because platforms show the same or lower prices and more reviews. Keep direct rates competitive, offer clear direct booking benefits and make your website booking fast and simple." },
      { q: "Should hotels have separate pages for corporate clients?", a: "Yes. Corporate rates, meeting rooms and group booking pages with capacity, equipment and quick enquiry options help business clients book directly and repeatedly." },
      { q: "When should hill station hotels publish seasonal content?", a: "Several months before peak demand: summer stays early in the year, winter snow trips in the autumn and Eid packages six to eight weeks ahead." },
    ],
  },

  /* ------------------------------------------------------------------ 26 travel */
  "travel-seo-expert": {
    blocks: [
      { type: "h2", text: "Hajj and Umrah SEO in detail" },
      { type: "p", text: "Religious travel is one of the most trust-sensitive categories in Pakistani search. Pilgrims and their families need confidence that the operator is licensed, that packages are exactly as described, and that support will be available throughout the journey. Search behaviour reflects this: people search by month, by package type, by hotel distance from the Haram, by family size and by departure city." },
      { type: "table", caption: "Umrah package page essentials", head: ["Element", "What to include"], rows: [
        ["Dates and duration", "Departure month, number of nights in Makkah and Madinah"],
        ["Hotels", "Names, star ratings and walking distance from the Haram"],
        ["Flights", "Airline, departure city and baggage"],
        ["Inclusions", "Visa, transport, ziyarat, meals"],
        ["Price", "Per person by room sharing, with what is excluded"],
        ["Support", "Group leader, contact during the trip, emergency support"],
      ] },
      { type: "p", text: "Show your licence and registration prominently, publish photos and reviews from past groups with permission, and explain the booking and payment process clearly. These details are what pilgrims look for, and providing them openly is one of the strongest ways to stand out." },
      { type: "h2", text: "Northern areas tour content" },
      { type: "p", text: "Domestic tourism to Hunza, Skardu, Swat, Naran, Kaghan and Fairy Meadows attracts families, couples, students and corporate groups. Each audience has different priorities: families care about safety and comfort, couples about scenery and privacy, students about cost, and corporate groups about logistics. Separate itineraries or sections for each audience help them find what fits." },
      { type: "checklist", title: "What northern tour pages should explain", items: [
        "Day-by-day route with travel times",
        "Road conditions and the type of vehicle used",
        "Hotels or camps, with photos",
        "Altitude and any health considerations",
        "What to pack for the season",
        "Weather and road closure risks, with your contingency plans",
      ] },
      { type: "h2", text: "Visa and outbound travel content" },
      { type: "p", text: "Outbound travel searches often start with visa questions: requirements, processing times, documents and fees for popular destinations. Accurate, regularly updated visa guides attract these searchers and lead naturally into package enquiries. Because visa rules change, show a last-updated date and link to official sources where appropriate. Outdated visa information damages trust quickly." },
      { type: "callout", tone: "warn", title: "Keep visa content current", text: "Visa rules and fees change often. Review visa guides regularly, show the date of the last update, and remove or correct outdated information promptly." },
      { type: "h2", text: "Using reviews and real trip content" },
      { type: "p", text: "Travel buyers want proof that trips happen as advertised. After each trip, collect reviews and, with permission, photos and short videos from travellers. Add them to the relevant itinerary page and share highlights on social media. Over time, this builds a library of real evidence that competitors using stock photos cannot match." },
      { type: "h2", text: "Travel SEO and paid advertising" },
      { type: "p", text: "Seasonal demand makes travel a good fit for combining SEO with paid search. SEO builds long-term visibility for itinerary and guide pages, while ads can capture demand quickly at the start of a season, for new products, or for competitive terms. Point ads at the same detailed itinerary pages and track enquiries by source to decide where to invest." },
      { type: "stats", title: "Travel SEO metrics", items: [
        { value: "Enquiries", label: "By itinerary page and season" },
        { value: "Bookings", label: "Confirmed trips from organic search" },
        { value: "Timing", label: "When enquiries start each season" },
        { value: "Reviews", label: "New reviews after each trip" },
      ] },
    ],
    faqs: [
      { q: "What should an Umrah package page include?", a: "Dates and duration, hotel names and distance from the Haram, flights, inclusions, price per person by room sharing, exclusions, support during the trip and the operator’s licence details." },
      { q: "How do I keep visa guides accurate?", a: "Review them regularly, show a last-updated date, link to official sources where appropriate and correct outdated information promptly." },
      { q: "Should travel agencies combine SEO with Google Ads?", a: "Often yes. SEO builds long-term visibility, while ads capture seasonal demand quickly. Point both at detailed itinerary pages and track enquiries by source." },
    ],
  },
};
