import type { Deep } from "./deep";

export const DEEP_F: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 27 education */
  "education-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for schools, colleges and academies" },
      { type: "p", text: "Education searches in Pakistan cover several distinct audiences. Parents search for schools by area, curriculum and fees. Students search for colleges and programmes by subject, eligibility and scholarships. Adult learners search for short courses, certifications and evening classes. Each audience uses different words and needs different pages, so an education SEO expert starts by separating them clearly." },
      { type: "table", caption: "Education search patterns", head: ["Audience", "Example searches", "Page type"], rows: [
        ["Parents of young children", "Montessori near F-10, primary school G-11 fees", "Campus and level pages"],
        ["Parents of teenagers", "O level school Islamabad, Matric vs O level", "Programme pages and comparison guides"],
        ["Students", "FSc pre-medical college Rawalpindi, A level admissions", "Programme and admissions pages"],
        ["University applicants", "BS computer science Islamabad, merit list dates", "Programme, eligibility and dates pages"],
        ["Adult learners", "evening English course, digital marketing course Rawalpindi", "Course pages with schedules and fees"],
      ] },
      { type: "p", text: "Your Search Console data will show which of these audiences already find you, and through which pages. Many institutions discover that parents search far more specifically than expected, for example by sector, class level and curriculum together, and that no page on the site answers those combined questions directly." },
      { type: "h2", text: "Comparison content parents actually want" },
      { type: "p", text: "Parents in Islamabad and Rawalpindi often compare curricula and systems before choosing a school: Matric versus O level, Cambridge versus local boards, or one campus against another. Honest comparison content helps them decide and positions your school as knowledgeable and trustworthy. The key is fairness. A comparison that explains the strengths and limitations of each option, and who each suits, is far more credible than one that simply promotes your own offering." },
      { type: "compare", title: "How to write curriculum comparisons", left: { label: "Weak comparison", items: [
        "Only lists advantages of your own curriculum",
        "Uses vague claims without detail",
        "Ignores cost and practical differences",
        "Does not say who each option suits",
      ] }, right: { label: "Strong comparison", items: [
        "Explains strengths and limits of each option",
        "Covers subjects, exams, recognition and progression",
        "Includes cost and time differences",
        "Helps parents decide what suits their child",
      ] } },
      { type: "h2", text: "Results, faculty and facilities as trust signals" },
      { type: "p", text: "Parents and students judge quality through evidence. Publish recent results in a clear, honest format, with dates and context. Introduce key faculty with their qualifications and experience. Show facilities with real photos: laboratories, libraries, sports grounds, transport and safety arrangements. Update these pages every year, because outdated results or staff lists quickly undermine trust and suggest a school that does not care about details." },
      { type: "checklist", title: "Trust content for education websites", items: [
        "Recent results with dates and context",
        "Faculty profiles with qualifications",
        "Real photos of classrooms, labs and grounds",
        "Transport routes, timings and safety measures",
        "Admission criteria and test information",
        "Fee structure with a last-updated date",
        "Parent and alumni testimonials with permission",
      ] },
      { type: "h2", text: "Academies and coaching centres" },
      { type: "p", text: "Coaching centres and academies for entry tests, O and A levels, and professional exams face intense local competition and strong seasonality. Students search for specific subjects, teachers, batch timings and results. Pages for each course or batch, with schedules, fees, teacher profiles and past results, perform best. A complete Business Profile with real photos and reviews from students and parents helps the academy appear for “near me” searches around colleges and universities." },
      { type: "p", text: "Timing is critical for academies. Entry test preparation, board exam revision and new academic years each create predictable peaks. Publish and update batch pages several weeks before each peak, and use Business Profile posts to announce new batches as soon as they open." },
      { type: "h2", text: "Online learning and wider reach" },
      { type: "p", text: "Many Pakistani institutions now offer online classes, which can reach students far beyond their city. Online programmes need their own pages explaining how classes work, which platforms are used, timings across time zones if overseas students are welcome, and how assessment and certificates are handled. Clear information helps students in other cities and abroad choose with confidence." },
      { type: "h2", text: "Measuring education SEO" },
      { type: "stats", title: "Education SEO metrics", items: [
        { value: "Enquiries", label: "Admission enquiries by campus and programme" },
        { value: "Visits", label: "Campus visits and test registrations" },
        { value: "Enrolments", label: "Students enrolled from organic search" },
        { value: "Season", label: "When enquiries start each admission cycle" },
      ] },
      { type: "p", text: "Tracking when enquiries start each year is particularly useful. If enquiries begin earlier than expected, content needs to be ready earlier the following year. Over two or three cycles, this data gives an institution a precise content calendar matched to its own audience." },
    ],
    faqs: [
      { q: "Should schools publish curriculum comparisons?", a: "Yes, if they are fair. Honest comparisons of Matric, O level and other options help parents decide and position the school as knowledgeable and trustworthy." },
      { q: "How can academies attract more students online?", a: "Create pages for each course or batch with schedules, fees, teacher profiles and past results, keep a complete Business Profile with reviews, and publish batch pages weeks before each seasonal peak." },
      { q: "Do online programmes need separate pages?", a: "Yes. Explain how classes work, platforms used, timings, assessment and certificates so students in other cities and abroad can choose confidently." },
      { q: "How should schools present exam results online?", a: "Clearly and honestly, with dates and context, updated every year. Outdated or unclear results undermine trust." },
    ],
  },

  /* ------------------------------------------------------------------ 28 SaaS */
  "saas-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for software products" },
      { type: "p", text: "SaaS keyword research starts with customers, not tools. Interview recent customers and sales staff to learn the words buyers use for their problems, the alternatives they considered and the objections they raised. Then use keyword tools and Search Console to estimate demand and find related terms. The aim is a map of problems, use cases, features, integrations and competitors, each linked to a page that answers it." },
      { type: "table", caption: "SaaS keyword map example", head: ["Theme", "Example query", "Page"], rows: [
        ["Problem", "how to track employee attendance remotely", "Guide with template"],
        ["Use case", "attendance software for schools", "Industry use-case page"],
        ["Feature", "geofenced attendance app", "Feature page"],
        ["Integration", "attendance software payroll integration", "Integration page"],
        ["Competitor", "alternatives to a known attendance tool", "Alternative page"],
        ["Pricing", "attendance software price per user", "Pricing page"],
      ] },
      { type: "h2", text: "Product-led content" },
      { type: "p", text: "The most effective SaaS content shows the product solving the problem. Instead of a generic article about reducing payroll errors, a product-led article explains the causes of payroll errors and shows, with screenshots, how the product prevents each one. This content ranks for problem searches and converts better, because readers see the solution in action. It also earns links and citations more easily, because it is specific and useful." },
      { type: "list", items: [
        "Use real screenshots and workflows, not stock images.",
        "Show before-and-after examples of the problem being solved.",
        "Include templates or checklists readers can use immediately.",
        "End with a natural invitation to try the feature shown.",
      ] },
      { type: "h2", text: "Selling internationally from Pakistan" },
      { type: "p", text: "Many Pakistani software companies sell to customers in the Gulf, the UK, North America and beyond. International buyers need reassurance about support hours, data security, payment options and the company’s track record. Pages that address these concerns openly, alongside case studies from customers in the target market, help overcome the hesitation some buyers feel about vendors they do not know." },
      { type: "checklist", title: "Trust content for international SaaS buyers", items: [
        "Support hours in the buyer’s time zone",
        "Security and data protection practices explained clearly",
        "Uptime and reliability information",
        "Payment options and invoicing in common currencies",
        "Case studies and logos from customers in the target market",
        "Named leadership and company registration details",
      ] },
      { type: "h2", text: "Documentation and help centres as SEO assets" },
      { type: "p", text: "Documentation is often the most visited part of a SaaS website, and it can attract both existing customers and prospects searching how to do specific tasks. Well-structured help articles with clear titles, step-by-step instructions, screenshots and internal links rank for many long-tail queries. Make sure documentation is crawlable, avoid duplicate versions for different product releases where possible, and link from help articles to relevant feature pages." },
      { type: "h2", text: "Product-led growth and SEO together" },
      { type: "p", text: "For products with a free trial or free plan, SEO feeds product-led growth. Visitors arrive through guides, templates or use-case pages, sign up, and experience the product directly. Track this journey carefully: which landing pages produce sign-ups, which sign-ups activate, and which convert to paid accounts. This data shows which content brings genuinely valuable users rather than casual visitors." },
      { type: "stats", title: "SaaS funnel metrics from organic search", items: [
        { value: "Sign-ups", label: "Trials or free accounts by landing page" },
        { value: "Activation", label: "Users completing a key action" },
        { value: "Paid", label: "Conversions to paid plans" },
        { value: "Pipeline", label: "Demo requests and deal value" },
      ] },
      { type: "h2", text: "Choosing a SaaS SEO expert" },
      { type: "p", text: "Look for someone who has grown software products before, understands the funnel from content to activation and revenue, and can work with product and engineering teams on technical issues. Ask how they would approach comparison pages, documentation and international markets. Experts who talk mainly about traffic, rather than pipeline and revenue, are usually not the right fit for a software company." },
    ],
    faqs: [
      { q: "How do I find keywords for a SaaS product?", a: "Start with customer interviews and sales conversations to learn buyer language, then use keyword tools and Search Console to estimate demand across problems, use cases, features, integrations and competitors." },
      { q: "What is product-led content?", a: "Content that explains a problem and shows, with real screenshots and workflows, how the product solves it. It ranks for problem searches and converts better than generic articles." },
      { q: "How can Pakistani SaaS companies win international buyers?", a: "By addressing support hours, security, reliability, payment options and track record openly, with case studies and logos from customers in the target market." },
      { q: "Should SaaS documentation be optimised for SEO?", a: "Yes. Crawlable, well-structured help articles with clear titles and steps rank for many long-tail queries and attract both customers and prospects." },
    ],
  },

  /* ------------------------------------------------------------------ 29 international */
  "international-seo-expert": {
    blocks: [
      { type: "h2", text: "Choosing target markets with data" },
      { type: "p", text: "Many Pakistani exporters try to target every country at once and end up visible nowhere. A better approach is to choose one or two markets based on evidence: existing customers and enquiries, search demand for your products, competitive intensity, logistics and trade agreements. Search Console already shows which countries send impressions and clicks, and your sales records show where buyers come from. Start where these signals agree." },
      { type: "table", caption: "Scoring a potential market", head: ["Factor", "Questions to ask"], rows: [
        ["Existing demand", "Do we already get enquiries or orders from this country?"],
        ["Search demand", "Do buyers there search for our products in meaningful volume?"],
        ["Competition", "Who ranks today, and can we offer something better or different?"],
        ["Logistics", "Can we ship, deliver and support customers there reliably?"],
        ["Trade conditions", "Are tariffs, standards and certifications manageable?"],
      ] },
      { type: "h2", text: "Keyword research in each market" },
      { type: "p", text: "Buyers in different countries describe the same product differently. British buyers may search for trousers where Americans search for pants; trade buyers search with technical specifications and standards; some markets search in their own language. International keyword research therefore needs to be done separately for each market, using local search data, competitor sites in that market and input from sales teams or agents who know the buyers." },
      { type: "list", items: [
        "Research terms in each market separately, not by translating your Pakistani keywords.",
        "Include trade and technical terms used by professional buyers.",
        "Check how competitors in that market name and group products.",
        "Ask agents, distributors or existing customers which terms they use.",
      ] },
      { type: "h2", text: "Technical setup for international sites" },
      { type: "p", text: "Once markets are chosen, the technical setup must make each version clear to search engines. That means a consistent URL structure, correct hreflang annotations between language or country versions, self-referencing canonical tags on each version, and no automatic redirects that prevent users or search engines from reaching every version. Server location matters less than it used to, but page speed in the target market still matters, so a content delivery network is usually worthwhile." },
      { type: "checklist", title: "International technical checklist", items: [
        "Consistent URL structure for each market",
        "Hreflang with return links between all versions",
        "Self-referencing canonical tags on each version",
        "No forced redirects based on IP location",
        "A content delivery network for fast loading abroad",
        "Separate sitemaps or sitemap entries for each version",
      ] },
      { type: "h2", text: "Earning international links and mentions" },
      { type: "p", text: "Authority in a target market comes partly from links and mentions in that market. For exporters, good sources include trade directories, industry associations in the buyer’s country, trade fair exhibitor listings, distributor and agent websites, and trade publications. Taking part in international trade fairs and publishing useful technical content for buyers in that market both create natural opportunities for these links." },
      { type: "h2", text: "Converting international enquiries" },
      { type: "p", text: "International buyers often send detailed enquiries and expect fast, professional responses. Make enquiry forms ask for the information you need to quote, such as quantities, specifications and destination, and respond within a business day in the buyer’s time zone where possible. Provide clear product specifications, sample policies, payment terms and lead times on the website, so buyers can qualify themselves before contacting you." },
      { type: "stats", title: "International SEO metrics", items: [
        { value: "Market", label: "Impressions and clicks by target country" },
        { value: "Enquiries", label: "Qualified enquiries from each market" },
        { value: "Response", label: "Time to first reply to buyers" },
        { value: "Orders", label: "Orders and revenue by market" },
      ] },
      { type: "h2", text: "Choosing an international SEO expert" },
      { type: "p", text: "Look for someone who has helped businesses enter new markets, understands hreflang and international site structures, and can research keywords properly in each target market. Ask how they would choose markets for you, which structure they would recommend and why, and how they would build authority abroad. Practical experience with exporters or software firms selling internationally is a strong advantage." },
    ],
    faqs: [
      { q: "How do I choose which countries to target?", a: "Use evidence: existing enquiries and customers, search demand, competition, logistics and trade conditions. Start with one or two markets where these signals agree." },
      { q: "Can I translate my keywords for other countries?", a: "Not reliably. Buyers in each market use their own terms, including technical and trade terms. Research keywords separately in each market." },
      { q: "Do I need a server in each country?", a: "Usually not. Server location matters less than it used to; a content delivery network can provide fast loading in target markets." },
      { q: "How can exporters earn links in foreign markets?", a: "Through trade directories, industry associations, trade fair exhibitor listings, distributor and agent websites, and useful technical content for buyers in that market." },
    ],
  },
};
