import type { Deep } from "./deep";

export const DEEP_D: Record<string, Deep> = {
  /* ------------------------------------------------------------------ 17 off-page */
  "off-page-seo-expert": {
    blocks: [
      { type: "h2", text: "How links actually pass value" },
      { type: "p", text: "Not all links are equal. A link from a respected industry association, placed inside a relevant article that real people read, tells Google far more than a link from an unrelated blog that exists only to sell placements. Google’s systems look at the context around a link, the relevance and trust of the linking site, and whether the link appears to be an editorial choice rather than a purchase. That is why a handful of good links can outperform hundreds of poor ones." },
      { type: "table", caption: "What makes a link valuable", head: ["Factor", "Higher value", "Lower value"], rows: [
        ["Relevance", "Same industry or location", "Unrelated topic"],
        ["Trust", "Established site with real readers", "New site with no audience"],
        ["Placement", "Inside main content", "Footer, sidebar or long link lists"],
        ["Editorial choice", "Earned through merit or relationship", "Paid without disclosure"],
        ["Anchor text", "Natural, often the brand name", "Repeated exact-match keywords"],
      ] },
      { type: "p", text: "Link attributes also matter. Links marked rel=\"nofollow\", rel=\"sponsored\" or rel=\"ugc\" tell Google not to treat them as an endorsement in the usual way. They still have value: they bring visitors, build brand awareness and form part of a natural profile. A healthy site has a mix of followed and unfollowed links, just as a real business would." },
      { type: "h2", text: "Digital PR for Pakistani businesses" },
      { type: "p", text: "Digital PR means earning coverage and links by giving journalists and publishers something worth writing about. It works well in Pakistan because business, technology and lifestyle media constantly need expert comment, data and local stories. The key is to offer something genuinely useful rather than promotional." },
      { type: "slides", title: "Digital PR ideas that earn coverage", slides: [
        { title: "Data stories", points: ["Survey your customers on a topic in the news", "Publish price trends from your own sales", "Share anonymised insights from your industry"] },
        { title: "Expert comment", points: ["Offer quick, quotable comment on industry news", "Explain the effect of new regulations", "Give practical advice during seasonal peaks"] },
        { title: "Community stories", points: ["Training programmes or scholarships", "Local initiatives with real impact", "Milestones that matter to customers"] },
        { title: "Useful resources", points: ["Free guides and checklists", "Calculators or comparison tools", "Directories of useful local services"] },
      ] },
      { type: "p", text: "Keep a simple media list of journalists who cover your industry, follow their work, and send short, relevant pitches only when you have something that fits what they write about. A few strong relationships with editors are worth more than mass emails to hundreds of addresses." },
      { type: "h2", text: "Brand mentions and their growing importance" },
      { type: "p", text: "Even without a link, being mentioned on respected sites helps people discover and trust your business. AI assistants also learn how to describe businesses partly from what is written about them across the web. Consistent, positive mentions in news articles, industry publications, forums and directories help build a clear picture of who you are and what you do." },
      { type: "checklist", title: "Ways to grow brand mentions", items: [
        "Speak at local events, university seminars or industry meetups",
        "Contribute expert articles to industry publications",
        "Take part in community and charity initiatives",
        "Answer questions helpfully in relevant online communities",
        "Partner with complementary businesses on joint content or events",
        "Keep business details consistent so mentions are clearly about you",
      ] },
      { type: "h2", text: "Cleaning up a risky link profile" },
      { type: "p", text: "Many Pakistani businesses have bought link packages in the past, sometimes without knowing what they were getting. If your profile includes obviously spammy links, the first step is to stop buying more. Google says it is good at ignoring most spammy links on its own. Disavowing links is generally only recommended when you have a manual action for unnatural links, or when you know you took part in a large link scheme and want to address it." },
      { type: "process", title: "Handling a risky link profile", steps: [
        { title: "Stop", text: "End any paid link arrangements" },
        { title: "Review", text: "Export links from Search Console" },
        { title: "Assess", text: "Check for a manual action" },
        { title: "Act", text: "Remove or disavow only if needed" },
        { title: "Rebuild", text: "Earn relevant, natural links" },
      ] },
      { type: "callout", tone: "warn", title: "Use the disavow tool carefully", text: "Disavowing the wrong links can remove genuine value. If you are unsure, get an expert opinion before submitting a disavow file." },
      { type: "h2", text: "Local off-page signals for city-based businesses" },
      { type: "p", text: "For businesses that depend on local customers, off-page SEO has a local flavour. Citations on local directories, links from local news sites, mentions by nearby businesses and organisations, and reviews on Google and other platforms all help Google understand that you are a real, active part of your city. A clinic in Islamabad benefits more from a mention by a local health association than from a link on a general international directory." },
      { type: "bars", title: "Local off-page signals by impact", items: [
        { label: "Google reviews", value: 5, display: "High" },
        { label: "Links from local news and associations", value: 4, display: "High" },
        { label: "Consistent citations", value: 3, display: "Medium" },
        { label: "Mentions by partner businesses", value: 3, display: "Medium" },
        { label: "Generic international directories", value: 1, display: "Low" },
      ], note: "Our view of what tends to help local businesses most." },
    ],
    faqs: [
      { q: "What is the difference between dofollow and nofollow links?", a: "Followed links can pass ranking signals; links marked nofollow, sponsored or ugc tell Google not to treat them as a normal endorsement. A natural profile contains both, and nofollow links still bring visitors and awareness." },
      { q: "Should I disavow bad backlinks?", a: "Usually only if you have a manual action for unnatural links or know you took part in a large link scheme. Google ignores most spammy links on its own. Get expert advice before disavowing." },
      { q: "What is digital PR in SEO?", a: "Earning coverage and links by giving journalists something worth writing about, such as data, expert comment, community stories or useful resources, rather than paying for placements." },
    ],
  },

  /* ------------------------------------------------------------------ 18 audit */
  "seo-audit-expert": {
    blocks: [
      { type: "h2", text: "A walk-through of a real-style audit" },
      { type: "p", text: "To make the audit process concrete, here is an illustrative example of how an audit expert might work through a mid-sized Islamabad services website with around 80 pages and falling enquiries." },
      { type: "list", ordered: true, items: [
        "**Data review.** Search Console shows impressions steady but clicks falling over six months. The biggest drops are on three service pages.",
        "**Indexing check.** Twelve old service pages are still indexed after a redesign, competing with their replacements. Several new pages are “Discovered, currently not indexed”.",
        "**Technical crawl.** The redesign introduced redirect chains and broken internal links to old URLs. Mobile pages are slow because of a large background video.",
        "**Content review.** The new service pages are shorter than the old ones and dropped the pricing and FAQ sections that used to answer buyer questions.",
        "**Competitor comparison.** The three businesses now ranking above include clear prices, detailed process explanations and recent reviews.",
        "**Local check.** The Business Profile still lists an old phone number, and the category is broader than ideal.",
      ] },
      { type: "p", text: "From these findings, the audit’s top five priorities write themselves: redirect old pages properly, fix internal links and redirect chains, restore pricing and FAQs to the new service pages, remove the heavy video on mobile, and correct the Business Profile. None of these requires a large budget, but together they explain most of the decline." },
      { type: "h2", text: "Content audit: deciding what to keep, improve or remove" },
      { type: "p", text: "Many sites accumulate pages that no longer serve a purpose: old news, thin blog posts, outdated offers, near-duplicate service pages. A content audit reviews every page and decides what to do with it. The goal is a site where every indexed page is useful." },
      { type: "table", caption: "Content audit decisions", head: ["Page situation", "Decision"], rows: [
        ["Useful, accurate, getting traffic", "Keep and refresh periodically"],
        ["Useful topic, weak or outdated content", "Improve and update"],
        ["Several pages covering the same topic", "Merge into one strong page and redirect the rest"],
        ["No traffic, no links, no business value", "Remove or noindex, with redirects if it had links"],
        ["Outdated offer or event", "Redirect to the current equivalent or remove"],
      ] },
      { type: "callout", tone: "tip", title: "Do not delete blindly", text: "Before removing any page, check whether it has external links or brings any traffic. If it does, redirect it to the most relevant current page so you keep that value." },
      { type: "h2", text: "Backlink audit basics" },
      { type: "p", text: "A backlink audit looks at who links to your site and whether those links help or create risk. For most small businesses, the main goals are to understand which pages attract links, find opportunities to earn more from similar sources, and spot any obvious signs of past link schemes. Search Console’s Links report is a free starting point; paid tools add more detail." },
      { type: "checklist", title: "What a backlink audit reviews", items: [
        "The number of different sites linking to you, not just total links",
        "Which pages receive the most links",
        "The relevance and quality of the main linking sites",
        "Patterns suggesting paid links or networks",
        "Lost links that could be recovered",
        "Competitor links that might be realistic for you to earn",
      ] },
      { type: "h2", text: "Local SEO audit checklist" },
      { type: "p", text: "For businesses with local customers, the audit should include a dedicated local section. Many Islamabad and Rawalpindi businesses have strong websites but weak Business Profiles, or the reverse. Both need to work together." },
      { type: "checklist", title: "Local audit points", items: [
        "Business Profile ownership, verification and correct details",
        "Primary and secondary categories compared with competitors",
        "Services, photos, hours and attributes complete",
        "Review count, rating, recency and reply rate",
        "Name, address and phone consistent across directories",
        "Location pages on the website matching the profile",
        "Grid ranking for main services across the service area",
      ] },
      { type: "h2", text: "Presenting audit findings to decision makers" },
      { type: "p", text: "An audit is only useful if the people who control budget and resources understand it. Business owners rarely need technical detail; they need to know what is wrong, what it is costing, what it will take to fix, and in what order. A good audit expert writes a one-page summary for decision makers and a detailed appendix for the people doing the work." },
      { type: "stats", title: "What decision makers want from an audit", items: [
        { value: "Problem", label: "What is holding results back, in plain words" },
        { value: "Cost", label: "What it is costing in visibility or enquiries" },
        { value: "Fix", label: "What it will take, who and how long" },
        { value: "Order", label: "What to do first, second and third" },
      ] },
    ],
    faqs: [
      { q: "What is a content audit?", a: "A review of every page on the site to decide whether to keep, improve, merge or remove it, so that every indexed page is useful. Pages with links or traffic should be redirected rather than deleted." },
      { q: "Does a small business need a backlink audit?", a: "A light one is useful: understanding which pages attract links, spotting signs of past link schemes and finding realistic opportunities. Search Console’s Links report is a free starting point." },
      { q: "What should an SEO audit summary include for business owners?", a: "A short explanation of what is holding results back, what it is likely costing, what it will take to fix and in which order, with technical detail kept in an appendix for the team." },
    ],
  },

  /* ------------------------------------------------------------------ 19 link building */
  "link-building-expert": {
    blocks: [
      { type: "h2", text: "Outreach that gets replies" },
      { type: "p", text: "Most link outreach fails because it is generic, long and obviously self-serving. Editors and site owners receive many requests every week and ignore most of them. Outreach that works is short, personal and offers something useful to the recipient’s readers." },
      { type: "compare", title: "Outreach that gets ignored versus replies", left: { label: "Ignored", items: [
        "“Dear Sir/Madam, we would like a backlink”",
        "Long emails about your company",
        "Offering payment for a link",
        "The same message sent to hundreds of sites",
      ] }, right: { label: "Gets replies", items: [
        "Addressed to a named person about a specific article",
        "Two or three sentences explaining the value to their readers",
        "Offering data, a quote or a resource they can use",
        "Sent to a small, carefully chosen list",
      ] } },
      { type: "p", text: "Follow up once, politely, and then move on. Keep a simple record of who you contacted, when and what happened, so you do not pester the same people and you can see which kinds of pitches work." },
      { type: "h2", text: "Linkable assets: content worth linking to" },
      { type: "p", text: "The easiest links to earn point to content that is genuinely useful to other publishers: something they want to reference for their own readers. Creating one strong linkable asset often does more than months of outreach for ordinary pages." },
      { type: "table", caption: "Linkable asset ideas for Pakistani businesses", head: ["Asset", "Who might link to it"], rows: [
        ["Annual price or cost guide for your industry", "Journalists, bloggers, comparison sites"],
        ["Original survey results", "News sites, industry publications"],
        ["Free calculator or tool", "Blogs, forums, resource pages"],
        ["Definitive guide to a local process", "Universities, associations, community sites"],
        ["Directory or map of useful local resources", "Local news, community groups"],
      ] },
      { type: "h2", text: "Measuring the impact of link building" },
      { type: "p", text: "Links take time to show their effect, and their impact is often indirect. The right way to measure is to watch the pages that received links and the queries they target, over several months, alongside overall growth in referring domains from relevant sites. Avoid judging success by tool authority scores alone; they are third-party estimates, not Google metrics." },
      { type: "stats", title: "Link building metrics that matter", items: [
        { value: "Domains", label: "New relevant sites linking to you" },
        { value: "Pages", label: "Rankings of the pages that gained links" },
        { value: "Referrals", label: "Visitors arriving through those links" },
        { value: "Quality", label: "Share of links from relevant, trusted sites" },
      ] },
      { type: "h2", text: "Link building for local businesses" },
      { type: "p", text: "Local businesses rarely need national media coverage. Their best links come from the community they serve: local associations, chambers of commerce, schools and universities, charities, events they sponsor, suppliers and partners, and local news sites. These links are relevant, hard for distant competitors to copy, and often bring customers directly." },
      { type: "checklist", title: "Local link opportunities", items: [
        "Membership listings in local and industry associations",
        "Sponsorship of local sports, cultural or charity events",
        "Partnerships with complementary local businesses",
        "Scholarships or internships with local universities",
        "Expert comment for local news stories",
        "Supplier and distributor “where to buy” pages",
      ] },
      { type: "h2", text: "What a fair link building engagement looks like" },
      { type: "p", text: "A fair engagement sets clear expectations: the kinds of sites to target, the methods to be used, how many quality placements are realistic per month, and how results will be reported. It should exclude undisclosed paid links and private networks in writing, and include a complete monthly list of links earned. If a provider promises a fixed large number of links every month regardless of your niche, that is usually a sign of low-quality sources." },
      { type: "callout", tone: "note", title: "Quality takes time", text: "Earning a few genuinely good links a month is normal for local and niche businesses. Promises of dozens or hundreds of links a month usually mean low-quality or paid sources." },
    ],
    faqs: [
      { q: "How do I write an outreach email for a backlink?", a: "Keep it short and personal: address a named person, mention their specific article, explain in two or three sentences why your resource helps their readers, and follow up only once." },
      { q: "What is a linkable asset?", a: "Content so useful that other publishers want to reference it, such as cost guides, original surveys, calculators, definitive local guides or resource directories." },
      { q: "How many links should a local business build each month?", a: "A few genuinely relevant, trusted links a month is normal and effective. Large fixed numbers usually indicate low-quality or paid sources." },
    ],
  },

  /* ------------------------------------------------------------------ 20 real estate */
  "real-estate-seo-expert": {
    blocks: [
      { type: "h2", text: "Keyword research for property in the twin cities" },
      { type: "p", text: "Property searches in Islamabad and Rawalpindi follow recognisable patterns. Buyers search by society, phase, sector, plot size, property type, price range and purpose. Overseas buyers add terms about buying from abroad, documentation and payment. Mapping these patterns to pages is the foundation of real estate SEO." },
      { type: "table", caption: "Property search patterns", head: ["Pattern", "Example", "Page type"], rows: [
        ["Society + phase", "Bahria Town Phase 8 plots", "Society or phase page"],
        ["Sector + type", "house for sale F-11", "Area page with listings"],
        ["Size + location", "10 marla plot DHA Islamabad", "Filtered landing page"],
        ["Process question", "how to verify plot file Islamabad", "Guide"],
        ["Overseas buyer", "buy property in Islamabad from Dubai", "Overseas buyer guide"],
        ["Investment question", "best area to invest in Islamabad", "Comparison or market guide"],
      ] },
      { type: "h2", text: "Listings, expiry and technical hygiene" },
      { type: "p", text: "Property websites with listings face a constant technical challenge: listings go live, sell and expire. Left unmanaged, thousands of expired listing URLs accumulate, wasting crawl effort and frustrating visitors who land on dead pages. A clear policy keeps the site healthy." },
      { type: "list", items: [
        "**Sold or expired listings** show a clear notice and links to similar available properties, then redirect to the relevant area or society page after a period.",
        "**Area and society pages** stay permanent and collect the authority that individual listings would otherwise lose.",
        "**Listing filters** for size, price and type should not create endless indexable URLs.",
        "**Structured data** for listings should reflect real, current prices and availability.",
      ] },
      { type: "h2", text: "Trust content that converts serious buyers" },
      { type: "p", text: "Property is a high-stakes purchase, and Pakistani buyers have good reasons to be cautious. Content that addresses risk openly builds trust and often ranks well because buyers search for exactly these concerns." },
      { type: "slides", title: "Trust content for property businesses", slides: [
        { title: "Due diligence guides", points: ["How to verify a plot file", "Checking society approvals", "Questions to ask before paying"] },
        { title: "Process explainers", points: ["Transfer process step by step", "Fees and taxes involved", "Timelines to expect"] },
        { title: "Company credibility", points: ["Registration and licences", "Team profiles", "Completed projects with photos"] },
        { title: "Buyer stories", points: ["Testimonials with permission", "Case studies of completed purchases", "Overseas buyer experiences"] },
      ] },
      { type: "h2", text: "Combining SEO with paid search and portals" },
      { type: "p", text: "Most property businesses use a mix of channels: listing portals, social media, Google Ads and SEO. They work best together. Portals bring volume for generic searches, Google Ads can target high-intent searches immediately, and SEO builds a long-term asset of project, society and guide pages that keep producing enquiries without per-click costs. Tracking enquiries by source shows which channel produces the best buyers, not just the most leads." },
      { type: "bars", title: "Typical role of each channel", items: [
        { label: "SEO: project and guide pages", value: 5, display: "Long-term asset" },
        { label: "Google Ads: high-intent searches", value: 4, display: "Immediate" },
        { label: "Portals: generic searches", value: 3, display: "Volume" },
        { label: "Social media: awareness", value: 3, display: "Reach" },
      ], note: "A simplified view; the right mix depends on your projects and budget." },
      { type: "h2", text: "Video and virtual tours" },
      { type: "p", text: "Video is especially valuable in property marketing, because many buyers, particularly overseas, cannot visit in person. Walkthrough videos, drone footage of development progress and virtual tours help buyers shortlist with confidence. Embed them on project pages with written descriptions and dates, so search engines understand the content and buyers know it is current." },
    ],
    faqs: [
      { q: "What keywords should a property website target?", a: "Society and phase names, sectors with property types, plot sizes with locations, process questions such as file verification, overseas buyer questions and investment comparisons, each mapped to the right page type." },
      { q: "What should happen to sold property listings?", a: "Show a clear sold notice with links to similar properties, then redirect to the relevant society or area page, which keeps authority instead of leaving dead URLs." },
      { q: "Should property businesses use SEO and Google Ads together?", a: "Usually yes. Ads capture high-intent searches immediately, while SEO builds project, society and guide pages that keep producing enquiries over time." },
    ],
  },

  /* ------------------------------------------------------------------ 21 healthcare */
  "healthcare-seo-expert": {
    blocks: [
      { type: "h2", text: "Writing medical content responsibly" },
      { type: "p", text: "Medical content carries real responsibility. Patients may make decisions based on what they read, so accuracy matters more than volume or keyword targeting. Hospitals and clinics in Pakistan should treat their website content with the same care as patient information leaflets." },
      { type: "checklist", title: "Standards for medical content", items: [
        "Written or reviewed by a named, qualified clinician",
        "A visible date showing when it was last reviewed",
        "Plain language, with medical terms explained",
        "Clear advice to consult a doctor for individual situations",
        "No promises of cures or guaranteed outcomes",
        "Sources referenced where specific claims are made",
        "Regular review as guidance and treatments change",
      ] },
      { type: "p", text: "Content that meets these standards tends to perform better over time, because it earns trust from patients, links from other health sites and credibility in Google’s quality assessment. Content that cuts corners can damage the reputation of the whole site." },
      { type: "h2", text: "Structuring a hospital website" },
      { type: "p", text: "Large hospitals often have hundreds of services, dozens of doctors and several locations. A clear structure helps patients find what they need and helps Google understand the relationships between departments, doctors and procedures." },
      { type: "process", title: "A clear hospital site structure", steps: [
        { title: "Departments", text: "Cardiology, orthopaedics, paediatrics" },
        { title: "Procedures and conditions", text: "Linked from each department" },
        { title: "Doctors", text: "Linked to departments and procedures" },
        { title: "Locations", text: "With services available at each" },
      ] },
      { type: "p", text: "Link every doctor profile to the departments and procedures they cover, and every procedure page to the doctors who perform it. These connections help patients navigate and give search engines clear signals about expertise." },
      { type: "h2", text: "Doctor profiles that build trust" },
      { type: "p", text: "Doctor profiles are among the most visited pages on healthcare websites, because patients want to know who will treat them. A strong profile goes beyond a name and a photo." },
      { type: "table", caption: "What a strong doctor profile includes", head: ["Element", "Why it matters"], rows: [
        ["Full name and photo", "Patients want to recognise their doctor"],
        ["Qualifications and registration", "Verifiable credentials build trust"],
        ["Specialisation and experience", "Shows relevance to the patient’s need"],
        ["Conditions and procedures", "Matches what patients search for"],
        ["Clinic timings and locations", "Practical information for booking"],
        ["Languages spoken", "Helps patients communicate comfortably"],
      ] },
      { type: "h2", text: "Handling reviews in healthcare" },
      { type: "p", text: "Patient reviews influence choice strongly, but healthcare businesses must handle them with special care. Never confirm or discuss a patient’s treatment in a public reply, even if they mentioned it themselves. Thank reviewers in general terms, and invite anyone with concerns to contact the hospital privately. Encourage reviews from satisfied patients consistently, without incentives." },
      { type: "compare", title: "Review replies in healthcare", left: { label: "Avoid", items: [
        "Mentioning the patient’s condition or treatment",
        "Arguing about what happened",
        "Offering discounts for positive reviews",
      ] }, right: { label: "Do", items: [
        "Thank the reviewer without clinical details",
        "Invite private contact to resolve concerns",
        "Ask every satisfied patient for honest feedback",
      ] } },
      { type: "h2", text: "Telemedicine and online consultations" },
      { type: "p", text: "Many Pakistani hospitals and clinics now offer online consultations. These services can reach patients far beyond the physical location, but they need their own pages explaining how consultations work, which specialties are available, how to book and pay, and any limitations. Patients searching for online doctor consultations want clear, practical information before they commit." },
      { type: "h2", text: "Measuring healthcare SEO" },
      { type: "stats", title: "Healthcare SEO metrics", items: [
        { value: "Bookings", label: "Appointments booked online, by phone and WhatsApp" },
        { value: "Profiles", label: "Visits to doctor profile pages" },
        { value: "Local", label: "Calls and directions from Business Profiles" },
        { value: "Procedures", label: "Enquiries from procedure pages" },
      ] },
    ],
    faqs: [
      { q: "Who should write medical content for a hospital website?", a: "Content should be written or reviewed by named, qualified clinicians, with a visible review date, plain language and clear advice to consult a doctor for individual situations." },
      { q: "How should hospitals reply to patient reviews?", a: "Thank reviewers in general terms, never discuss a patient’s condition or treatment publicly, and invite anyone with concerns to contact the hospital privately." },
      { q: "Do telemedicine services need their own pages?", a: "Yes. Explain which specialties are available online, how consultations work, how to book and pay, and any limitations, so patients can decide confidently." },
    ],
  },
};
