import type { PostInput } from "@/lib/blog";
import { SRC } from "./part1";

const LINKS = { label: "Google Search Central: Qualify your outbound links", href: "https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links" };
const CRAWLABLE = { label: "Google Search Central: Link best practices", href: "https://developers.google.com/search/docs/crawling-indexing/links-crawlable" };
const RATER = { label: "Google Search Quality Rater Guidelines (PDF)", href: "https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf" };
const VITALS = { label: "web.dev: Core Web Vitals", href: "https://web.dev/articles/vitals" };
const GSC = { label: "Google Search Console", href: "https://search.google.com/search-console/about" };

export const PART5: PostInput[] = [
  /* ------------------------------------------------------------------ 18 */
  {
    slug: "off-page-seo-expert",
    title: "Off-Page SEO Expert: Strategies for Building Authority",
    keyword: "off page SEO expert",
    description: "How an off-page SEO expert builds authority without risky shortcuts: earned links, digital PR, citations, reviews, brand mentions and partnerships that work for Pakistani businesses.",
    category: "SEO skills",
    icon: "link",
    accent: "teal",
    answer: "An off-page SEO expert builds a website’s authority through signals that come from outside it: relevant links from respected sites, consistent business citations, genuine reviews, brand mentions and partnerships. In Pakistan, the safest and most effective sources are industry associations, local directories, suppliers and partners, media coverage and useful content that others cite, never paid link networks.",
    takeaways: [
      "Off-page SEO is about reputation: links, mentions, citations and reviews.",
      "Relevance and trust of the linking site matter far more than the number of links.",
      "Associations, partners, suppliers and local media are the best Pakistani link sources.",
      "Paid or sponsored links must be labelled; undisclosed paid links break Google’s policies.",
      "Brand mentions and reviews increasingly influence AI answers as well as rankings.",
    ],
    body: [
      { type: "h2", text: "What off-page SEO means today" },
      { type: "p", text: "**Off-page SEO** covers everything outside your website that signals your business is real, relevant and trusted. Links are still the most important part, but citations, reviews and brand mentions now matter too, especially as AI search tools summarise what the web says about a business." },
      { type: "stats", title: "The four off-page signals", items: [
        { value: "Links", label: "Relevant sites linking to your pages" },
        { value: "Citations", label: "Consistent name, address and phone listings" },
        { value: "Reviews", label: "Genuine customer feedback on Google and elsewhere" },
        { value: "Mentions", label: "Your brand discussed in articles, forums and media" },
      ] },
      { type: "h2", text: "Strategies that work for Pakistani businesses" },
      { type: "slides", title: "Sustainable off-page strategies", slides: [
        { title: "Associations and chambers", points: ["Membership listings in industry bodies", "Chamber of commerce member directories", "Professional councils where applicable"] },
        { title: "Partners and suppliers", points: ["Supplier “where to buy” pages", "Partner and client case studies", "Event sponsorship pages"] },
        { title: "Local media and PR", points: ["Expert comments for news stories", "Data or surveys about your industry", "Community initiatives worth covering"] },
        { title: "Useful content", points: ["Guides others reference", "Pricing studies and checklists", "Free tools or calculators"] },
        { title: "Citations and reviews", points: ["Accurate listings on Pakistani directories", "Consistent details everywhere", "A steady review routine"] },
      ] },
      { type: "h2", text: "What to avoid" },
      { type: "compare", title: "Risky and safe off-page tactics", left: { label: "Risky", items: [
        "Buying link packages or guest posts with hidden payment",
        "Private blog networks",
        "Comment and forum spam",
        "Mass directory submissions to irrelevant sites",
      ] }, right: { label: "Safe", items: [
        "Earning links through relationships and useful content",
        "Labelling sponsored links with rel=\"sponsored\"",
        "Selective, relevant directories",
        "Genuine participation in industry communities",
      ] } },
      { type: "callout", tone: "warn", title: "Paid links must be disclosed", text: "Google asks site owners to mark paid or sponsored links with rel=\"sponsored\". Buying links that pass ranking credit without disclosure is a link scheme under Google’s spam policies." },
      { type: "h2", text: "How an off-page SEO expert plans the work" },
      { type: "video", title: "Building an off-page plan", steps: [
        { title: "Audit your current profile", text: "Review existing links, citations and reviews, and note anything toxic or inconsistent." },
        { title: "Study competitors", text: "See which relevant sites link to the businesses ranking above you, and which of those are realistic for you." },
        { title: "List relationship assets", text: "Associations you belong to, suppliers, partners, clients and events you are involved in." },
        { title: "Create something worth citing", text: "Publish a guide, price study or checklist that journalists and partners would reference." },
        { title: "Outreach and track", text: "Contact the most relevant sites personally, then track new links and mentions each month." },
      ] },
      { type: "h2", text: "Measuring off-page progress" },
      { type: "bars", title: "What to report each month", items: [
        { label: "New relevant referring domains", value: 5, display: "Core" },
        { label: "Review count and rating trend", value: 4, display: "Core" },
        { label: "Brand mentions found", value: 3, display: "Useful" },
        { label: "Citation consistency score", value: 3, display: "Useful" },
        { label: "Total backlinks", value: 1, display: "Misleading alone" },
      ], note: "Our recommended reporting priorities." },
      { type: "p", text: "Off-page work is part of every [SEO engagement](/services/seo/) we run. If you are not sure whether your existing links are helping or hurting, [ask for an audit](/contact/)." },
      { type: "sources", items: [SRC.spam, LINKS, SRC.local] },
    ],
    faqs: [
      { q: "What does an off-page SEO expert do?", a: "They build authority through relevant links, consistent citations, genuine reviews and brand mentions, using relationships and useful content rather than paid link schemes." },
      { q: "Is off-page SEO still important?", a: "Yes. Links remain an important ranking signal, and reviews and brand mentions also shape local rankings and how AI tools describe your business." },
      { q: "Is buying backlinks safe?", a: "Buying links that pass ranking credit without disclosure breaks Google’s spam policies and risks penalties. Sponsored links should be marked rel=\"sponsored\"." },
      { q: "How many backlinks do I need?", a: "There is no fixed number. A handful of relevant, trusted links usually does more than hundreds of low-quality ones." },
    ],
    related: [
      { label: "SEO services", href: "/services/seo/" },
      { label: "Content marketing", href: "/services/content/" },
      { label: "Request a link profile review", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 19 */
  {
    slug: "seo-audit-expert",
    title: "SEO Audit Expert: How to Identify Website Ranking Issues",
    keyword: "SEO audit expert",
    description: "How an SEO audit expert finds what is holding a website back: the audit process, the tools, the issues it covers and how to turn findings into a prioritised fix list your team can act on.",
    category: "Technical SEO",
    icon: "search-check",
    accent: "blue",
    answer: "An SEO audit expert identifies ranking issues by reviewing a site’s technical health, indexing, content quality, keyword targeting, internal links, backlinks and local signals, then comparing it with the sites ranking above it. A useful audit ends with a prioritised fix list ranked by impact and effort, written for the people who will implement it.",
    takeaways: [
      "An audit is only useful if it ends with a prioritised, actionable fix list.",
      "Good audits compare your site with the competitors actually ranking above you.",
      "Search Console data is the starting point, not a third-party score.",
      "Automated tool reports are inputs, not audits.",
      "Re-audit after major changes and at least once a year.",
    ],
    body: [
      { type: "h2", text: "What an SEO audit is for" },
      { type: "p", text: "An **SEO audit** answers a simple question: why is this site not getting the search traffic and enquiries it should? The answer may be technical, such as pages not indexed, content-related, such as pages that do not match search intent, or about authority, such as competitors having stronger links. An **SEO audit expert** finds the real constraint and tells you what to fix first." },
      { type: "process", title: "The audit process", steps: [
        { title: "Data", text: "Search Console and Analytics" },
        { title: "Crawl", text: "Technical and structural review" },
        { title: "Content", text: "Intent, quality, gaps" },
        { title: "Competitors", text: "Who ranks and why" },
        { title: "Priorities", text: "Fix list by impact and effort" },
      ] },
      { type: "h2", text: "What a complete audit covers" },
      { type: "table", caption: "Audit areas and typical findings", head: ["Area", "Typical findings"], rows: [
        ["Indexing", "Important pages not indexed, junk pages indexed, wrong canonicals"],
        ["Technical", "Slow mobile pages, broken links, redirect chains, missing HTTPS redirects"],
        ["Content", "Thin service pages, pages competing for the same keyword, outdated information"],
        ["Keywords", "High-impression queries with low clicks, missing pages for real demand"],
        ["Internal links", "Key pages buried deep, orphan pages, vague anchor text"],
        ["Off-page", "Few relevant links, toxic links, inconsistent citations"],
        ["Local", "Incomplete Business Profile, wrong categories, few recent reviews"],
      ] },
      { type: "h2", text: "Tool reports versus real audits" },
      { type: "compare", title: "Automated report versus expert audit", left: { label: "Automated tool report", items: [
        "Hundreds of warnings with no priority",
        "A generic health score",
        "Flags issues that may not matter",
        "No view of your business goals",
      ] }, right: { label: "Expert audit", items: [
        "A short list of what matters most",
        "Specific pages and queries named",
        "Explains impact and effort for each fix",
        "Tied to enquiries and revenue",
      ] } },
      { type: "h2", text: "How to read your own Search Console first" },
      { type: "video", title: "A self-check before you commission an audit", steps: [
        { title: "Performance report", text: "Sort queries by impressions. Look for queries with many impressions but few clicks; titles or content may not match intent." },
        { title: "Pages report", text: "Check how many pages are indexed and why others are excluded." },
        { title: "Core Web Vitals", text: "Note whether mobile URLs pass or fail." },
        { title: "Links report", text: "See which pages receive the most internal and external links." },
        { title: "Write down questions", text: "Bring these observations to the audit expert so the audit starts from your real data." },
      ] },
      { type: "h2", text: "Turning findings into action" },
      { type: "slides", title: "From audit to fix list", slides: [
        { title: "Rank by impact", points: ["Which fixes affect the most valuable pages?", "Which block indexing or conversions?", "Which are quick wins?"] },
        { title: "Assign owners", points: ["Developer tasks", "Content tasks", "Business Profile and reviews tasks"] },
        { title: "Set a timeline", points: ["Critical fixes in two weeks", "Content improvements over 60 days", "Authority building ongoing"] },
        { title: "Measure", points: ["Baseline numbers recorded", "Changes dated", "Review at 30, 60 and 90 days"] },
      ] },
      { type: "checklist", title: "What your audit document should include", items: [
        "An executive summary in plain language",
        "The top five issues ranked by impact",
        "Specific URLs and queries for each issue",
        "Recommended fix, owner and effort level",
        "Competitor comparison for key keywords",
        "Baseline metrics to measure progress",
      ] },
      { type: "p", text: "Our free audit for Islamabad and Pakistani businesses follows this format and arrives within 24 hours. [Request yours here](/contact/)." },
      { type: "sources", items: [GSC, VITALS, SRC.starter] },
    ],
    faqs: [
      { q: "What does an SEO audit expert check?", a: "Indexing, technical health, content quality and intent, keyword targeting, internal links, backlinks and local signals, compared against the competitors ranking above you." },
      { q: "How long does an SEO audit take?", a: "A focused audit of a small business site can be done in one to three days. Large sites with thousands of pages take longer." },
      { q: "Are free SEO audit tools enough?", a: "They are useful inputs but produce long, unprioritised lists. An expert audit focuses on what is actually limiting your results and what to fix first." },
      { q: "How often should I audit my website?", a: "At least once a year, and before and after any redesign, migration or major content change." },
    ],
    related: [
      { label: "Request a free SEO audit", href: "/contact/" },
      { label: "SEO services", href: "/services/seo/" },
      { label: "Web design and development", href: "/services/web-design/" },
    ],
  },

  /* ------------------------------------------------------------------ 20 */
  {
    slug: "link-building-expert",
    title: "Link Building Expert: How to Evaluate Their Work",
    keyword: "link building expert",
    description: "How to evaluate a link building expert: judging link quality, relevance and risk, reading a link report, spotting paid networks, and the outreach methods that earn links that last.",
    category: "SEO skills",
    icon: "link-2",
    accent: "amber",
    answer: "Evaluate a link building expert by the links themselves: each should come from a real, relevant site with its own audience, sit within useful content, and be explainable without payment. Ask for a full list of links built, check each one, look for patterns of private blog networks or paid placements, and judge results by rankings and traffic to the linked pages.",
    takeaways: [
      "Judge links by relevance, trust and editorial context, not by tool scores alone.",
      "Always ask for a complete list of every link built.",
      "Networks of similar-looking sites linking to each other are a red flag.",
      "Good link building looks like PR and partnerships, not purchases.",
      "Results show up as better rankings for the linked pages, usually over months.",
    ],
    body: [
      { type: "h2", text: "Why link building needs scrutiny" },
      { type: "p", text: "Links remain one of the strongest ranking signals, which is exactly why the market is full of shortcuts. Many “link building” packages sold in Pakistan are paid placements on networks built only to sell links. They may move rankings briefly before Google discounts them or penalises the site. A real **link building expert** earns links that would exist even if search engines did not." },
      { type: "h2", text: "How to judge a single link" },
      { type: "checklist", title: "Questions to ask about every link", items: [
        "Is the linking site real, with its own audience and regular content?",
        "Is it relevant to your industry or location?",
        "Is the link inside useful content, not a footer or a list of unrelated links?",
        "Would the link make sense to a reader if search engines did not exist?",
        "Is it free of undisclosed payment?",
        "Does the site link out to many unrelated topics such as casinos or loans?",
      ] },
      { type: "h2", text: "Red flags in a link report" },
      { type: "compare", title: "Warning signs versus healthy patterns", left: { label: "Warning signs", items: [
        "Dozens of new links in a week from unknown blogs",
        "Sites with similar designs and no real traffic",
        "Articles that exist only to place links",
        "Exact-match anchor text everywhere",
      ] }, right: { label: "Healthy patterns", items: [
        "A few links a month from relevant sites",
        "Links from associations, partners and media",
        "Natural anchor text such as your brand name",
        "Links to useful pages, not only the home page",
      ] } },
      { type: "h2", text: "Methods that earn lasting links" },
      { type: "slides", title: "Link building methods that hold up", slides: [
        { title: "Digital PR", points: ["Share data or expert commentary with journalists", "Respond to media requests in your field", "Publish surveys about your industry"] },
        { title: "Relationships", points: ["Suppliers and distributors", "Partners and clients", "Associations and chambers"] },
        { title: "Useful assets", points: ["Guides and checklists", "Price comparisons and calculators", "Local resource pages"] },
        { title: "Reclamation", points: ["Turn unlinked brand mentions into links", "Fix broken links pointing to your site", "Update outdated references"] },
      ] },
      { type: "video", title: "Auditing a link building provider’s work", steps: [
        { title: "Request the list", text: "Ask for every link built, with the date, URL and target page." },
        { title: "Spot-check ten links", text: "Open them. Are they real sites with real content and readers?" },
        { title: "Look for patterns", text: "Check whether many linking sites share designs, owners or hosting, a sign of a network." },
        { title: "Check the targets", text: "See whether linked pages improved in Search Console after the links appeared." },
        { title: "Decide", text: "Keep providers whose links you would be happy to show a Google reviewer. Stop the rest." },
      ] },
      { type: "bars", title: "Link value: what tends to matter most", items: [
        { label: "Topical relevance", value: 5, display: "Very high" },
        { label: "Trust and real audience", value: 5, display: "Very high" },
        { label: "Editorial placement", value: 4, display: "High" },
        { label: "Third-party authority score", value: 2, display: "Indicator only" },
        { label: "Raw link count", value: 1, display: "Low" },
      ], note: "Our view of link quality factors." },
      { type: "callout", tone: "tip", title: "Think like a reviewer", text: "If you would be embarrassed to explain how you got a link to a journalist or a Google reviewer, it is probably not a link worth having." },
      { type: "p", text: "Link earning is part of our [SEO service](/services/seo/). If you have bought links in the past and are worried, [ask for a link audit](/contact/)." },
      { type: "sources", items: [SRC.spam, LINKS, CRAWLABLE] },
    ],
    faqs: [
      { q: "How do I know if a link building expert is good?", a: "Ask for every link they built and check them: real, relevant sites with their own audiences, links inside useful content, and no sign of payment or networks." },
      { q: "What is a private blog network?", a: "A group of sites built or bought mainly to link to other sites for ranking purposes. Google treats them as link schemes." },
      { q: "How many links should a link builder get per month?", a: "Quality matters more than quantity. A few relevant, editorial links a month usually outperform dozens of low-quality ones." },
      { q: "Can bad links hurt my site?", a: "Google mostly ignores spammy links, but participating in link schemes can lead to manual actions. If you bought links, review them with an expert." },
    ],
    related: [
      { label: "SEO services", href: "/services/seo/" },
      { label: "Content marketing", href: "/services/content/" },
      { label: "Request a link audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 21 */
  {
    slug: "real-estate-seo-expert",
    title: "Real Estate SEO Expert in Islamabad: Lead Generation Guide",
    keyword: "real estate SEO expert",
    description: "How a real estate SEO expert generates property leads in Islamabad and Rawalpindi: society and project pages, overseas Pakistani buyers, portal competition, trust signals and lead tracking.",
    category: "Industry SEO",
    icon: "building-2",
    accent: "violet",
    answer: "A real estate SEO expert generates property leads by building detailed pages for each society, project and phase you sell in, creating content for overseas Pakistani buyers, targeting specific searches property portals handle poorly, publishing trust signals such as approvals and completed projects, and tracking calls and WhatsApp enquiries back to the page that produced them.",
    takeaways: [
      "Portals win generic property searches; agencies and developers win specific ones.",
      "Society, project and phase pages are the core of real estate SEO in the twin cities.",
      "Overseas Pakistanis are a high-value audience that searches in English and needs reassurance.",
      "Trust signals, approvals and completed-project evidence drive both rankings and conversions.",
      "Track enquiries by page, because property leads are few but valuable.",
    ],
    body: [
      { type: "h2", text: "The real estate search landscape in Islamabad" },
      { type: "p", text: "Property searches in Islamabad and Rawalpindi are dominated by listing portals for broad terms like “plots for sale Islamabad”. Competing head-on wastes budget. A **real estate SEO expert** focuses on searches the portals answer badly: specific societies, phases and blocks, documentation questions, payment plans and overseas buying." },
      { type: "compare", title: "Where to compete in property search", left: { label: "Portals usually win", items: [
        "Plots for sale Islamabad",
        "Houses for rent Rawalpindi",
        "Property prices Pakistan",
      ] }, right: { label: "Agencies and developers can win", items: [
        "Specific society, phase and block searches",
        "Payment plan and possession questions",
        "Buying property from the UK, Gulf or Canada",
        "File verification and documentation guidance",
      ] } },
      { type: "h2", text: "Society, project and phase pages" },
      { type: "p", text: "For each society or project you genuinely deal in, build a page with real information: location and access routes, approval status, plot and unit sizes, payment plans, development progress with dated photos, nearby schools and hospitals, and an honest note on risks. These pages rank for specific searches and reassure buyers." },
      { type: "slides", title: "What a strong project page includes", slides: [
        { title: "Facts", points: ["Location, access routes and map", "Approval and NOC status", "Plot or unit sizes and prices with a date"] },
        { title: "Progress", points: ["Dated construction photos", "Possession timelines", "Amenities delivered so far"] },
        { title: "Buying", points: ["Payment plan table", "Documentation required", "Transfer process explained"] },
        { title: "Trust", points: ["Your registration and office address", "Named team members", "Reviews from past buyers"] },
      ] },
      { type: "h2", text: "Overseas Pakistani buyers" },
      { type: "p", text: "Islamabad attracts significant investment from Pakistanis abroad. They search in English from the UK, the Gulf, North America and Europe, often at night Pakistan time, and they need far more reassurance than local buyers. Content that answers their specific worries converts well and faces less competition." },
      { type: "checklist", title: "Content for overseas buyers", items: [
        "Buying property in Islamabad from abroad: step-by-step guides",
        "Power of attorney and document verification explained",
        "Remittance and payment guidance",
        "Video walkthroughs and virtual site visits",
        "WhatsApp contact that works across time zones",
        "Clear company registration and office details",
      ] },
      { type: "h2", text: "Generating and tracking leads" },
      { type: "video", title: "Building a property lead engine", steps: [
        { title: "List your inventory", text: "Map every society, project and phase you sell in, and the questions buyers ask about each." },
        { title: "Build priority pages", text: "Start with the three projects that generate the most revenue, and make their pages the best on the web." },
        { title: "Add overseas content", text: "Publish guides for overseas buyers and link them to the relevant project pages." },
        { title: "Strengthen local presence", text: "Optimise your Google Business Profile and earn reviews from completed deals." },
        { title: "Track every enquiry", text: "Track calls, WhatsApp clicks and forms by page, so you know which projects SEO is selling." },
      ] },
      { type: "stats", title: "Real estate SEO benchmarks to watch", items: [
        { value: "2–4 mo", label: "Typical time for project pages to rank" },
        { value: "6–12 mo", label: "For broader area and city terms" },
        { value: "High", label: "Value per lead from overseas buyers" },
      ] },
      { type: "p", text: "Read our full [real estate SEO guide](/seo-for/seo-for-real-estate/) or [request an audit](/contact/) of your property website." },
      { type: "sources", items: [SRC.helpful, SRC.local, RATER] },
    ],
    faqs: [
      { q: "How can a real estate agency compete with property portals?", a: "Target specific societies, phases, payment plans, documentation questions and overseas buyer searches, where portals are weaker and enquiries convert better." },
      { q: "What content attracts overseas Pakistani property buyers?", a: "Guides on buying from abroad, power of attorney, document verification, remittances and payment plans, plus virtual tours and clear company registration details." },
      { q: "Should property prices be on the website?", a: "Yes, with a visible last-updated date. Serious buyers filter by price and often skip listings that hide it." },
      { q: "How long does real estate SEO take in Islamabad?", a: "Specific project and society pages often rank within two to four months. Broad area and city terms take six to twelve months." },
    ],
    related: [
      { label: "SEO for real estate in Pakistan", href: "/seo-for/seo-for-real-estate/" },
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "Google Ads management", href: "/services/ppc/" },
    ],
  },

  /* ------------------------------------------------------------------ 22 */
  {
    slug: "healthcare-seo-expert",
    title: "Healthcare SEO Expert: How to Attract More Patients",
    keyword: "healthcare SEO expert",
    description: "How a healthcare SEO expert helps hospitals and clinics in Pakistan attract more patients: E-E-A-T for medical content, doctor profiles, procedure pages, local search and patient-friendly websites.",
    category: "Industry SEO",
    icon: "stethoscope",
    accent: "rose",
    answer: "A healthcare SEO expert attracts more patients by making medical content trustworthy and findable: detailed doctor profiles with verifiable PM&DC registration and qualifications, accurate procedure and condition pages reviewed by clinicians, transparent pricing where possible, an optimised Google Business Profile for each location, and fast mobile pages with easy appointment booking.",
    takeaways: [
      "Health is a “Your Money or Your Life” topic, so Google applies stricter quality standards.",
      "Named, qualified authors and reviewers are essential for medical content.",
      "Doctor profiles and procedure pages convert better than general health articles.",
      "Each hospital or clinic location needs its own optimised Business Profile.",
      "Never publish unverified medical claims or fake reviews.",
    ],
    body: [
      { type: "h2", text: "Why healthcare SEO is different" },
      { type: "p", text: "Google’s quality rater guidelines treat health as a “Your Money or Your Life” (YMYL) topic, where inaccurate information can cause real harm. Pages in this category are held to a higher standard of experience, expertise, authoritativeness and trust (E-E-A-T). A **healthcare SEO expert** builds that trust into every page rather than chasing traffic with generic health articles." },
      { type: "stats", title: "What patients look for before booking", items: [
        { value: "Doctor", label: "Qualifications, specialisation and experience" },
        { value: "Cost", label: "Consultation and procedure prices" },
        { value: "Location", label: "Distance, timings and parking" },
        { value: "Reviews", label: "Other patients’ experiences" },
      ] },
      { type: "h2", text: "Building trust signals into the website" },
      { type: "checklist", title: "Trust signals for healthcare websites", items: [
        "Doctor profiles with full name, photo, qualifications and PM&DC registration number",
        "Medical content written or reviewed by named clinicians, with a review date",
        "Clear hospital or clinic registration and contact details",
        "Transparent consultation fees or price ranges where possible",
        "Patient privacy and data handling information",
        "Genuine patient reviews, never incentivised or invented",
      ] },
      { type: "h2", text: "The pages that attract patients" },
      { type: "slides", title: "Healthcare page types that perform", slides: [
        { title: "Doctor profiles", points: ["Specialisation and qualifications", "Conditions treated and procedures performed", "Timings and how to book"] },
        { title: "Procedure pages", points: ["What the procedure involves", "Preparation and recovery", "Cost range and what is included"] },
        { title: "Department pages", points: ["Services offered", "Doctors in the department", "Facilities and equipment"] },
        { title: "Location pages", points: ["Address, map and directions", "Timings including Friday", "Parking and accessibility"] },
      ] },
      { type: "callout", tone: "warn", title: "Accuracy over volume", text: "Do not publish medical content without clinical review, and avoid promising outcomes. Thin or inaccurate health content can damage rankings for the whole site, as well as patient trust." },
      { type: "h2", text: "Local search for hospitals and clinics" },
      { type: "p", text: "Most patients choose care close to home or work. Each location needs its own Google Business Profile with the right categories (for example “Hospital”, “Medical clinic” or a specialist category), accurate timings, real photos and a steady review routine. Departments with distinct services may also be eligible for their own profiles under Google’s guidelines." },
      { type: "video", title: "A healthcare SEO roadmap", steps: [
        { title: "Audit trust signals", text: "Check that every doctor, department and location page shows real credentials and contact details." },
        { title: "Fix the local foundation", text: "Optimise each location’s Business Profile and make name, address and phone consistent everywhere." },
        { title: "Build procedure pages", text: "Create clinically reviewed pages for your highest-value procedures, with costs and preparation details." },
        { title: "Make booking easy", text: "Add click-to-call, WhatsApp and online booking on mobile, and track every enquiry." },
        { title: "Earn authority", text: "Seek links from medical associations, universities and health journalism, and keep content reviewed regularly." },
      ] },
      { type: "bars", title: "Typical healthcare SEO timeline", items: [
        { label: "Local pack improvements", value: 2, display: "1–3 months" },
        { label: "Doctor and procedure pages ranking", value: 4, display: "3–6 months" },
        { label: "Competitive specialty terms", value: 6, display: "6–12 months" },
      ], note: "Indicative ranges; stricter quality assessment makes healthcare slower than many categories." },
      { type: "p", text: "See our [medical and healthcare SEO guide](/seo-for/seo-for-medical/) or [request an audit](/contact/) of your hospital or clinic website." },
      { type: "sources", items: [RATER, SRC.helpful, SRC.gbp] },
    ],
    faqs: [
      { q: "What does a healthcare SEO expert do?", a: "They make medical websites trustworthy and findable: doctor profiles with credentials, clinically reviewed procedure pages, optimised Business Profiles for each location, and easy mobile booking." },
      { q: "What is E-E-A-T in healthcare SEO?", a: "Experience, expertise, authoritativeness and trust. Google’s quality guidelines apply stricter standards to health content, so named, qualified authors and accurate information are essential." },
      { q: "Should hospitals publish treatment prices?", a: "Where possible, yes. Cost is one of the most searched questions, and ranges with clear inclusions help patients choose and reduce unqualified enquiries." },
      { q: "How long does SEO take for a hospital or clinic?", a: "Local visibility can improve within one to three months. Doctor and procedure pages often take three to six months, and competitive specialty terms longer." },
    ],
    related: [
      { label: "SEO for medical and healthcare", href: "/seo-for/seo-for-medical/" },
      { label: "SEO for clinics and dental", href: "/seo-for/seo-for-clinics/" },
      { label: "Local SEO services", href: "/services/local-seo/" },
    ],
  },
];
