import type { PostInput } from "@/lib/blog";
import { SRC } from "./part1";

const VITALS = { label: "web.dev: Core Web Vitals", href: "https://web.dev/articles/vitals" };
const CANON = { label: "Google Search Central: How to specify a canonical URL", href: "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls" };
const SD = { label: "Google Search Central: Introduction to structured data", href: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" };
const ECOM = { label: "Google Search Central: Ecommerce SEO best practices", href: "https://developers.google.com/search/docs/specialty/ecommerce" };
const SHOPIFY = { label: "Shopify Help Center: Search engine optimization", href: "https://help.shopify.com/en/manual/promoting-marketing/seo" };

export const PART4: PostInput[] = [
  /* ------------------------------------------------------------------ 13 */
  {
    slug: "wordpress-seo-expert",
    title: "WordPress SEO Expert in Islamabad: Complete Guide",
    keyword: "WordPress SEO expert",
    description: "What a WordPress SEO expert fixes: theme and plugin bloat, Rank Math or Yoast setup, permalinks, speed, schema and security, with a practical checklist for Islamabad business websites.",
    category: "Platform SEO",
    icon: "file-code",
    accent: "blue",
    answer: "A WordPress SEO expert makes a WordPress site fast, crawlable and well structured: removing plugin and theme bloat, configuring an SEO plugin such as Rank Math or Yoast correctly, setting clean permalinks, fixing duplicate archive pages, adding schema, compressing images and hardening security. Most Islamabad WordPress sites gain more from these fixes than from new content.",
    takeaways: [
      "WordPress is SEO-friendly, but themes, page builders and plugins often make it slow and messy.",
      "One SEO plugin, configured properly, is enough; two conflict.",
      "Tag, author and date archives often create thin duplicate pages that should be noindexed.",
      "Speed fixes on WordPress usually come from images, caching and removing plugins.",
      "Updates and security matter: a hacked site loses rankings fast.",
    ],
    body: [
      { type: "h2", text: "Why WordPress sites need specialist SEO attention" },
      { type: "p", text: "WordPress powers a large share of Pakistani business websites because it is flexible and cheap to start. The same flexibility creates problems: heavy themes, page builders that load scripts on every page, dozens of plugins, and default settings that publish thin archive pages. A **WordPress SEO expert** knows where these problems hide and how to fix them without breaking the site." },
      { type: "stats", title: "Common findings on Islamabad WordPress audits", items: [
        { value: "Slow", label: "Mobile pages weighed down by sliders and page builders" },
        { value: "Thin", label: "Tag, author and date archives indexed by default" },
        { value: "Clash", label: "Two SEO plugins installed at the same time" },
        { value: "Outdated", label: "Plugins and themes not updated for months" },
      ] },
      { type: "h2", text: "The WordPress SEO checklist" },
      { type: "checklist", title: "Settings and fixes a WordPress SEO expert checks", items: [
        "Settings > Reading: the “Discourage search engines” box is unticked on the live site",
        "Permalinks set to a clean post name structure",
        "One SEO plugin (Rank Math or Yoast) with titles, sitemaps and schema configured",
        "Tag, author, date and attachment pages noindexed or disabled where thin",
        "Images compressed, resized and served in modern formats",
        "A caching plugin and, ideally, a CDN in place",
        "Unused plugins and themes deleted, not just deactivated",
        "HTTPS enforced with no mixed content",
        "Core, theme and plugins updated, with backups",
      ] },
      { type: "h2", text: "Speed: the most common WordPress problem" },
      { type: "bars", title: "Typical sources of slow WordPress pages", items: [
        { label: "Uncompressed images", value: 5, display: "Very common" },
        { label: "Page builder scripts and sliders", value: 4, display: "Common" },
        { label: "Too many plugins", value: 4, display: "Common" },
        { label: "Cheap shared hosting", value: 3, display: "Frequent" },
        { label: "No caching", value: 3, display: "Frequent" },
      ], note: "From our audits of WordPress sites in Islamabad and Rawalpindi." },
      { type: "p", text: "Fix images first: they are usually the biggest and easiest win. Then remove sliders and plugins you do not need, add caching, and consider better hosting if server response time is slow. Measure with PageSpeed Insights on mobile before and after each change." },
      { type: "h2", text: "Configuring Rank Math or Yoast properly" },
      { type: "slides", title: "SEO plugin setup that actually matters", slides: [
        { title: "Titles and descriptions", points: ["Unique title for every key page", "Service and area in the title naturally", "Descriptions written to earn the click"] },
        { title: "Sitemaps", points: ["Include pages, posts and services", "Exclude tags, attachments and thin archives", "Submit the sitemap in Search Console"] },
        { title: "Schema", points: ["Organisation or LocalBusiness details complete", "Article schema on posts", "FAQ schema only where FAQs are visible"] },
        { title: "Redirects", points: ["301 redirects for changed URLs", "Monitor 404 errors", "No redirect chains"] },
      ] },
      { type: "callout", tone: "warn", title: "Do not run two SEO plugins", text: "Installing Yoast and Rank Math together, or adding an all-in-one plugin on top, creates duplicate meta tags and conflicting sitemaps. Pick one and remove the rest." },
      { type: "h2", text: "Content structure on WordPress" },
      { type: "p", text: "Use pages for services and locations, and posts for articles. Link each service page to the area pages it relates to, and keep your most important pages within three clicks of the home page. Categories should be few and meaningful; tags are usually unnecessary for business sites." },
      { type: "video", title: "A 30-minute WordPress SEO health check", steps: [
        { title: "Check visibility settings", text: "In Settings > Reading, confirm search engines are not discouraged. This single checkbox has hidden many Pakistani sites from Google." },
        { title: "Review plugins", text: "List all plugins, remove anything unused, and confirm only one SEO plugin is active." },
        { title: "Test speed", text: "Run PageSpeed Insights on mobile for the home page and one service page. Note the largest images." },
        { title: "Check the sitemap", text: "Open your sitemap and remove thin archives such as tags and author pages from it." },
        { title: "Update and back up", text: "Back up the site, then update WordPress core, theme and plugins." },
      ] },
      { type: "p", text: "We build and optimise WordPress sites for Islamabad businesses, and teach a short [WordPress course](/courses/wordpress/) for people who want to manage their own. For a review of your site, see our [web design and development service](/services/web-design/) or [request an audit](/contact/)." },
      { type: "sources", items: [VITALS, SD, SRC.starter] },
    ],
    faqs: [
      { q: "Is WordPress good for SEO?", a: "Yes. WordPress is SEO-friendly when configured properly. Problems usually come from heavy themes, page builders, too many plugins and default settings that index thin archive pages." },
      { q: "Rank Math or Yoast: which is better?", a: "Both work well. What matters is configuring one plugin properly and not running two at the same time." },
      { q: "Why is my WordPress site slow?", a: "Usually large images, page builder scripts, sliders, too many plugins, no caching or slow shared hosting. Fix images first, then plugins and caching." },
      { q: "Should I noindex WordPress tag pages?", a: "For most business sites, yes. Tag, author and date archives are usually thin duplicates of existing content and add little value in search." },
    ],
    related: [
      { label: "Web design and development", href: "/services/web-design/" },
      { label: "WordPress development course", href: "/courses/wordpress/" },
      { label: "Request a WordPress SEO audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 14 */
  {
    slug: "shopify-seo-expert",
    title: "Shopify SEO Expert in Islamabad: How to Grow Store Traffic",
    keyword: "Shopify SEO expert",
    description: "How a Shopify SEO expert grows organic store traffic: collection page strategy, product content, duplicate URLs, apps and speed, structured data and the Pakistani buying journey.",
    category: "Ecommerce SEO",
    icon: "shopping-bag",
    accent: "green",
    answer: "A Shopify SEO expert grows store traffic by turning collection pages into strong category landing pages, writing unique product content, keeping internal links pointing to canonical product URLs, trimming apps that slow the store, completing product structured data and building content around how Pakistani shoppers search, including price, delivery and cash-on-delivery questions.",
    takeaways: [
      "Collection pages usually carry more ranking potential than individual products.",
      "Unique product descriptions beat manufacturer copy shared by every reseller.",
      "Shopify creates duplicate product URLs inside collections; internal links should use the canonical URL.",
      "Every app adds weight; remove those you do not use.",
      "Pakistani shoppers search for price, delivery time and cash on delivery; answer those on the page.",
    ],
    body: [
      { type: "h2", text: "How Shopify SEO differs from a normal website" },
      { type: "p", text: "Shopify handles a lot of SEO basics well: sitemaps, canonical tags, HTTPS and clean themes. But it also has fixed URL structures, apps that inject scripts, and a habit of creating multiple paths to the same product. A **Shopify SEO expert** works within those constraints rather than fighting them." },
      { type: "compare", title: "What Shopify handles and what you must do", left: { label: "Shopify does for you", items: [
        "Automatic XML sitemap",
        "Canonical tags on product pages",
        "HTTPS and hosting performance",
        "Basic product structured data in most themes",
      ] }, right: { label: "You still need to do", items: [
        "Write unique collection and product content",
        "Fix internal links to canonical product URLs",
        "Remove unused apps and heavy scripts",
        "Plan categories around real search demand",
      ] } },
      { type: "h2", text: "Collection pages: your biggest opportunity" },
      { type: "p", text: "Shoppers usually search for a category before a specific product: “lawn suits online Pakistan”, “men’s leather wallets”, “organic skincare Islamabad”. Collection pages are where those searches land. Add a short, useful introduction, link to sub-collections, and include an FAQ covering sizing, delivery and returns. Keep the product grid visible above the fold." },
      { type: "slides", title: "Building a collection page that ranks", slides: [
        { title: "Choose the right collections", points: ["Match collections to search demand", "Avoid dozens of near-duplicate collections", "Use clear, descriptive handles"] },
        { title: "Write the introduction", points: ["Two short paragraphs that help shoppers choose", "Mention materials, sizes or uses", "Link to related collections"] },
        { title: "Answer buyer questions", points: ["Delivery time to major cities", "Cash on delivery and returns", "Size guides where relevant"] },
        { title: "Help Google understand it", points: ["Unique title and description", "Descriptive image alt text", "Products linked with canonical URLs"] },
      ] },
      { type: "h2", text: "Product pages and duplicate URLs" },
      { type: "p", text: "On many themes, a product is reachable both at /products/name and at /collections/category/products/name. Shopify sets the canonical tag to the /products/ version, but internal links from collection grids often point to the longer version. A Shopify SEO expert edits the theme so links go directly to the canonical URL, which concentrates signals on one address." },
      { type: "callout", tone: "tip", title: "Write your own product copy", text: "If you resell products, every other reseller probably uses the same supplier description. Rewrite descriptions with your own details: fabric, fit, how it washes, who it suits, what is in the box. Unique content is one of the few advantages a small store has over marketplaces." },
      { type: "h2", text: "Speed and apps" },
      { type: "bars", title: "Where Shopify store weight usually comes from", items: [
        { label: "Apps loading scripts on every page", value: 5, display: "Biggest" },
        { label: "Large hero images and videos", value: 4, display: "Large" },
        { label: "Theme features you do not use", value: 3, display: "Medium" },
        { label: "Third-party chat and popups", value: 3, display: "Medium" },
      ], note: "From audits of Pakistani Shopify stores." },
      { type: "h2", text: "Content around the Pakistani buying journey" },
      { type: "p", text: "Pakistani shoppers often check delivery times, cash on delivery and return policies before ordering, and compare prices with marketplaces. Clear answers on collection and product pages, plus guides such as size charts or care instructions, earn rankings for long-tail searches and reduce abandoned carts." },
      { type: "video", title: "A Shopify SEO sprint in five steps", steps: [
        { title: "Map demand to collections", text: "Use Search Console and keyword research to confirm which categories people search for, then align collections to them." },
        { title: "Fix internal links", text: "Update the theme so product links point to the canonical /products/ URL." },
        { title: "Write collection content", text: "Add short introductions and FAQs to the top ten collections." },
        { title: "Trim apps", text: "Remove unused apps and check that removed apps did not leave scripts behind in the theme." },
        { title: "Track revenue", text: "Use Google Analytics 4 ecommerce tracking to measure organic revenue, not just sessions." },
      ] },
      { type: "p", text: "Our [e-commerce SEO guide](/seo-for/seo-for-ecommerce/) covers category architecture in depth. For a Shopify audit, [contact us](/contact/)." },
      { type: "sources", items: [SHOPIFY, ECOM, CANON] },
    ],
    faqs: [
      { q: "Is Shopify good for SEO?", a: "Yes. Shopify handles sitemaps, canonical tags and hosting well. Results depend on collection strategy, unique product content, app weight and internal linking." },
      { q: "Why does Shopify create duplicate product URLs?", a: "Products can be reached through collection paths as well as the main /products/ URL. Shopify sets a canonical tag, but internal links should also point to the canonical version." },
      { q: "Do Shopify apps hurt SEO?", a: "They can. Many apps load scripts on every page, slowing the store. Remove apps you do not use and check the theme for leftover code." },
      { q: "Should I add blog content to a Shopify store?", a: "Yes, if it helps shoppers choose: buying guides, size and care guides, and comparisons. Link those articles to the relevant collections." },
    ],
    related: [
      { label: "SEO for e-commerce in Pakistan", href: "/seo-for/seo-for-ecommerce/" },
      { label: "Web design and development", href: "/services/web-design/" },
      { label: "Request a store audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 15 */
  {
    slug: "ecommerce-seo-expert",
    title: "Ecommerce SEO Expert in Islamabad: How to Increase Sales",
    keyword: "ecommerce SEO expert",
    description: "How an ecommerce SEO expert increases online sales in Pakistan: category architecture, faceted navigation, product content, structured data, marketplace competition and revenue tracking.",
    category: "Ecommerce SEO",
    icon: "shopping-cart",
    accent: "amber",
    answer: "An ecommerce SEO expert increases sales by building a category structure that matches how people search, controlling faceted navigation so filters do not create thousands of thin URLs, writing unique category and product content, adding product structured data, targeting long-tail searches marketplaces handle badly, and measuring organic revenue rather than traffic.",
    takeaways: [
      "Category architecture is the foundation of ecommerce SEO.",
      "Uncontrolled filters can create thousands of near-duplicate URLs that waste crawl budget.",
      "Marketplaces win broad terms; independent stores win specific, long-tail searches.",
      "Product structured data helps listings show price and availability in results.",
      "Measure organic revenue and conversion rate, not sessions.",
    ],
    body: [
      { type: "h2", text: "Why ecommerce SEO is its own discipline" },
      { type: "p", text: "An online store has hundreds or thousands of pages, products that go in and out of stock, filters that multiply URLs and competition from marketplaces with huge budgets. General SEO advice does not cover this well. An **ecommerce SEO expert** focuses on structure, scale and revenue." },
      { type: "process", title: "The ecommerce SEO stack", steps: [
        { title: "Architecture", text: "Categories that match demand" },
        { title: "Crawl control", text: "Filters and parameters managed" },
        { title: "Content", text: "Unique category and product copy" },
        { title: "Rich results", text: "Product structured data" },
        { title: "Revenue", text: "Organic sales measured" },
      ] },
      { type: "h2", text: "Category architecture that matches search demand" },
      { type: "p", text: "Start from what customers search, not from how your warehouse is organised. If people search “bridal shoes”, “khussa for women” and “heels for wedding”, those may deserve their own categories or subcategories. Keep the structure shallow: home, category, subcategory, product." },
      { type: "h2", text: "Faceted navigation: the silent ranking killer" },
      { type: "p", text: "Filters for size, colour, price and brand are great for shoppers but can generate thousands of URL combinations. Google spends its crawl effort on these near-duplicates instead of your real pages. An ecommerce SEO expert decides which filter combinations deserve indexable pages (for example “red lawn suits”) and keeps the rest out of the index." },
      { type: "table", caption: "Handling filters", head: ["Filter type", "Typical approach"], rows: [
        ["High-demand combinations (e.g. brand + category)", "Indexable landing page with unique content"],
        ["Sort order (price low to high)", "Not indexed; canonical to the base category"],
        ["Multiple selected filters", "Not indexed; avoid crawlable links where possible"],
        ["Price ranges", "Usually not indexed"],
      ] },
      { type: "h2", text: "Competing with marketplaces" },
      { type: "compare", title: "Where to compete", left: { label: "Where marketplaces usually win", items: [
        "Broad terms like “online shopping Pakistan”",
        "Generic product names sold by many sellers",
        "Price-only comparisons",
      ] }, right: { label: "Where your store can win", items: [
        "Specific products with detailed specifications",
        "Buying guides and comparisons",
        "Brand searches and niche categories",
        "Questions about delivery, sizing and care",
      ] } },
      { type: "h2", text: "Product content and structured data" },
      { type: "slides", title: "Product page essentials", slides: [
        { title: "Content", points: ["Unique description with real details", "Specifications in a clear table", "Delivery, returns and COD information"] },
        { title: "Media", points: ["Several real photos, compressed", "Descriptive alt text", "Video where it helps buying decisions"] },
        { title: "Structured data", points: ["Product name, image, price and currency", "Availability kept accurate", "Genuine reviews only, never invented ratings"] },
        { title: "Out of stock", points: ["Keep the page live if it returns soon", "Link to alternatives", "Redirect permanently discontinued products to the category"] },
      ] },
      { type: "stats", title: "What to measure in ecommerce SEO", items: [
        { value: "Revenue", label: "Organic sales in Google Analytics 4" },
        { value: "CVR", label: "Conversion rate of organic visitors" },
        { value: "AOV", label: "Average order value from search" },
        { value: "Indexed", label: "Share of real products and categories indexed" },
      ] },
      { type: "video", title: "Auditing an online store", steps: [
        { title: "Crawl the store", text: "Crawl the site and count how many URLs exist compared with real products and categories." },
        { title: "Check index coverage", text: "In Search Console, see which important pages are not indexed and which filter URLs are." },
        { title: "Review top categories", text: "Compare your top categories with competitors on content, products shown and internal links." },
        { title: "Validate structured data", text: "Check product markup for errors and confirm prices match what customers see." },
        { title: "Connect to revenue", text: "Make sure organic revenue is tracked so every change can be judged by sales." },
      ] },
      { type: "p", text: "Read our [e-commerce SEO guide for Pakistan](/seo-for/seo-for-ecommerce/) or [request a store audit](/contact/)." },
      { type: "sources", items: [ECOM, CANON, SD] },
    ],
    faqs: [
      { q: "What does an ecommerce SEO expert do?", a: "They build category structures around search demand, control faceted navigation, improve category and product content, add product structured data, and measure organic revenue." },
      { q: "How can a small online store compete with Daraz?", a: "Target specific products, niche categories, buying guides and questions about delivery, sizing and care. Marketplaces handle broad terms well and specific ones poorly." },
      { q: "Should filter pages be indexed?", a: "Only high-demand combinations that deserve their own landing page with unique content. Most sort and multi-filter URLs should stay out of the index." },
      { q: "What should happen to out-of-stock product pages?", a: "Keep them live with alternatives if the product returns soon. Redirect permanently discontinued products to the most relevant category." },
    ],
    related: [
      { label: "SEO for e-commerce in Pakistan", href: "/seo-for/seo-for-ecommerce/" },
      { label: "Google Ads management", href: "/services/ppc/" },
      { label: "Request a store audit", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 16 */
  {
    slug: "google-maps-seo-expert",
    title: "Google Maps SEO Expert: How to Choose the Right Specialist",
    keyword: "Google Maps SEO expert",
    description: "How to choose a Google Maps SEO expert: the services they should offer, the questions to ask, the tactics that get profiles suspended, and how to measure Maps performance properly.",
    category: "Local SEO",
    icon: "map",
    accent: "rose",
    answer: "Choose a Google Maps SEO expert who works only within Google Business Profile guidelines, can show Maps results for businesses in your category, explains how relevance, distance and prominence apply to you, and reports on calls, direction requests and website clicks from your profile. Avoid anyone who suggests keyword-stuffed names, fake addresses or bought reviews.",
    takeaways: [
      "Maps SEO is mostly Google Business Profile work plus reviews, citations and local content.",
      "Good specialists explain what they can and cannot influence, including distance.",
      "Suspension risks come from names with keywords, fake addresses and fake reviews.",
      "Measure Maps success with calls, direction requests and website clicks from the profile.",
      "Results usually appear within weeks, faster than organic website rankings.",
    ],
    body: [
      { type: "h2", text: "What a Google Maps SEO expert actually does" },
      { type: "p", text: "A **Google Maps SEO expert** improves how often and how prominently your business appears in Google Maps and in the local pack, the map results shown above normal search results. The work centres on your Google Business Profile, supported by reviews, consistent citations and website pages that reinforce your location and services." },
      { type: "process", title: "The Maps SEO workflow", steps: [
        { title: "Profile audit", text: "Categories, services, details" },
        { title: "Optimisation", text: "Photos, products, Q&A, posts" },
        { title: "Reviews", text: "A steady, genuine routine" },
        { title: "Citations", text: "Consistent details everywhere" },
        { title: "Reporting", text: "Calls, directions, clicks" },
      ] },
      { type: "h2", text: "Questions to ask before hiring" },
      { type: "slides", title: "Interviewing a Google Maps specialist", slides: [
        { title: "About results", points: ["Can you show Maps results in my category?", "Which city or area were they in?", "How long did movement take?"] },
        { title: "About method", points: ["Which categories would you choose for me and why?", "How will you increase reviews?", "Will you change my business name?"] },
        { title: "About risk", points: ["Have any of your clients been suspended?", "What do you do if a profile is suspended?", "Do you use virtual offices?"] },
        { title: "About reporting", points: ["Which profile metrics will you report?", "How will you track calls from Maps?", "How often will we review progress?"] },
      ] },
      { type: "h2", text: "Tactics that get profiles suspended" },
      { type: "compare", title: "Risky shortcuts versus safe practice", left: { label: "Risky shortcuts", items: [
        "Adding keywords to the business name",
        "Using a virtual office or someone else’s address",
        "Buying reviews or reviewing from staff accounts",
        "Creating several profiles for one location",
      ] }, right: { label: "Safe, effective practice", items: [
        "Your real-world name exactly as customers see it",
        "A staffed address or a properly set service area",
        "Asking real customers for honest reviews",
        "One complete, actively updated profile per location",
      ] } },
      { type: "callout", tone: "warn", title: "A suspension costs more than slow growth", text: "While a profile is suspended you disappear from Maps entirely, and reinstatement can take weeks. Any short-term gain from a shortcut rarely survives that." },
      { type: "h2", text: "How to measure Maps performance" },
      { type: "stats", title: "Business Profile metrics that matter", items: [
        { value: "Calls", label: "Phone calls made from the profile" },
        { value: "Directions", label: "Requests for directions to your premises" },
        { value: "Website", label: "Clicks to your site from the profile" },
        { value: "Searches", label: "Terms people used to find you" },
      ] },
      { type: "p", text: "Rankings in Maps vary by the searcher’s exact location, so a single rank check from one place is misleading. Good specialists use grid-based tracking across your service area and combine it with the profile’s own performance data." },
      { type: "video", title: "Choosing your Google Maps SEO expert", steps: [
        { title: "Check your starting point", text: "Search your main service from a few locations near you and note where you appear." },
        { title: "Shortlist by evidence", text: "Pick specialists who can show Maps results in your category and city." },
        { title: "Ask about suspensions", text: "Listen for a clear commitment to Google’s guidelines and a plan if something goes wrong." },
        { title: "Agree the metrics", text: "Settle on calls, directions and website clicks as the core measures, with grid rank tracking." },
        { title: "Review after 60 days", text: "Most profile improvements show within weeks; judge progress at 60 days." },
      ] },
      { type: "p", text: "Maps work is the core of our [local SEO service](/services/local-seo/). The [free audit](/contact/) includes a review of your Business Profile." },
      { type: "sources", items: [SRC.gbp, SRC.local] },
    ],
    faqs: [
      { q: "What does a Google Maps SEO expert do?", a: "They optimise your Google Business Profile, build a genuine review routine, keep your business details consistent across the web, and support the profile with relevant website content, then report on calls, directions and clicks." },
      { q: "How long does Google Maps SEO take?", a: "Many businesses see movement within four to eight weeks after the profile is properly optimised and reviews start coming in. Competitive categories take longer." },
      { q: "Can adding keywords to my business name help?", a: "It may help briefly, but it breaks Google’s guidelines and risks suspension. Use your real business name." },
      { q: "Why do my Maps rankings look different on different phones?", a: "Local results depend on the searcher’s location. Track rankings across a grid of points in your service area rather than from one spot." },
    ],
    related: [
      { label: "Local SEO services", href: "/services/local-seo/" },
      { label: "SEO by city", href: "/seo-expert/" },
      { label: "Free Business Profile review", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 17 */
  {
    slug: "on-page-seo-expert",
    title: "On-Page SEO Expert: What Services Should You Expect?",
    keyword: "on page SEO expert",
    description: "What an on-page SEO expert delivers: keyword mapping, titles and descriptions, headings, content improvements, internal links, images and schema, with a page-by-page checklist.",
    category: "SEO skills",
    icon: "file-text",
    accent: "violet",
    answer: "An on-page SEO expert optimises the content and code of individual pages so they match search intent: mapping one main keyword to each page, writing titles and meta descriptions that earn clicks, structuring headings, improving content depth and clarity, adding internal links, optimising images and implementing structured data. You should receive a keyword map, page-level changes and before-and-after tracking.",
    takeaways: [
      "On-page SEO starts with a keyword map: one main topic per page, no two pages competing.",
      "Titles and descriptions influence clicks as much as rankings.",
      "Improving existing pages usually beats publishing new ones.",
      "Internal links tell Google which pages matter most.",
      "Schema helps search and AI systems understand the page; it is not a ranking shortcut.",
    ],
    body: [
      { type: "h2", text: "What on-page SEO covers" },
      { type: "p", text: "**On-page SEO** is everything you control on the page itself: the words, headings, links, images and code. It is where search intent meets your business. A good on-page SEO expert makes each page the clearest, most useful answer to a specific set of searches." },
      { type: "h2", text: "The services you should expect" },
      { type: "table", caption: "On-page SEO deliverables", head: ["Service", "What you receive"], rows: [
        ["Keyword mapping", "A list assigning one main keyword and related terms to each page"],
        ["Titles and meta descriptions", "Rewritten for relevance and click-through"],
        ["Heading structure", "One clear H1 and logical H2 and H3 sections"],
        ["Content improvement", "Gaps filled, questions answered, outdated details fixed"],
        ["Internal linking", "Links from related pages using descriptive anchor text"],
        ["Image optimisation", "Compressed files, descriptive names and alt text"],
        ["Structured data", "Schema that matches visible content"],
        ["Tracking", "Rankings and clicks before and after each change"],
      ] },
      { type: "h2", text: "Start with the keyword map" },
      { type: "p", text: "Without a map, sites end up with several pages targeting the same search, which confuses Google and splits signals. The map assigns each page one primary topic and shows where new pages are genuinely needed." },
      { type: "video", title: "Optimising a single page, start to finish", steps: [
        { title: "Confirm the intent", text: "Search the target keyword and study what Google already ranks: guides, service pages or product pages. Match that format." },
        { title: "Rewrite the title", text: "Lead with the main topic, add a reason to click, and keep it readable rather than stuffed." },
        { title: "Restructure the content", text: "Answer the main question early, then cover the follow-up questions in clear sections." },
        { title: "Add internal links", text: "Link to the page from two or three related pages, and from it to the next logical step." },
        { title: "Track the change", text: "Note the date and watch clicks and position in Search Console over the following weeks." },
      ] },
      { type: "h2", text: "Titles and meta descriptions" },
      { type: "compare", title: "Weak and strong title tags", left: { label: "Weak", items: [
        "Home | Company Name",
        "Best SEO SEO Services SEO Islamabad Cheap SEO",
        "Services",
      ] }, right: { label: "Strong", items: [
        "Family Dentist in F-10 Islamabad | Clinic Name",
        "SEO Services in Islamabad with Monthly Reporting",
        "Corporate Lawyer in Blue Area: Contracts and Compliance",
      ] } },
      { type: "h2", text: "Content depth without fluff" },
      { type: "p", text: "Depth does not mean length. It means covering what a buyer needs to decide: what is included, cost or price range, timelines, areas served, who it suits and how to contact you. Add an FAQ for the questions your team hears repeatedly. Remove filler that adds words without information." },
      { type: "slides", title: "On-page checklist for every important page", slides: [
        { title: "Relevance", points: ["Main keyword in the title and H1", "Related terms used naturally", "Search intent matched"] },
        { title: "Usefulness", points: ["Main question answered early", "Prices, timelines or specifics included", "Clear next step"] },
        { title: "Structure", points: ["Logical headings", "Short paragraphs and lists", "FAQ for repeated questions"] },
        { title: "Signals", points: ["Internal links in and out", "Optimised images", "Valid structured data"] },
      ] },
      { type: "bars", title: "Typical impact of on-page changes on existing pages", items: [
        { label: "Matching search intent", value: 5, display: "Highest" },
        { label: "Title and description rewrite", value: 4, display: "High" },
        { label: "Filling content gaps", value: 4, display: "High" },
        { label: "Internal links", value: 3, display: "Medium" },
        { label: "Image optimisation", value: 2, display: "Supporting" },
      ], note: "Relative impact we commonly see; results vary by site." },
      { type: "p", text: "On-page work is the core of our [SEO service](/services/seo/) and our [content marketing service](/services/content/). [Request an audit](/contact/) to see which of your pages would gain most." },
      { type: "sources", items: [SRC.starter, SRC.helpful, SD] },
    ],
    faqs: [
      { q: "What does an on-page SEO expert do?", a: "They optimise individual pages through keyword mapping, titles and descriptions, heading structure, content improvements, internal links, image optimisation and structured data." },
      { q: "What is the most important on-page SEO factor?", a: "Matching search intent: giving searchers the type of page and information they expect. Titles, headings and links then help Google understand and rank it." },
      { q: "Should I rewrite old pages or create new ones?", a: "Usually improve existing pages first. They already have history and links. Create new pages only where the keyword map shows a genuine gap." },
      { q: "How long before on-page changes affect rankings?", a: "Often within a few weeks after Google recrawls the page, though competitive keywords can take longer." },
    ],
    related: [
      { label: "SEO services", href: "/services/seo/" },
      { label: "Content marketing", href: "/services/content/" },
      { label: "SEO course", href: "/courses/seo/" },
    ],
  },
];
