import type { PostInput } from "@/lib/blog";
import { SRC } from "./part1";

const VITALS = { label: "web.dev: Core Web Vitals", href: "https://web.dev/articles/vitals" };
const CANON = { label: "Google Search Central: How to specify a canonical URL", href: "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls" };
const SD = { label: "Google Search Central: Introduction to structured data", href: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data" };

export const PART3: PostInput[] = [
  /* ------------------------------------------------------------------ 8 */
  {
    slug: "seo-expert-price-islamabad",
    title: "How Much Does an SEO Expert Charge in Islamabad?",
    keyword: "SEO expert price Islamabad",
    description: "Indicative SEO prices in Islamabad for 2026: what freelancers, agencies and senior consultants typically charge, what drives the cost up or down, and how to judge whether a quote is fair.",
    category: "Pricing",
    icon: "wallet",
    accent: "amber",
    answer: "SEO prices in Islamabad vary widely. As an indicative 2026 guide, freelancers often charge roughly PKR 25,000 to 60,000 a month, small agencies PKR 50,000 to 150,000, and senior consultants or specialist agencies PKR 100,000 to 300,000 or more. The real cost depends on competition, how many services and areas you target, and how much content and technical work is needed.",
    takeaways: [
      "Treat any price list as indicative: the right fee depends on your competition and scope.",
      "The biggest cost drivers are category competitiveness, number of services and areas, and content volume.",
      "Very cheap monthly SEO usually means automated reports and risky links.",
      "Compare quotes on deliverables and reporting, not on the headline number.",
      "A good expert can tell you the minimum budget at which SEO becomes viable for you.",
    ],
    body: [
      { type: "h2", text: "Typical SEO price ranges in Islamabad" },
      { type: "p", text: "There is no official rate card for SEO in Pakistan, and fees change with the market. The ranges below are **indicative figures based on what we commonly see quoted in Islamabad and Rawalpindi in 2026**. Use them to sense-check proposals, not as fixed prices." },
      { type: "table", caption: "Indicative monthly SEO fees in Islamabad (2026)", head: ["Provider type", "Indicative monthly range", "Usually includes"], rows: [
        ["Freelancer", "PKR 25,000 – 60,000", "On-page fixes, Google Business Profile, basic reporting"],
        ["Small local agency", "PKR 50,000 – 150,000", "Ongoing SEO, some content, monthly report"],
        ["Senior consultant or specialist agency", "PKR 100,000 – 300,000+", "Strategy, technical work, content, links, enquiry reporting"],
        ["One-off SEO audit", "PKR 15,000 – 75,000", "Written audit and prioritised fix list"],
        ["Google Business Profile setup", "PKR 10,000 – 30,000", "Setup, categories, services, photos, review process"],
      ] },
      { type: "callout", tone: "note", title: "These are indicative, not quotes", text: "Ranges vary by provider, scope and competition and will change over time. Always ask for a written scope that explains exactly what the fee covers." },
      { type: "h2", text: "What drives the price up or down" },
      { type: "bars", title: "Relative impact of the main cost drivers", items: [
        { label: "Competitiveness of your category", value: 5, display: "Very high" },
        { label: "Number of services and areas targeted", value: 4, display: "High" },
        { label: "Content that needs writing", value: 4, display: "High" },
        { label: "Technical state of the website", value: 3, display: "Medium" },
        { label: "Reporting and tracking depth", value: 2, display: "Medium" },
      ], note: "Our view of which factors move the fee most, based on scoping Islamabad projects." },
      { type: "p", text: "A single-location clinic in F-8 targeting five services needs far less work than a property developer with twenty projects targeting overseas buyers. Healthcare, legal, property and finance are also scrutinised more strictly by Google, so the content and credibility work takes longer." },
      { type: "h2", text: "Why very cheap SEO costs more in the end" },
      { type: "compare", title: "What a low price often hides", left: { label: "PKR 10,000 a month packages", items: [
        "Automated reports with no analysis",
        "Bulk directory submissions and paid links",
        "Copy-pasted or AI-spun content",
        "No access to who is doing the work",
      ] }, right: { label: "What you should pay for", items: [
        "A plan specific to your site and market",
        "Links earned from relevant local sources",
        "Content written by someone who understands your sector",
        "Reports that connect rankings to enquiries",
      ] } },
      { type: "p", text: "Google’s spam policies cover link schemes and scaled low-value content. Cleaning up after a cheap package, including disavowing links or rewriting pages, often costs more than doing it properly the first time." },
      { type: "h2", text: "How to judge whether a quote is fair" },
      { type: "slides", title: "Questions that reveal what a quote really includes", slides: [
        { title: "Scope", points: ["How many pages will be optimised each month?", "How many new pages or articles are included?", "Is Google Business Profile management included?"] },
        { title: "Links", points: ["How will links be earned?", "Will I receive a list of every link built?", "Are any links paid for?"] },
        { title: "Reporting", points: ["Which metrics are in the monthly report?", "Will calls and WhatsApp enquiries be tracked?", "Who explains the report to me?"] },
        { title: "Terms", points: ["Is there a minimum term?", "Do I own the content and accounts?", "What happens if results stall?"] },
      ] },
      { type: "video", title: "Working out your SEO budget", steps: [
        { title: "Value a customer", text: "Estimate the average profit from one new customer, including repeat business over a year." },
        { title: "Set a target", text: "Decide how many extra customers per month would make SEO clearly worthwhile." },
        { title: "Check the market", text: "Ask an expert how competitive your keywords are in Islamabad and roughly how long ranking will take." },
        { title: "Compare with ads", text: "Estimate what the same enquiries would cost through Google Ads. SEO usually costs more at first and less over time." },
        { title: "Commit to 90 days", text: "Choose a budget you can sustain for at least three months, then review results before increasing or stopping." },
      ] },
      { type: "h2", text: "How MrSEO.pk prices work" },
      { type: "p", text: "We quote after the audit rather than selling fixed packages, because a package price is a guess made before anyone has looked at your site. The audit is free, the quote explains exactly what is included, and terms are monthly. If the minimum viable budget for your category is more than you can spend, we will say so. [Get your audit and quote](/contact/)." },
      { type: "sources", items: [SRC.needSeo, SRC.spam] },
    ],
    faqs: [
      { q: "How much does an SEO expert charge in Islamabad?", a: "Indicatively, freelancers often charge around PKR 25,000 to 60,000 a month, small agencies PKR 50,000 to 150,000, and senior consultants PKR 100,000 to 300,000 or more. The right fee depends on your competition and scope." },
      { q: "Why do SEO prices vary so much?", a: "Because the work varies. Competitive categories, more services and areas, more content and a website with technical problems all need more hours and more expertise." },
      { q: "Is cheap SEO worth it?", a: "Rarely. Very low monthly fees usually mean automated reports, bulk directory submissions or paid links, which can harm your site and cost more to clean up later." },
      { q: "Do SEO experts in Islamabad charge per keyword?", a: "Some do, but per-keyword pricing encourages targeting easy keywords nobody searches. Pricing by scope and outcomes is usually fairer." },
      { q: "How much does an SEO audit cost in Islamabad?", a: "Indicatively PKR 15,000 to 75,000 for a one-off audit, depending on site size. Some consultants, including MrSEO.pk, offer a free initial audit." },
    ],
    related: [
      { label: "SEO services in Pakistan", href: "/services/seo/" },
      { label: "Google Ads management", href: "/services/ppc/" },
      { label: "Get a free audit and quote", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 9 */
  {
    slug: "best-seo-expert-in-pakistan",
    title: "Who Is the Best SEO Expert in Pakistan?",
    keyword: "best SEO expert in Pakistan",
    description: "An honest framework for deciding who the best SEO expert in Pakistan is for your business, with the criteria that matter, how to verify claims and why rankings for “best SEO expert” prove little.",
    category: "Hiring guide",
    icon: "trophy",
    accent: "violet",
    answer: "There is no single best SEO expert in Pakistan for every business. The best expert for you has verifiable results in your industry and target market, a transparent method that follows Google’s guidelines, reporting tied to enquiries and revenue, and experience with Pakistani search behaviour such as Roman Urdu queries and city-level competition. Judge evidence, not titles or awards.",
    takeaways: [
      "“Best SEO expert in Pakistan” is a claim anyone can make; judge evidence instead.",
      "Industry and market fit matter more than general reputation.",
      "Local knowledge, including Roman Urdu and city-level competition, is a real advantage.",
      "Awards and badges are weak signals; client outcomes are strong ones.",
      "Ranking for “SEO expert” proves skill at one keyword, not at your market.",
    ],
    body: [
      { type: "h2", text: "Why there is no single answer" },
      { type: "p", text: "Search for the best SEO expert in Pakistan and you will find dozens of people claiming the title. Some are genuinely excellent; some are good at ranking for that one phrase. The honest answer is that the best expert depends on what you need. A Faisalabad textile exporter targeting buyers in Europe needs a different specialist from a Lahore restaurant or an Islamabad law firm." },
      { type: "quote", text: "The best SEO expert for your business is the one whose evidence matches your market, your sector and your goal.", cite: "Syed Mudassir Shah, MrSEO.pk" },
      { type: "h2", text: "Five criteria that actually matter" },
      { type: "stats", title: "How to judge an SEO expert in Pakistan", items: [
        { value: "Proof", label: "Results you can verify for businesses like yours" },
        { value: "Fit", label: "Experience in your industry and target market" },
        { value: "Method", label: "Clean techniques that follow Google’s guidelines" },
        { value: "Reporting", label: "Measures enquiries and revenue, not vanity metrics" },
        { value: "Local", label: "Understands Pakistani search behaviour" },
      ] },
      { type: "h3", text: "Verifiable results" },
      { type: "p", text: "Ask for examples you can check: live rankings, Search Console screenshots with dates, and a client you can call. Be wary of screenshots without dates or results for keywords nobody searches." },
      { type: "h3", text: "Industry and market fit" },
      { type: "p", text: "Healthcare, property and finance are judged more strictly by Google. Export businesses need international SEO. Local service businesses need map pack expertise. Look for someone whose past work matches your situation." },
      { type: "h3", text: "Knowledge of Pakistani search" },
      { type: "p", text: "Pakistani buyers mix English and Roman Urdu, search heavily on mobile, prefer WhatsApp, and behave differently from city to city. Keyword tools underreport much of this. An expert who works from your own Search Console data will find opportunities that generic playbooks miss." },
      { type: "h2", text: "Signals that mislead" },
      { type: "compare", title: "Weak signals versus strong signals", left: { label: "Weak signals", items: [
        "Self-awarded “best” or “number one” titles",
        "Paid award badges",
        "Thousands of followers on social media",
        "Ranking for “SEO expert” alone",
      ] }, right: { label: "Strong signals", items: [
        "Named clients you can contact",
        "Results in your sector and city",
        "Clear explanation of their method",
        "Willingness to say what they cannot do",
      ] } },
      { type: "h2", text: "How to compare the top candidates" },
      { type: "video", title: "Finding the best SEO expert for your business", steps: [
        { title: "Define the market", text: "Write down who your customers are and where they search: one city, several cities, all of Pakistan or abroad." },
        { title: "Shortlist by fit", text: "Pick three experts with proven results in a similar market or industry, not just the most visible names." },
        { title: "Request a site-specific audit", text: "Ask each to review your site. The best audits are specific and ranked by impact." },
        { title: "Verify evidence", text: "Call a reference and check claimed rankings yourself from your target city." },
        { title: "Choose on method and fit", text: "Pick the expert whose plan you understand and trust, on terms that let you review results after 90 days." },
      ] },
      { type: "slides", title: "Questions for any “top” SEO expert", slides: [
        { title: "About results", points: ["Which client is most similar to me?", "What changed in their enquiries?", "How long did it take?"] },
        { title: "About method", points: ["How do you earn links?", "How do you use AI in content?", "How do you handle algorithm updates?"] },
        { title: "About you", points: ["Who will do my work each week?", "How many clients do you handle?", "What would make you turn down my project?"] },
      ] },
      { type: "h2", text: "Where MrSEO.pk stands" },
      { type: "p", text: "We will not claim to be the best SEO expert in Pakistan; that is your judgement to make. What we can show is a track record since 2010, work across eight cities and eight industries, a free written audit, and reporting tied to enquiries. Read [about Syed Mudassir Shah](/about/) or browse our [city guides](/seo-expert/) to see how we think about each market." },
      { type: "sources", items: [SRC.needSeo, SRC.helpful, SRC.spam] },
    ],
    faqs: [
      { q: "Who is the best SEO expert in Pakistan?", a: "There is no single best expert for every business. The best one for you has verifiable results in your industry and market, a transparent and compliant method, and reporting tied to enquiries and revenue." },
      { q: "How can I verify an SEO expert’s claims?", a: "Check claimed rankings yourself from your target city, ask for dated Search Console screenshots, and speak to at least one current client about what changed in their enquiries." },
      { q: "Does ranking for “best SEO expert” prove someone is good?", a: "It proves they can rank for that phrase. It does not prove they understand your industry, your city or your customers. Ask for evidence in a market like yours." },
      { q: "Should I hire an SEO expert from Karachi, Lahore or Islamabad?", a: "Location matters less than market knowledge. Hire someone who understands the city or country you are targeting and can show results there." },
    ],
    related: [
      { label: "About Syed Mudassir Shah", href: "/about/" },
      { label: "SEO by city", href: "/seo-expert/" },
      { label: "SEO by industry", href: "/seo-for/" },
    ],
  },

  /* ------------------------------------------------------------------ 10 */
  {
    slug: "seo-expert-rawalpindi-hiring-guide",
    title: "SEO Expert in Rawalpindi: Complete Hiring Guide",
    keyword: "SEO expert Rawalpindi",
    description: "How to hire an SEO expert in Rawalpindi: how Pindi search differs from Islamabad, which areas to target, what services you need and how to evaluate local SEO providers.",
    category: "Local SEO",
    icon: "train-front",
    accent: "blue",
    answer: "To hire an SEO expert in Rawalpindi, look for someone who understands area-level search across Saddar, Satellite Town, Bahria Town, DHA and Chaklala, who prioritises your Google Business Profile and reviews, and who writes in the mix of English and Roman Urdu Pindi customers use. Ask for local results you can verify and start with a 90-day plan on monthly terms.",
    takeaways: [
      "Rawalpindi customers search by area: Saddar, Satellite Town, Bahria Town, DHA and Chaklala behave differently.",
      "Price and practicality matter more in Pindi searches than in Islamabad’s premium sectors.",
      "Roman Urdu and WhatsApp-first contact are common, so pages must reflect that.",
      "Twin-city targeting can double your reach if your service covers both cities.",
      "Local pack results often move within six weeks in Rawalpindi when the basics are done properly.",
    ],
    body: [
      { type: "h2", text: "How SEO in Rawalpindi differs from Islamabad" },
      { type: "p", text: "Rawalpindi and Islamabad sit side by side but search differently. Islamabad is organised by sectors and dominated by English-language, research-heavy buying. Rawalpindi is denser, more commercially diverse and more price-conscious, with large markets around Saddar, Raja Bazaar and Commercial Market, and newer self-contained communities in Bahria Town and DHA. A good SEO expert in Rawalpindi plans around those differences rather than reusing an Islamabad template. Our [Rawalpindi SEO guide](/seo-expert/seo-expert-rawalpindi/) covers the market in depth." },
      { type: "compare", title: "Rawalpindi and Islamabad search compared", left: { label: "Islamabad", items: [
        "Sector-based searches such as F-10 or G-11",
        "Mostly English commercial queries",
        "High value per lead, lower volume",
        "Buyers research carefully before contacting",
      ] }, right: { label: "Rawalpindi", items: [
        "Area-based searches such as Saddar or Satellite Town",
        "English mixed with Roman Urdu",
        "Higher volume, more price comparison",
        "Faster decisions, WhatsApp-first contact",
      ] } },
      { type: "h2", text: "The Rawalpindi areas that matter for search" },
      { type: "table", caption: "Search behaviour by area", head: ["Area", "What tends to be searched"], rows: [
        ["Saddar and Raja Bazaar", "Retail, wholesale, repairs, food and everyday services"],
        ["Satellite Town and Commercial Market", "Clinics, salons, tuition, restaurants, family services"],
        ["Bahria Town phases", "Property, interiors, schools, home services, restaurants"],
        ["DHA Rawalpindi", "Property, premium services, schools and clinics"],
        ["Chaklala and Westridge", "Family services, schools, healthcare and local shops"],
      ] },
      { type: "h2", text: "Services a Rawalpindi business needs" },
      { type: "slides", title: "Core SEO services for Rawalpindi", slides: [
        { title: "Google Business Profile", points: ["Correct category and service list", "Real photos of the premises", "A steady review routine"] },
        { title: "Area pages", points: ["Pages for the areas you genuinely serve", "Real local detail, not swapped place names", "Directions and landmarks customers use"] },
        { title: "Service pages", points: ["Prices or price ranges", "Roman Urdu phrases where customers use them", "WhatsApp contact on every page"] },
        { title: "Twin-city reach", points: ["Islamabad sector pages if you serve them", "Separate content for each city", "Consistent business details everywhere"] },
      ] },
      { type: "h2", text: "How to evaluate Rawalpindi SEO providers" },
      { type: "checklist", title: "Hiring checklist for Rawalpindi", items: [
        "Can show local pack results in Rawalpindi you can check yourself",
        "Talks about specific areas, not just “Rawalpindi” as one market",
        "Understands Roman Urdu search and WhatsApp-first contact",
        "Offers monthly terms after an audit",
        "Reports calls and WhatsApp enquiries, not only rankings",
        "Keeps your Google Business Profile in your ownership",
      ] },
      { type: "video", title: "Hiring an SEO expert in Rawalpindi", steps: [
        { title: "Map your customers", text: "List the areas your customers come from and the services they ask about most." },
        { title: "Check the local pack", text: "Search your main service plus each area on your phone and note who appears in the map results." },
        { title: "Shortlist three providers", text: "Prefer providers with visible Rawalpindi results and detailed local reviews." },
        { title: "Compare audits", text: "Ask each for a site and profile audit. Choose the one that names concrete local opportunities." },
        { title: "Start with 90 days", text: "Agree a 90-day plan focused on the profile, service pages and two or three priority areas." },
      ] },
      { type: "stats", title: "Typical Rawalpindi timelines", items: [
        { value: "4–6 wks", label: "Local pack movement after profile work" },
        { value: "2–3 mo", label: "Organic gains for service keywords" },
        { value: "3 mo+", label: "Steady enquiry growth from area pages" },
      ] },
      { type: "p", text: "Our training campus is in Scheme 3, Rawalpindi, and we work with Pindi businesses every week. If you want an expert who knows the twin cities, [request a free audit](/contact/)." },
      { type: "sources", items: [SRC.gbp, SRC.local] },
    ],
    faqs: [
      { q: "How do I find a good SEO expert in Rawalpindi?", a: "Look for verifiable local pack results in Rawalpindi, knowledge of area-level search, Roman Urdu content experience and monthly terms. Compare three audits before choosing." },
      { q: "Should a Rawalpindi business also target Islamabad?", a: "If you genuinely serve Islamabad customers, yes. Create separate, substantive content for the Islamabad sectors you cover rather than one page for both cities." },
      { q: "How fast does local SEO work in Rawalpindi?", a: "Local pack movement often appears within four to six weeks once the Google Business Profile is properly set up, with organic gains for service keywords in two to three months." },
      { q: "Do Rawalpindi customers search in Urdu?", a: "Many use a mix of English and Roman Urdu. Your own Search Console data shows the exact phrases; include them naturally in English pages." },
    ],
    related: [
      { label: "SEO Expert in Rawalpindi", href: "/seo-expert/seo-expert-rawalpindi/" },
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "Local SEO services", href: "/services/local-seo/" },
    ],
  },

  /* ------------------------------------------------------------------ 11 */
  {
    slug: "local-seo-expert-islamabad",
    title: "Local SEO Expert in Islamabad: How to Improve Google Maps Rankings",
    keyword: "local SEO expert Islamabad",
    description: "How a local SEO expert improves Google Maps rankings in Islamabad: relevance, distance and prominence explained, Google Business Profile optimisation, reviews, citations and sector pages.",
    category: "Local SEO",
    icon: "map-pin",
    accent: "green",
    answer: "Google ranks local results on relevance, distance and prominence. A local SEO expert in Islamabad improves Google Maps rankings by choosing the right categories and services in your Google Business Profile, adding real photos and accurate hours, building a steady flow of genuine reviews, keeping your business details consistent across directories, and creating useful pages for the sectors you serve.",
    takeaways: [
      "Google’s local ranking factors are relevance, distance and prominence.",
      "The primary category is the single most important setting in your Business Profile.",
      "Review quantity, recency and replies all contribute to prominence.",
      "Sector pages on your website support Maps rankings beyond your immediate area.",
      "Fake addresses, keyword-stuffed names and bought reviews risk suspension.",
    ],
    body: [
      { type: "h2", text: "How Google ranks local results" },
      { type: "p", text: "Google explains that local results are based mainly on **relevance** (how well your profile matches the search), **distance** (how far you are from the searcher or the location in the query) and **prominence** (how well known your business is, including reviews and links). You cannot change your distance, but a local SEO expert can improve the other two significantly." },
      { type: "stats", title: "The three local ranking factors", items: [
        { value: "Relevance", label: "Categories, services and content that match the search" },
        { value: "Distance", label: "How close you are to the searcher or the area searched" },
        { value: "Prominence", label: "Reviews, links, mentions and overall reputation" },
      ] },
      { type: "h2", text: "Optimising your Google Business Profile" },
      { type: "checklist", title: "Business Profile essentials", items: [
        "The most accurate **primary category**, plus relevant secondary categories",
        "Every service listed, with short descriptions",
        "Your real business name, without added keywords",
        "Accurate address with the correct sector, or a service area if you visit customers",
        "Hours that include Friday prayer adjustments and holidays",
        "Real photos of the premises, team and work, added regularly",
        "Products or price ranges where relevant",
        "Questions and answers that reflect what customers ask",
      ] },
      { type: "callout", tone: "warn", title: "Avoid suspension", text: "Google’s guidelines prohibit adding keywords to your business name, using virtual offices you do not staff, and creating multiple profiles for one location. Suspensions can take weeks to resolve, during which you disappear from Maps." },
      { type: "h2", text: "Reviews: the prominence engine" },
      { type: "p", text: "Review count, rating, recency and your replies all matter. In Islamabad, where customers compare carefully, detailed reviews that mention the service and area are especially persuasive to both buyers and Google." },
      { type: "video", title: "Building a review routine that lasts", steps: [
        { title: "Get your review link", text: "Copy the short review link from your Business Profile and save it on staff phones." },
        { title: "Ask at the right moment", text: "Ask straight after a good outcome: a finished job, a successful appointment, a happy delivery." },
        { title: "Make it easy", text: "Send the link on WhatsApp with a short thank-you message, or show a QR code at the counter." },
        { title: "Reply to every review", text: "Thank positive reviewers by name and respond calmly and helpfully to complaints." },
        { title: "Never incentivise", text: "Do not offer discounts for reviews or ask only happy customers through filters. Both break Google’s policies." },
      ] },
      { type: "h2", text: "Citations and consistency" },
      { type: "p", text: "Citations are mentions of your business name, address and phone on other sites: Pakistani business directories, industry associations, chambers of commerce and social profiles. Consistency matters more than volume. Use exactly the same name, address format and phone number everywhere." },
      { type: "h2", text: "Sector pages that extend your reach" },
      { type: "p", text: "Distance limits how far your Maps listing reaches. A clinic in F-8 naturally ranks near F-8. Well-written pages about serving nearby sectors, with real detail about the area and the services you provide there, help you appear for searches like “dentist F-10” or “physiotherapist G-11”." },
      { type: "slides", title: "A 60-day local SEO plan for Islamabad", slides: [
        { title: "Week 1–2", points: ["Audit and correct the Business Profile", "Fix name, address and phone everywhere", "Set up review link and tracking"] },
        { title: "Week 3–4", points: ["Add services, products and photos", "Start the review routine", "Publish weekly profile updates"] },
        { title: "Week 5–6", points: ["Create two sector pages", "Build ten quality citations", "Answer common customer questions"] },
        { title: "Week 7–8", points: ["Review calls, directions and website clicks", "Expand to the next sectors", "Request links from local partners"] },
      ] },
      { type: "bars", title: "Where local SEO effort usually pays off first", items: [
        { label: "Primary category and services", value: 5, display: "Highest" },
        { label: "Reviews and replies", value: 4, display: "High" },
        { label: "Photos and updates", value: 3, display: "Medium" },
        { label: "Sector pages on the website", value: 3, display: "Medium" },
        { label: "Citations", value: 2, display: "Supporting" },
      ], note: "Our experience across Islamabad local campaigns; your mix will depend on your category." },
      { type: "p", text: "Our [local SEO service](/services/local-seo/) covers all of the above, and the [free audit](/contact/) includes a review of your Business Profile." },
      { type: "sources", items: [SRC.local, SRC.gbp] },
    ],
    faqs: [
      { q: "How can I rank higher on Google Maps in Islamabad?", a: "Choose the most accurate primary category, list every service, add real photos and correct hours, build a steady flow of genuine reviews, keep your details consistent across directories, and create useful pages for the sectors you serve." },
      { q: "How long does it take to improve Google Maps rankings?", a: "Many Islamabad businesses see movement within four to eight weeks after fixing their profile and starting a review routine. Competitive categories take longer." },
      { q: "Can I rank on Google Maps without a physical office?", a: "Service-area businesses can appear without showing an address if staff visit customers. Virtual offices and addresses you do not staff break Google’s guidelines." },
      { q: "Do reviews affect Google Maps rankings?", a: "Yes. Google lists review count and score as part of prominence. Recent, detailed reviews and your replies also help customers choose you." },
    ],
    related: [
      { label: "Local SEO services", href: "/services/local-seo/" },
      { label: "SEO Expert in Islamabad", href: "/seo-expert/seo-expert-islamabad/" },
      { label: "Free Business Profile review", href: "/contact/" },
    ],
  },

  /* ------------------------------------------------------------------ 12 */
  {
    slug: "technical-seo-expert",
    title: "Technical SEO Expert in Islamabad: When Do You Need One?",
    keyword: "technical SEO expert",
    description: "The signs your website needs a technical SEO expert, what a technical audit covers, how Core Web Vitals, indexing and site architecture affect rankings, and what to fix first.",
    category: "Technical SEO",
    icon: "cpu",
    accent: "teal",
    answer: "You need a technical SEO expert when good content still is not ranking, pages are missing from Google, traffic dropped after a redesign or migration, the site is slow on mobile, or you run a large site with filters and many URLs. A technical expert diagnoses crawling, indexing, speed, structure and structured data problems, then gives your developer a prioritised fix list.",
    takeaways: [
      "Technical SEO makes sure Google can crawl, render, understand and index your pages.",
      "Common triggers: pages not indexed, migrations, slow mobile pages and duplicate URLs.",
      "Core Web Vitals measure loading, responsiveness (INP) and visual stability.",
      "A good technical audit ranks fixes by impact so your developer knows what to do first.",
      "Most small sites need a technical audit once a year and before any redesign.",
    ],
    body: [
      { type: "h2", text: "What technical SEO covers" },
      { type: "p", text: "**Technical SEO** is the work of making sure search engines can find, crawl, render, understand and index your pages efficiently. Content and links only help if this foundation is sound. A technical SEO expert works closely with developers, translating search problems into specific code and configuration changes." },
      { type: "process", title: "How Google processes a page", steps: [
        { title: "Discover", text: "Links and sitemaps" },
        { title: "Crawl", text: "Googlebot fetches the URL" },
        { title: "Render", text: "JavaScript and layout processed" },
        { title: "Index", text: "Content understood and stored" },
        { title: "Rank", text: "Shown for relevant searches" },
      ] },
      { type: "h2", text: "Signs you need a technical SEO expert" },
      { type: "checklist", title: "Warning signs", items: [
        "Search Console shows many pages as “Crawled, currently not indexed” or “Discovered, not indexed”",
        "Traffic dropped after a redesign, new theme or domain change",
        "Pages load slowly on mobile data or fail Core Web Vitals",
        "Duplicate versions of pages exist with parameters, tags or filters",
        "Your JavaScript site shows little content in Google’s cached or rendered view",
        "Important pages are buried four or more clicks from the home page",
        "Structured data shows errors in Search Console",
      ] },
      { type: "h2", text: "What a technical audit includes" },
      { type: "table", caption: "Technical audit areas", head: ["Area", "What is checked"], rows: [
        ["Crawlability", "robots.txt, internal links, orphan pages, redirect chains, broken links"],
        ["Indexing", "Index coverage, canonical tags, noindex use, duplicate content, sitemaps"],
        ["Performance", "Core Web Vitals (LCP, INP, CLS), image weight, server response time"],
        ["Mobile", "Responsive layout, tap targets, content parity with desktop"],
        ["Architecture", "URL structure, click depth, internal linking between services and areas"],
        ["Structured data", "Organisation, LocalBusiness, product, article and FAQ markup validity"],
        ["Security", "HTTPS, mixed content, redirects from http and www variants"],
      ] },
      { type: "h2", text: "Core Web Vitals in plain language" },
      { type: "stats", title: "Google’s Core Web Vitals thresholds for a good experience", items: [
        { value: "≤ 2.5s", label: "Largest Contentful Paint: main content loads" },
        { value: "≤ 200ms", label: "Interaction to Next Paint: page responds to taps" },
        { value: "≤ 0.1", label: "Cumulative Layout Shift: nothing jumps around" },
      ] },
      { type: "p", text: "In Pakistan, many visitors browse on mid-range phones over variable mobile connections, so page weight matters more than on fast office broadband. Heavy sliders, uncompressed images and too many plugins are the usual culprits on WordPress sites in Islamabad." },
      { type: "slides", title: "Technical fixes that usually matter most", slides: [
        { title: "Indexing", points: ["Fix pages blocked by noindex or robots.txt by mistake", "Consolidate duplicates with canonical tags or redirects", "Submit a clean XML sitemap"] },
        { title: "Speed", points: ["Compress and resize images, serve WebP or AVIF", "Remove unused plugins and scripts", "Use caching and a CDN"] },
        { title: "Structure", points: ["Keep key pages within three clicks of home", "Link services to relevant area pages", "Use clean, descriptive URLs"] },
        { title: "Migrations", points: ["Map every old URL to a new one", "Use 301 redirects, not 302", "Monitor Search Console for eight weeks after launch"] },
      ] },
      { type: "video", title: "Running a basic technical check yourself", steps: [
        { title: "Open Search Console", text: "Go to the Pages report and note how many pages are indexed and why others are not." },
        { title: "Test your key page", text: "Use URL Inspection on your most important service page and check it is indexed and renders correctly." },
        { title: "Check speed", text: "Run PageSpeed Insights on the mobile version of your home page and a service page." },
        { title: "Search your own site", text: "Search site:yourdomain.pk in Google and look for duplicates, old pages or test pages." },
        { title: "Bring in an expert", text: "If you find indexing errors, failing vitals or duplicates you cannot explain, that is the moment for a technical audit." },
      ] },
      { type: "p", text: "MrSEO.pk carries out technical audits for Islamabad businesses and supports developers through redesigns and migrations. See our [web design and development service](/services/web-design/) or [request an audit](/contact/)." },
      { type: "sources", items: [VITALS, CANON, SD, SRC.starter] },
    ],
    faqs: [
      { q: "What does a technical SEO expert do?", a: "They make sure search engines can crawl, render, understand and index your pages, fixing problems with indexing, speed, mobile usability, site structure, duplicate content and structured data." },
      { q: "When do I need technical SEO?", a: "When pages are missing from Google, traffic drops after a redesign or migration, the site is slow on mobile, or you run a large site with filters, parameters or many URLs." },
      { q: "What are Core Web Vitals?", a: "Google’s measures of page experience: Largest Contentful Paint for loading, Interaction to Next Paint for responsiveness and Cumulative Layout Shift for visual stability." },
      { q: "How often should I get a technical SEO audit?", a: "Most small business sites need one a year and before any redesign or migration. Large or frequently changing sites benefit from monthly monitoring." },
    ],
    related: [
      { label: "Web design and development", href: "/services/web-design/" },
      { label: "SEO services", href: "/services/seo/" },
      { label: "Request a technical audit", href: "/contact/" },
    ],
  },
];
