/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    'case-studies': CaseStudy;
    media: Media;
    services: Service;
    courses: Course;
    cities: City;
    industries: Industry;
    testimonials: Testimonial;
    queries: Query;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    queries: QueriesSelect<false> | QueriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    home: Home;
    about: About;
    'contact-page': ContactPage;
    'courses-page': CoursesPage;
    'hub-pages': HubPage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    'hub-pages': HubPagesSelect<false> | HubPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Posts go live automatically at their publish time. Set a future time to schedule a post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown under the title and on blog cards.
   */
  description: string;
  /**
   * A 40 to 60 word direct answer, shown first. This is what Google snippets and AI assistants quote.
   */
  answer: string;
  takeaways?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add paragraphs, headings, slides, infographics and guides. Drag to reorder.
   */
  body?:
    | (
        | {
            /**
             * Use **double asterisks** for bold and [link text](/page-url/) for links.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            /**
             * Main section heading. Appears in the table of contents.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading2';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading3';
          }
        | {
            ordered?: boolean | null;
            /**
             * Use **double asterisks** for bold and [link text](/page-url/) for links.
             */
            items?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            tone: 'tip' | 'warn' | 'note';
            title?: string | null;
            /**
             * Use **double asterisks** for bold and [link text](/page-url/) for links.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            title: string;
            slides?:
              | {
                  title: string;
                  points?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slides';
          }
        | {
            title: string;
            steps?:
              | {
                  title: string;
                  /**
                   * Use **double asterisks** for bold and [link text](/page-url/) for links.
                   */
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            title: string;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title: string;
            items?:
              | {
                  label: string;
                  /**
                   * Bar length, 0 to 100
                   */
                  value: number;
                  /**
                   * Text shown on the bar (optional)
                   */
                  display?: string | null;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bars';
          }
        | {
            title: string;
            steps?:
              | {
                  title: string;
                  /**
                   * Use **double asterisks** for bold and [link text](/page-url/) for links.
                   */
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            title: string;
            leftLabel: string;
            rightLabel: string;
            leftItems?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            rightItems?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'compare';
          }
        | {
            title: string;
            items?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            caption?: string | null;
            head?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            rows?:
              | {
                  cells?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            /**
             * Use **double asterisks** for bold and [link text](/page-url/) for links.
             */
            text: string;
            cite?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            items?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sources';
          }
      )[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  related?:
    | {
        label: string;
        /**
         * e.g. /services/seo/
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  keyword: string;
  /**
   * Leave empty to use the intro. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * The post appears on the site at this time.
   */
  publishAt: string;
  /**
   * Set when you substantially update the article. Used as the "modified" date for Google.
   */
  contentUpdatedAt?: string | null;
  hideFromSite?: boolean | null;
  category: string;
  accent: 'green' | 'blue' | 'teal' | 'amber' | 'violet' | 'rose';
  /**
   * Drawn on the generated feature image and post card.
   */
  icon:
    | 'award'
    | 'banknote'
    | 'bed-double'
    | 'bot'
    | 'building'
    | 'building-2'
    | 'cloud'
    | 'cpu'
    | 'file-code'
    | 'file-text'
    | 'git-compare'
    | 'globe'
    | 'graduation-cap'
    | 'house'
    | 'landmark'
    | 'laptop'
    | 'link'
    | 'link-2'
    | 'locate-fixed'
    | 'map'
    | 'map-pin'
    | 'messages-square'
    | 'plane'
    | 'rocket'
    | 'scale'
    | 'search'
    | 'search-check'
    | 'shopping-bag'
    | 'shopping-cart'
    | 'smile'
    | 'sparkles'
    | 'stethoscope'
    | 'store'
    | 'train-front'
    | 'trophy'
    | 'user-check'
    | 'users'
    | 'utensils'
    | 'wallet'
    | 'wrench';
  /**
   * Optional. Leave empty to use the automatically designed image (1200 x 630).
   */
  featureImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and files for blog posts, case studies and pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and Google Images.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Simple pages such as Privacy Policy and Terms, served at mrseo.pk/your-slug/. The main pages are edited under Page settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  intro?: string | null;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Untick to hide the page (it returns 404).
   */
  published?: boolean | null;
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real client results. The case studies page is hidden from Google until at least one is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  client?: string | null;
  industry?: string | null;
  city?: string | null;
  /**
   * Shown on the case studies list and at the top of the page.
   */
  summary: string;
  results?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Shown under the name in menus.
   */
  sub?: string | null;
  desc: string;
  /**
   * Leave empty to use the default icon for this item.
   */
  icon?:
    | (
        | 'svc:seo'
        | 'svc:ppc'
        | 'svc:social-media'
        | 'svc:web-design'
        | 'svc:local-seo'
        | 'svc:content'
        | 'course:digital-marketing'
        | 'course:seo'
        | 'course:social-media-marketing'
        | 'course:ai-marketing'
        | 'course:graphic-design'
        | 'course:content-writing'
        | 'course:canva-design'
        | 'course:ai-basics'
        | 'course:wordpress'
        | 'course:video-editing'
        | 'course:freelancing'
        | 'course:meta-ads-basics'
        | 'ind:travel-tourism'
        | 'ind:ecommerce'
        | 'ind:cosmetics'
        | 'ind:medical'
        | 'ind:schools'
        | 'ind:hotels'
        | 'ind:clinics'
        | 'ind:real-estate'
        | 'city:karachi'
        | 'city:lahore'
        | 'city:islamabad'
        | 'city:rawalpindi'
        | 'city:peshawar'
        | 'city:quetta'
        | 'city:faisalabad'
        | 'city:multan'
        | 'briefcase'
        | 'award'
        | 'folder'
        | 'file'
        | 'video'
        | 'users'
        | 'wallet'
        | 'clock'
        | 'hammer'
        | 'upgrade'
        | 'trophy'
        | 'local'
        | 'chart'
        | 'map'
        | 'layers'
        | 'unlock'
        | 'link'
        | 'coins'
        | 'search'
        | 'pin'
        | 'pen'
        | 'chat'
        | 'mail'
        | 'alert'
        | 'grad'
      )
    | null;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  tier: 'pro' | 'short';
  sub?: string | null;
  short?: string | null;
  desc: string;
  /**
   * e.g. 16 weeks
   */
  duration: string;
  /**
   * e.g. 96 hours
   */
  hours?: string | null;
  level?: string | null;
  /**
   * Number only, e.g. 15,000
   */
  fee: string;
  /**
   * e.g. One-time fee
   */
  fee_note?: string | null;
  seats?: string | null;
  mode?: string | null;
  /**
   * e.g. 8 weeks. Leave empty for none.
   */
  intern?: string | null;
  schedule?: string | null;
  outcomes?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the default icon for this item.
   */
  icon?:
    | (
        | 'svc:seo'
        | 'svc:ppc'
        | 'svc:social-media'
        | 'svc:web-design'
        | 'svc:local-seo'
        | 'svc:content'
        | 'course:digital-marketing'
        | 'course:seo'
        | 'course:social-media-marketing'
        | 'course:ai-marketing'
        | 'course:graphic-design'
        | 'course:content-writing'
        | 'course:canva-design'
        | 'course:ai-basics'
        | 'course:wordpress'
        | 'course:video-editing'
        | 'course:freelancing'
        | 'course:meta-ads-basics'
        | 'ind:travel-tourism'
        | 'ind:ecommerce'
        | 'ind:cosmetics'
        | 'ind:medical'
        | 'ind:schools'
        | 'ind:hotels'
        | 'ind:clinics'
        | 'ind:real-estate'
        | 'city:karachi'
        | 'city:lahore'
        | 'city:islamabad'
        | 'city:rawalpindi'
        | 'city:peshawar'
        | 'city:quetta'
        | 'city:faisalabad'
        | 'city:multan'
        | 'briefcase'
        | 'award'
        | 'folder'
        | 'file'
        | 'video'
        | 'users'
        | 'wallet'
        | 'clock'
        | 'hammer'
        | 'upgrade'
        | 'trophy'
        | 'local'
        | 'chart'
        | 'map'
        | 'layers'
        | 'unlock'
        | 'link'
        | 'coins'
        | 'search'
        | 'pin'
        | 'pen'
        | 'chat'
        | 'mail'
        | 'alert'
        | 'grad'
      )
    | null;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  urdu?: string | null;
  /**
   * e.g. Commercial capital
   */
  note?: string | null;
  /**
   * e.g. 120+
   */
  clients?: string | null;
  /**
   * e.g. Very high
   */
  comp?: string | null;
  pop?: string | null;
  /**
   * Leave empty to use the default icon for this item.
   */
  icon?:
    | (
        | 'svc:seo'
        | 'svc:ppc'
        | 'svc:social-media'
        | 'svc:web-design'
        | 'svc:local-seo'
        | 'svc:content'
        | 'course:digital-marketing'
        | 'course:seo'
        | 'course:social-media-marketing'
        | 'course:ai-marketing'
        | 'course:graphic-design'
        | 'course:content-writing'
        | 'course:canva-design'
        | 'course:ai-basics'
        | 'course:wordpress'
        | 'course:video-editing'
        | 'course:freelancing'
        | 'course:meta-ads-basics'
        | 'ind:travel-tourism'
        | 'ind:ecommerce'
        | 'ind:cosmetics'
        | 'ind:medical'
        | 'ind:schools'
        | 'ind:hotels'
        | 'ind:clinics'
        | 'ind:real-estate'
        | 'city:karachi'
        | 'city:lahore'
        | 'city:islamabad'
        | 'city:rawalpindi'
        | 'city:peshawar'
        | 'city:quetta'
        | 'city:faisalabad'
        | 'city:multan'
        | 'briefcase'
        | 'award'
        | 'folder'
        | 'file'
        | 'video'
        | 'users'
        | 'wallet'
        | 'clock'
        | 'hammer'
        | 'upgrade'
        | 'trophy'
        | 'local'
        | 'chart'
        | 'map'
        | 'layers'
        | 'unlock'
        | 'link'
        | 'coins'
        | 'search'
        | 'pin'
        | 'pen'
        | 'chat'
        | 'mail'
        | 'alert'
        | 'grad'
      )
    | null;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  urdu?: string | null;
  desc: string;
  kws?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short phrases. The first two appear as stats at the top of the page.
   */
  stats?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the default icon for this item.
   */
  icon?:
    | (
        | 'svc:seo'
        | 'svc:ppc'
        | 'svc:social-media'
        | 'svc:web-design'
        | 'svc:local-seo'
        | 'svc:content'
        | 'course:digital-marketing'
        | 'course:seo'
        | 'course:social-media-marketing'
        | 'course:ai-marketing'
        | 'course:graphic-design'
        | 'course:content-writing'
        | 'course:canva-design'
        | 'course:ai-basics'
        | 'course:wordpress'
        | 'course:video-editing'
        | 'course:freelancing'
        | 'course:meta-ads-basics'
        | 'ind:travel-tourism'
        | 'ind:ecommerce'
        | 'ind:cosmetics'
        | 'ind:medical'
        | 'ind:schools'
        | 'ind:hotels'
        | 'ind:clinics'
        | 'ind:real-estate'
        | 'city:karachi'
        | 'city:lahore'
        | 'city:islamabad'
        | 'city:rawalpindi'
        | 'city:peshawar'
        | 'city:quetta'
        | 'city:faisalabad'
        | 'city:multan'
        | 'briefcase'
        | 'award'
        | 'folder'
        | 'file'
        | 'video'
        | 'users'
        | 'wallet'
        | 'clock'
        | 'hammer'
        | 'upgrade'
        | 'trophy'
        | 'local'
        | 'chart'
        | 'map'
        | 'layers'
        | 'unlock'
        | 'link'
        | 'coins'
        | 'search'
        | 'pin'
        | 'pen'
        | 'chat'
        | 'mail'
        | 'alert'
        | 'grad'
      )
    | null;
  /**
   * One paragraph shown in the "In short" box near the top. Written as a direct answer for Google and AI assistants.
   */
  quick?: string | null;
  /**
   * Each section gets an H2 heading and appears in the table of contents.
   */
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  /**
   * Used in the page address. Lowercase letters, numbers and hyphens only. Changing it changes the URL.
   */
  slug: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real, attributable client feedback only. The homepage section appears once at least one is added.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  city?: string | null;
  text: string;
  /**
   * Lower numbers appear first in menus and grids.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything sent through the website forms. Mark each one as you deal with it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "queries".
 */
export interface Query {
  id: number;
  kind: 'contact' | 'enroll';
  status: 'new' | 'contacted' | 'won' | 'closed' | 'spam';
  name: string;
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  service?: string | null;
  website?: string | null;
  course?: string | null;
  mode?: string | null;
  education?: string | null;
  message?: string | null;
  /**
   * Only visible in the admin.
   */
  notes?: string | null;
  page?: string | null;
  ip?: string | null;
  emailed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'queries';
        value: number | Query;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  answer?: T;
  takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading2?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading3?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              ordered?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              tone?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        slides?:
          | T
          | {
              title?: T;
              slides?:
                | T
                | {
                    title?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bars?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    display?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        compare?:
          | T
          | {
              title?: T;
              leftLabel?: T;
              rightLabel?: T;
              leftItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rightItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              head?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              cite?: T;
              id?: T;
              blockName?: T;
            };
        sources?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  related?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  keyword?: T;
  metaDescription?: T;
  slug?: T;
  publishAt?: T;
  contentUpdatedAt?: T;
  hideFromSite?: T;
  category?: T;
  accent?: T;
  icon?: T;
  featureImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  published?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  industry?: T;
  city?: T;
  summary?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  image?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  sub?: T;
  desc?: T;
  icon?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  sub?: T;
  short?: T;
  desc?: T;
  duration?: T;
  hours?: T;
  level?: T;
  fee?: T;
  fee_note?: T;
  seats?: T;
  mode?: T;
  intern?: T;
  schedule?: T;
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        text?: T;
        id?: T;
      };
  icon?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  urdu?: T;
  note?: T;
  clients?: T;
  comp?: T;
  pop?: T;
  icon?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  urdu?: T;
  desc?: T;
  kws?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        text?: T;
        id?: T;
      };
  icon?: T;
  quick?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  city?: T;
  text?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "queries_select".
 */
export interface QueriesSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  service?: T;
  website?: T;
  course?: T;
  mode?: T;
  education?: T;
  message?: T;
  notes?: T;
  page?: T;
  ip?: T;
  emailed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, numbers and links used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  ownerName: string;
  brandTagline?: string | null;
  email: string;
  /**
   * Digits only with country code, e.g. 923435853835
   */
  whatsapp: string;
  phone: string;
  baseCity: string;
  baseRegion?: string | null;
  /**
   * e.g. Scheme 3, Rawalpindi
   */
  campus: string;
  campusCity: string;
  campusArea?: string | null;
  officeHours?: string | null;
  /**
   * e.g. 14+
   */
  yearsExperience?: string | null;
  /**
   * e.g. 50+
   */
  websitesRanked?: string | null;
  /**
   * e.g. 400+
   */
  clientsServed?: string | null;
  footerText?: string | null;
  authorBio?: string | null;
  /**
   * Pre-filled text when visitors tap the WhatsApp buttons.
   */
  whatsappMessage?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'x' | 'linkedin' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultMetaDescription?: string | null;
  /**
   * LinkedIn and similar profiles that identify the owner in structured data.
   */
  founderSameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  heroEyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
   */
  heroTitle?: string | null;
  heroDesc?: string | null;
  heroPoints?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  heroStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  cardRole?: string | null;
  cardLocation?: string | null;
  cardLabel?: string | null;
  cardPoints?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  answerLabel?: string | null;
  answerText?: string | null;
  servicesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  coursesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  /**
   * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
   */
  shortTitle?: string | null;
  shortText?: string | null;
  citiesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  industriesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  processHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  whyHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  whys?:
    | {
        icon?:
          | (
              | 'svc:seo'
              | 'svc:ppc'
              | 'svc:social-media'
              | 'svc:web-design'
              | 'svc:local-seo'
              | 'svc:content'
              | 'course:digital-marketing'
              | 'course:seo'
              | 'course:social-media-marketing'
              | 'course:ai-marketing'
              | 'course:graphic-design'
              | 'course:content-writing'
              | 'course:canva-design'
              | 'course:ai-basics'
              | 'course:wordpress'
              | 'course:video-editing'
              | 'course:freelancing'
              | 'course:meta-ads-basics'
              | 'ind:travel-tourism'
              | 'ind:ecommerce'
              | 'ind:cosmetics'
              | 'ind:medical'
              | 'ind:schools'
              | 'ind:hotels'
              | 'ind:clinics'
              | 'ind:real-estate'
              | 'city:karachi'
              | 'city:lahore'
              | 'city:islamabad'
              | 'city:rawalpindi'
              | 'city:peshawar'
              | 'city:quetta'
              | 'city:faisalabad'
              | 'city:multan'
              | 'briefcase'
              | 'award'
              | 'folder'
              | 'file'
              | 'video'
              | 'users'
              | 'wallet'
              | 'clock'
              | 'hammer'
              | 'upgrade'
              | 'trophy'
              | 'local'
              | 'chart'
              | 'map'
              | 'layers'
              | 'unlock'
              | 'link'
              | 'coins'
              | 'search'
              | 'pin'
              | 'pen'
              | 'chat'
              | 'mail'
              | 'alert'
              | 'grad'
            )
          | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  testimonialsHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  faqHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  contactHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  cta?: {
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    text?: string | null;
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
   */
  title?: string | null;
  lead?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cardRole?: string | null;
  cardLocation?: string | null;
  cardSkills?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  answer?: string | null;
  sections?:
    | {
        heading: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  industriesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  cta?: {
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    text?: string | null;
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
   */
  title?: string | null;
  desc?: string | null;
  faqHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: number;
  /**
   * Leave empty to use the automatic title. About 50 to 60 characters.
   */
  metaTitle?: string | null;
  /**
   * Leave empty to use the automatic description. About 150 to 160 characters.
   */
  metaDescription?: string | null;
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
   */
  title?: string | null;
  desc?: string | null;
  badges?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  answerQuestion?: string | null;
  answer?: string | null;
  proHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  shortHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  shortNote?: string | null;
  includesHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  includesPro?:
    | {
        icon?:
          | (
              | 'svc:seo'
              | 'svc:ppc'
              | 'svc:social-media'
              | 'svc:web-design'
              | 'svc:local-seo'
              | 'svc:content'
              | 'course:digital-marketing'
              | 'course:seo'
              | 'course:social-media-marketing'
              | 'course:ai-marketing'
              | 'course:graphic-design'
              | 'course:content-writing'
              | 'course:canva-design'
              | 'course:ai-basics'
              | 'course:wordpress'
              | 'course:video-editing'
              | 'course:freelancing'
              | 'course:meta-ads-basics'
              | 'ind:travel-tourism'
              | 'ind:ecommerce'
              | 'ind:cosmetics'
              | 'ind:medical'
              | 'ind:schools'
              | 'ind:hotels'
              | 'ind:clinics'
              | 'ind:real-estate'
              | 'city:karachi'
              | 'city:lahore'
              | 'city:islamabad'
              | 'city:rawalpindi'
              | 'city:peshawar'
              | 'city:quetta'
              | 'city:faisalabad'
              | 'city:multan'
              | 'briefcase'
              | 'award'
              | 'folder'
              | 'file'
              | 'video'
              | 'users'
              | 'wallet'
              | 'clock'
              | 'hammer'
              | 'upgrade'
              | 'trophy'
              | 'local'
              | 'chart'
              | 'map'
              | 'layers'
              | 'unlock'
              | 'link'
              | 'coins'
              | 'search'
              | 'pin'
              | 'pen'
              | 'chat'
              | 'mail'
              | 'alert'
              | 'grad'
            )
          | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  includesShort?:
    | {
        icon?:
          | (
              | 'svc:seo'
              | 'svc:ppc'
              | 'svc:social-media'
              | 'svc:web-design'
              | 'svc:local-seo'
              | 'svc:content'
              | 'course:digital-marketing'
              | 'course:seo'
              | 'course:social-media-marketing'
              | 'course:ai-marketing'
              | 'course:graphic-design'
              | 'course:content-writing'
              | 'course:canva-design'
              | 'course:ai-basics'
              | 'course:wordpress'
              | 'course:video-editing'
              | 'course:freelancing'
              | 'course:meta-ads-basics'
              | 'ind:travel-tourism'
              | 'ind:ecommerce'
              | 'ind:cosmetics'
              | 'ind:medical'
              | 'ind:schools'
              | 'ind:hotels'
              | 'ind:clinics'
              | 'ind:real-estate'
              | 'city:karachi'
              | 'city:lahore'
              | 'city:islamabad'
              | 'city:rawalpindi'
              | 'city:peshawar'
              | 'city:quetta'
              | 'city:faisalabad'
              | 'city:multan'
              | 'briefcase'
              | 'award'
              | 'folder'
              | 'file'
              | 'video'
              | 'users'
              | 'wallet'
              | 'clock'
              | 'hammer'
              | 'upgrade'
              | 'trophy'
              | 'local'
              | 'chart'
              | 'map'
              | 'layers'
              | 'unlock'
              | 'link'
              | 'coins'
              | 'search'
              | 'pin'
              | 'pen'
              | 'chat'
              | 'mail'
              | 'alert'
              | 'grad'
            )
          | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  howHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  howItRuns?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  campusFacts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  applyHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  faqHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
  };
  /**
   * Shown as an FAQ list and added to the page as FAQ structured data.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headings and intros for the pages that list services, locations, industries, blog posts and case studies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hub-pages".
 */
export interface HubPage {
  id: number;
  services?: {
    /**
     * Leave empty to use the automatic title. About 50 to 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use the automatic description. About 150 to 160 characters.
     */
    metaDescription?: string | null;
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    desc?: string | null;
  };
  locations?: {
    /**
     * Leave empty to use the automatic title. About 50 to 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use the automatic description. About 150 to 160 characters.
     */
    metaDescription?: string | null;
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    desc?: string | null;
  };
  industries?: {
    /**
     * Leave empty to use the automatic title. About 50 to 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use the automatic description. About 150 to 160 characters.
     */
    metaDescription?: string | null;
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    desc?: string | null;
  };
  blog?: {
    /**
     * Leave empty to use the automatic title. About 50 to 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use the automatic description. About 150 to 160 characters.
     */
    metaDescription?: string | null;
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    desc?: string | null;
  };
  caseStudies?: {
    /**
     * Leave empty to use the automatic title. About 50 to 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use the automatic description. About 150 to 160 characters.
     */
    metaDescription?: string | null;
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    desc?: string | null;
  };
  auditHead?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in green, for example: Get found on Google *across Pakistan*
     */
    title?: string | null;
    sub?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  ownerName?: T;
  brandTagline?: T;
  email?: T;
  whatsapp?: T;
  phone?: T;
  baseCity?: T;
  baseRegion?: T;
  campus?: T;
  campusCity?: T;
  campusArea?: T;
  officeHours?: T;
  yearsExperience?: T;
  websitesRanked?: T;
  clientsServed?: T;
  footerText?: T;
  authorBio?: T;
  whatsappMessage?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultMetaDescription?: T;
  founderSameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroDesc?: T;
  heroPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  cardRole?: T;
  cardLocation?: T;
  cardLabel?: T;
  cardPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  answerLabel?: T;
  answerText?: T;
  servicesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  coursesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  shortTitle?: T;
  shortText?: T;
  citiesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  industriesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  processHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  whyHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  whys?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  testimonialsHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faqHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  contactHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  eyebrow?: T;
  title?: T;
  lead?: T;
  cardRole?: T;
  cardLocation?: T;
  cardSkills?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  answer?: T;
  sections?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  industriesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  eyebrow?: T;
  title?: T;
  desc?: T;
  faqHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  eyebrow?: T;
  title?: T;
  desc?: T;
  badges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  answerQuestion?: T;
  answer?: T;
  proHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  shortHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  shortNote?: T;
  includesHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  includesPro?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  includesShort?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  howHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  howItRuns?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  campusFacts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  applyHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  faqHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hub-pages_select".
 */
export interface HubPagesSelect<T extends boolean = true> {
  services?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        desc?: T;
      };
  locations?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        desc?: T;
      };
  industries?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        desc?: T;
      };
  blog?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        desc?: T;
      };
  caseStudies?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        title?: T;
        desc?: T;
      };
  auditHead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        sub?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}